### ISSUE TITLE
Another instance of tomboy-ng appears to be running. Will exit.

### ISSUE THREAD

**Issue by tuxedotje** [tomboy-notes/tomboy-ng#104]
Error mesage: "Another instance of tomboy-ng appears to be running. Will exit."
How did this come? I Did read one note, than closed the window with note. I used "open with" tomboy-ng to read that one note. 
Want to open tomboy-ng again and this error is there. 
(now I will restart and I guess my problems are over. Because I do not know a ways to stop Tomboy-ng from running in background. . But maybe it is a bug??)
Using Fedora 31.

**Comment by tuxedotje** [comment]
tomboy-ng is slow when starting the program, or not showing up. Did restart PC and tried  to start tomboy-ng. Nothing happens, but when I try again same error message shows up.

**Comment by davidbannon** [comment]
tuxedotje, are you on top of the SystemTray issue ?  See the wiki, System Requirements, "Difficult Systems"  - unfortunately, Fedora fits into that category as they don't support the SystemTray icon approach. You have two choices really -
1. Install some tools that make things work as expected.
2. Leave what I call the "small splash screen" in place and interact with that rather than the SystemTray icon.
I am assuming that this is your problem, you have an instance of tomboy-ng running, cannot see the SystemTray icon but have clicked the 'Dismiss' button on the Small Splash Screen. That unfortunately hides everything. Another instance must not start up while that one is running, reboot or kill it from a terminal. I suggest that while experimenting, you start tomboy-ng from a terminal commandline, that way, if necessary, you can kill it with a Ctrl-C.
(Hmm, you can start a second instance if its single note mode.)
If this does not seem to address your problem, please get back to me.
Davo

**Comment by davidbannon** [comment]
Another useful trick is to start tomboy-ng with a -g (ie Gnome3 mode) switch, that way you cannot accidentally Dismiss the Small Splash Screen.

**Comment by davidbannon** [comment]
Nothing further required here apparently ....
