### ISSUE TITLE
(tomboy-ng:10969): Gtk-WARNING **: 15:32:52.617: Unable to locate theme engine in module_path: "adwaita",

### ISSUE THREAD

**Issue by tuxedotje** [tomboy-notes/tomboy-ng#106]
(tomboy-ng:10969): Gtk-WARNING **: 15:32:52.617: Unable to locate theme engine in module_path: "adwaita",
(srat Tomboy-ng in Terminal Fedora 31 and this warning :(tomboy-ng:10969): Gtk-WARNING **: 15:32:52.617: Unable to locate theme engine in module_path: "adwaita", In F31 Adwaita is a theme and is in usr/share/themes. I could change PATH for tomboy-ng to adwaita.

**Comment by davidbannon** [comment]
I suspect its not going to cause you any problems. GTK generates lots of warning that most users never see (and thats a good thing!). That one looks like an internal gtk thing. 
Is tb-ng working normally or is there some evidence of it not doing what you need ?
I don't know how the Theme Engines work but I suspect setting PATH won't help because its not really an executable. But I could be quite wrong.
I have not tested against F31 yet, my download bandwidth has taken a bit of a beating recently while we have been chasing a SystemTray bug that varies with each and every distribution (#!!!#).  As a matter of interest, do you see the Tray Icon ?  Do you have (eg) TopIcons installed ?
Davo

**Comment by davidbannon** [comment]
Hmm, not heard back from tuxedotje, I guess we have to assume things are OK ?

Please reopen if thats not the case.
