### ISSUE TITLE
version numbers are incorrect on macOS

### ISSUE THREAD

**Issue by core-code** [tomboy-notes/tomboy-ng#113]
i've downloaded version 0.24 but it claims to be version 0.1 when selected in the Finder.

the CFBundleShortVersionString and CFBundleVersion entries in your Info.plist file are incorrect

<img width="257" alt="Screenshot 2019-11-18 at 13 43 05" src="https://user-images.githubusercontent.com/1261954/69053337-7b6dd380-0a09-11ea-9c24-d805e2398811.png">

**Comment by davidbannon** [comment]
Indeed you are right.  Being a cross platform application, I try to avoid things that are unique to just one platform, as much as I can anyway.  You can see the version number of -ng by selecting the 'About' menu entry or, from the command line, --version

I'll look at rewriting the plist at build time, its messy XML so not sure how easy it will be, will try for the next release.

Thanks for that report, I was totally unaware of it.

Davo

**Comment by core-code** [comment]
thanks! if you need someone to test an improved build, just let me know

**Comment by davidbannon** [comment]
I'd sure like to know what version of OSX you are using, and does it work OK. I build and test on a single aging Sierra Powerbook. A very small test pool !  

Suggestions for a more "Mac like experience" would be good ....

Davo

**Comment by core-code** [comment]
> I'd sure like to know what version of OSX you are using, and does it work OK. 

i can confirm it launches on 10.14 but does not launch on 10.15 - because it seems to be a 32 bit binary

> Suggestions for a more "Mac like experience" would be good ....

below are some simple notes from trying out tomboy-ng just for a few minutes.
 
• even before launching the app you see some problem stemming from the Info.plist file. i've already mentioned the broken version numbers initially in this bug report. other entries in the Info.plist can probably also be improved to make them app integrate better in to macOS even before launching it, e.g. filling out the proper copyright information etc. i'd recommend creating a sample application using a recent Xcode version to see an up-to-date Info.plist sample file

• trying to launch the app is difficult on first launch because the app is not properly code-signed. however, proper code signing requires an Apple Developer Membership (100$)

• i've already mentioned that the app is 32 bit and will not launch on 10.15. even when launching on earlier versions of macOS you'll see nasty dialogues about how this app is not "optimized" (which is Apple's slang for 64 bit)

• weirdly, the app didn't launch for me on first launch at all, leaving the impression it has just crashed silently. i've opened Console.app before launching again to catch error messages, but for some reason it worked when double clicking again

• the "welcome to tomboy" dialoge is already very un-Mac-like. colors, are off. there is no white background in Mac apps. the buttons don't look like they should. and the whole dialoge was opened in the upper left corner which is confusing on a big screen. it should be in standard dialoge position which is slightly above the center of the screen

• for some reason i was unable to click the "dismiss" button in the "welcome to tomboy" dialoge and therefore (probably) unable to try out the main functionality of the app. i am not sure why this is the case

• therefore the only other part of the app that i was able to try out is the "settings" dialoge - which is also very un-Mac-like:

• the settings panel claims it will save data into ~/.config/.  this should never happen on a Mac. a Mac user will hate you if you save into a hidden folder in his home folder. apps are supposed to save their settings to ~/Library/Preferences/yourbundleidentifier.plist and additional data to ~/Library/Application Support/yourappname/

• the settings panel is a bit of a nightmare from a Mac user's perspective. all buttons are  nonstandard (in look and size). all spacings between the controls are nonstandard. the tabview is weirdly cropped on both sides left and right. the colors are off too. i'd suggest browsing through the tabs of Apple's System Preferences to see some halfway good examples of a Mac-like settings interface. and there is always the official document: https://developer.apple.com/design/human-interface-guidelines/macos/

sorry, i didn't try it longer - i hope some initial observations from a long-time Mac-user are helpful to you.

**Comment by davidbannon** [comment]
>  does not launch on 10.15 - because it seems to be a 32 bit binary
Which variety are you using ?  There is both a 32bit and a 64bit.  The 64bit upstream tools I use have only recently become mature. If you are using tomboy-ng64_0.24.dmg it should be all 64bit.


> .... proper code signing requires an Apple Developer Membership (100$)
Thats a $100 a year!  

> app didn't launch for me on first launch at all..
Now, that I don't understand. I might try completely removing it and reinstall to see if I can replicate.

> the "welcome to tomboy" dialoge is already very un-Mac-like......
Yep, that is an artefact of how it is built.  I don't know how many Mac users I have but not enough to justify building a Mac specific set of dialogues.  tomboy-ng is really only attractive to cross platform users so I assume they are comfortable with the app look and feel rather than a platform specific look and feel.

>  for some reason i was unable to click the "dismiss" button in the "welcome to tomboy" dialogue and therefore (probably) unable to try out the main functionality of the app. 

I prevent closing that "welcome screen" for a number of reasons, one is that there are, as yet, no notes present. If you made a note, next start will allow closing.   Again, this screen is a cross platform artifact, it is not closable at all on some platforms.  You can drive the app in all respects from that welcome screen (using the two menus), ignore it and use the Tray Icon or, if appropriate, dismiss it.  

If you cannot see the Tray Icon, that further reinforces my suspicion that you are looking at the 32bit version.


> the settings panel claims it will save data into ~/.config/. this should never happen on a Mac.
Agreed !   But its exactly where a *nix application should save its settings.  I would, for example, never be allowed to ship it via the Apple Shop. It works fine.

core-code, please don't think I am dismissing your concerns here. Far from it, but tomboy-ng is a cross platform application built from the one code base. When I started this project, I put two constrains on myself -
1) - Support the original Tomboy target platforms.
2) - Do so from the same code base to allow maintainability.

Tomboy did, for a few years have a functional Mac variety but as it forked away from the original, it required a totally separate, stand alone code base. And no one wanted to maintain that. Apple is a difficult platform to target, it constantly changes what it requires, its even worse that GTK !  I rely on Lazarus to look after that aspect for me and only have to maintain my code.

But I will look through your points and see what I can do without compromising maintainability.   Things like where to save config and data files can be easily made more Mac like, the existing model was just inherited from Linux.  But you will find if you have any other cross platform things installed, they probably are also naughty !

I guess I would be more motivated to cater to Mac sensitivities if I know I had more Mac users but, as I said, only real reason a Mac user would install tomboy-ng is its cross platform use.

Thanks core-code, very grateful for your input but would desperately like to know if you installed the 32bit or 64bit package !

Davo

**Comment by xypd** [comment]
**I wanted to share another Mac users point of view on some issues brought up. I appreciate core-code detail and specific reporting, big thumbs up! I would however say some words chosen may over inflate how some Mac user may feel the level of importance is.**

**This is not a criticism, more of adding another opinion to the mix.** 

> > does not launch on 10.15 - because it seems to be a 32 bit binary

>  Which variety are you using ?  There is both a 32bit and a 64bit.  The 64bit upstream tools I use have only recently become mature. If you are using tomboy-ng64_0.24.dmg it should be all 64bit.

**I'm currently on 10.14.5. I like to try avoid updating till all my key apps and driver are working with no issues. I do often update an ext drive for testing, but have not done so yet.**

**I've can't remember ever a version that didn't launch. I've used mostly the 32bit on advice of Davo, but have recently started using the 64bit vers.**

**I will agree with core-code here and say it still showing as a 32bit legacy in some places.**

**Here a picture of how Mac OS see it:**
![tomboy-ng_mac_24_64bit](https://user-images.githubusercontent.com/23583395/69211766-232ff200-0b2d-11ea-9239-7a334bc8a057.png)
 
> > .... proper code signing requires an Apple Developer Membership (100$)

>  Thats a $100 a year!

**I personally don't have a problem with this. yeah it would be great, but not realistic for dev who do this for free or as a hobby /love of doing it to spend money they don't really need to.**

> > app didn't launch for me on first launch at all..

>  Now, that I don't understand. I might try completely removing it and reinstall to see if I can replicate.

**Can't speak on this since I'm on 10.14.5. But I could see this being an issue from the new Mac OS 10.15+**

> > the "welcome to tomboy" dialoge is already very un-Mac-like......

> Yep, that is an artefact of how it is built.  I don't know how many Mac users I have but not enough to justify building a Mac specific set of dialogues.  tomboy-ng is really only attractive to cross platform users so I assume they are comfortable with the app look and feel rather than a platform specific look and feel.

**This doesn't bother me after I can turn it off in the settings. If you use many open source apps then you get used to the none Mac UI/UX. Lets keep in mind other large apps do this as well ( amity nicer looking) like adobe setting/open close windows are the same across platforms.**

> > for some reason i was unable to click the "dismiss" button in the "welcome to tomboy" dialogue and therefore (probably) unable to try out the main functionality of the app.
 
> I prevent closing that "welcome screen" for a number of reasons, one is that there are, as yet, no notes present. If you made a note, next start will allow closing. Again, this screen is a cross platform artifact, it is not closable at all on some platforms. You can drive the app in all respects from that welcome screen (using the two menus), ignore it and use the Tray Icon or, if appropriate, dismiss it.
 
> If you cannot see the Tray Icon, that further reinforces my suspicion that you are looking at the 32bit version.

**I just tried this works no problem. But again this might be a 10.15+ thing. Also I see the tray in the menubar no problem. Though I'm hoping to make it more attractive soon.**
 
> > the settings panel claims it will save data into ~/.config/. this should never happen on a Mac.

> Agreed !   But its exactly where a *nix application should save its settings.  I would, for example, never be allowed to ship it via the Apple Shop. It works fine.

**If it's easy then it might make sense to change it. Most Mac users will look for this where core-code mention.** 

**With that said, if you are using lots of linux apps then you will find them there too. I've seen some of these app putting file in the same place ... darktable, inkscape, meld, MusicBrainz, svgcleaner, tomboy-ng, xnconvert, etc.**

> core-code, please don't think I am dismissing your concerns here. Far from it, but tomboy-ng is a cross platform application built from the one code base. When I started this project, I put two constrains on myself -


> 1. * Support the original Tomboy target platforms.
> 2. * Do so from the same code base to allow maintainability.


> Tomboy did, for a few years have a functional Mac variety but as it forked away from the original, it required a totally separate, stand alone code base. And no one wanted to maintain that. Apple is a difficult platform to target, it constantly changes what it requires, its even worse that GTK ! I rely on Lazarus to look after that aspect for me and only have to maintain my code.

**There were some thing that work better in the old Mac vers (non mono), but there are many things that work great on the TB-ng version too. I would wish for example that nested bullet work better, or undo works or less conflict when synced (which is probably my old devices issue).**

> But I will look through your points and see what I can do without compromising maintainability. Things like where to save config and data files can be easily made more Mac like, the existing model was just inherited from Linux. But you will find if you have any other cross platform things installed, they probably are also naughty !

**I place functionality and reliability as the most important thing. Then usability and perhaps ascetics after. I also currently use it on both Mac and linux. So I'm grateful that it still working on the Mac.**

> I guess I would be more motivated to cater to Mac sensitivities if I know I had more Mac users but, as I said, only real reason a Mac user would install tomboy-ng is its cross platform use.

**I looked into other solutions, but they all have some compromises in some way ... as does Tomboy-ng. But right now it the one that work the best for my workflow.**

**Who know once I change my mobile set up it may open up other note taking apps, but not sure how much more they would add. But I keep an eye on project like https://www.qownnotes.org.**

Thank you both! Cheers

X

**Comment by core-code** [comment]
> Thanks core-code, very grateful for your input but would  t
> desperately like to know if you installed the 32bit or 64bit package !

sorry, i took the first .DMG download i could find, not even seeing it was a 32 bit download and a 64 bit download is available too. my mistake!

i am unsure if a 32 bit binary is of any value. Apple built very very very few 32-bit Intel Macs, and the last MacOS to run on them is 10.6. i doubt there are more than 5 of those still in operation, and i doubt even more there is a single one of those still browsing the internet and downloading apps.

**Comment by davidbannon** [comment]
Thanks folks for a very helpful conversation !  A few thoughts in no particular order :

32bit v 64bit- The 32bit Mac binary is considerably faster on slow hardware (including 64bit hardware). Its not really 32bit v 64bit, its carbon v cocoa widget set.  And, its only this release, 0.24 where I could call the Cocoa version fully functional, due to upstream development. If I put more effort into the github download page, yes, I could and should de-emphasis the 32bit version. I will soon have a similar problem on Linux, I'll be offering both a GTK2 and a Qt5 widget set option soon, and choosing the right one is quite complicated !

On my Sierra Mac (you will know the version number) I can use the finder to click "Get Info" and it shows me that, as core-code said, its version 0.1.  That I can fix.  But I cannot find anything that shows me the "bit-ness" of the app. xypd's image has two conflicting statements - what did you do to call up that report please ?
I am more used to using the file command, it certainly says the binary is a 64bit one. I am not sufficiently familiar with Mac linking but I do know you cannot, for example (easily) link 32bit and 64bit code into one binary. 

I will definitely look at moving where I store data/config.

And look forward to some nicer looking icons !

I think we are stuck with having to initially ctrl-click to start it as a non-apple approved app and use the somewhat clumsy dmg install. But it makes sense to clean up those issues I can.

That splash/welcome screen is an important part of keeping data safe, it pops up and cannot be dismissed if you have, for example, some corrupted notes.  Lots of new tomboy-ng users have expressed surprise when seeing very old notes that Tomboy had given up on, being reported here. There are also some built in tools to help recover those broken notes too. I hope you never need them !

Thank folks !

Davo

**Comment by core-code** [comment]
i can confirm that the 64 bit version looks better. the window backgrounds have the proper color instead of white. the buttons look better too, both in look as well as in size.

however, i was able to reproduce the problem with nothing happening on first start. Console.app reveals that the app is just terminated on first launch

<img width="649" alt="Screenshot 2019-11-21 at 18 45 49" src="https://user-images.githubusercontent.com/1261954/69362794-7de15f00-0c8f-11ea-8266-bf9dd07f924d.png">

**Comment by davidbannon** [comment]
For that "first start" core-code, you are doing a Control Click and then choosing "open" (or whatever) arn't you ? That is necessary because I have not paid a fee to Apple.
I understand after that first start, it opens normally ?
Davo

**Comment by core-code** [comment]
of course i am doing control-click to let it start despite not being properly signed. 

still, it will not open the very first time, just outputting the message listed above.

this happened both with the 32 bit version and afterwards also with the 64 bit version.

**Comment by xypd** [comment]
>But I cannot find anything that shows me the "bit-ness" of the app. xypd's image has two conflicting statements - what did you do to call up that report please ?
I am more used to using the file command, it certainly says the binary is a 64bit one. I am not sufficiently familiar with Mac linking but I do know you cannot, for example (easily) link 32bit and 64bit code into one binary

Hey Davo, you should be able to find out via the system information -> system report -> under software, applications.

- https://support.apple.com/en-us/HT203001
- https://appleinsider.com/articles/19/08/13/how-to-check-which-mac-apps-are-32-bit-and-wont-work-in-macos-catalina
- https://www.macworld.com/article/3393161/how-to-find-out-if-your-mac-software-is-32-or-64-bit.html

![](http://cdn.osxdaily.com/wp-content/uploads/2018/02/see-all-32-bit-apps-mac-1.jpg)

**Comment by davidbannon** [comment]
Wow, important apps like Warcraft III are still only 32bit ??
Good thing I prefer Warcraft II, it runs fine on Linux in a DOSBOX, far more stable than it ever was under Win95 !  I guess that means its 16bit ?

Seriously, thanks for that, I'll have a look later tonight. Her Ladyship is waiting on me to go out ....

core-code, I have no idea whats happening. Because its a one time issue, sounds like I have to make a new app each time to test for this problem ?   (And I prefer the "because I have not paid a fee to Apple" terminology, signing does not in any way ensure it does not, for example, contain malicious code, all it says is that I paid them some money. They based their OS on opensource code, they could at lease offer some concession to the open source community.)

Davo

**Comment by xypd** [comment]
Heh, this is not my info ... just one I found for your viewing pleasure ;).

But you're welcome, no problem. Also I also haven't forgotten about the icons, just more pressing project at the moment.

Still excited about seeing them in action.

**Comment by davidbannon** [comment]
> .... find out via the system information -> system report -> under software, applications.
Yep, found it. Did not know all that stuff was there. Interesting ....
And it reports on every version of tomboy-ng I have ever installed as, as core-code pointed out, they were almost all v0.1 !   But, yep, the 64bit one I have just installed with a proper version number is reported as 64bit.  So, thats good.  

I'll make a couple of new "hello worlds" and test for this first time failure issue.

Davo

**Comment by core-code** [comment]
> EDIT: No, I cannot replicate core-code's report of an app crashing first time it is run. Very strange indeed. Not sure just what I should do here ?
> Core-code, am I right in saying your experience is that it does run normally subsequently ?

it doesn't seem to be a real crash, because else we would have a crash log.

i've just tested on another Mac (with 10.15), and found the same issue there. however i wasn't able to find anything useful in the logfiles. also, i was unable to make the problem occur again by deleting ~/.config/tomboy-ng/

yes, it just happens one time, subsequently everything is fine.

i'd say ignore this for now unless other people see this too ;)

**Comment by xypd** [comment]
That is very strange core-code. I just thought of something, I'm wondering if it might be connected to [Apples SIP (System Integrity Protection)](https://blog.macsales.com/45473-we-explain-what-system-integrity-protection-on-mac-is-and-how-to-control-it/)

I know after 10.13 they added extra coverage features to it.

Thanks for all your trouble shooting.

**Comment by davidbannon** [comment]
Only outstanding issue here (with V0.25) is the difficult first start. I have added a line to release notes.  Thanks to  core-code for careful and detailed bug report. Thanks XYPD too.'
Closing in anticipation of 0.v25
