### ISSUE TITLE
Tomboy-ng 0.25 .deb package cannot be installed properly on older Debian systems (e.g., MX Linux 18)

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#118]
This was a nice Boxing Day present for my rpm-based system. However for my Debian-9-based MX Linux (have not updated yet) both the Gtk2 and Qt packages have been a problem.

First, the GTK2 package:
dpkg notes -- tomboy-ng : Depends: appmenu-gtk2-module but it is not installable (ng actually installs, but dpkg says it is not configured. tomboy-ng appears to work properly, but if I the MX package installer, I am blocked from installing/uninstalling anything -- and ng disappears from the.)

appmenu-gtk2.module was not available in any of the available repositories. I thought it was part of vala-panel-appmenu, but trying to install let showed appmenu-gtk2-module as a recommended package!

For the Qt version:
Gdebi notes that the dependency libqt5pas1 cannot be satisfied
Trying with apt.get simply fails to find the dependency

I suspect the problem in both cases is that I have not updated to the Debian 10 base as yet. However I may not be the only one -- and obviously the older Ubuntu LTS versions are based on Debian 9 -- yet, according to the release notes, the Gtk version should work.

**Comment by aguador** [comment]
Oops, my touchpad decided it was time to send this before I finished:

> First, the GTK2 package:
> dpkg notes -- tomboy-ng : Depends: appmenu-gtk2-module but it is not installable (ng actually installs, but dpkg says it is not configured. tomboy-ng appears to work properly, but if I the MX package installer, I am blocked from installing/uninstalling anything -- and ng disappears from the.)
> 
ng disappears from the systray.)

**Comment by davidbannon** [comment]
hmm, firstly, the Qt5 one is not for older systems. Even on my U18.04, while it runs initially, opening a particular form will crash it. U18.04 (released in April 2018) has too old a version of Qt5 available. You can force an update to libQt5Pas1 but the unattended updater will promptly overwrite it next day. (#$@!!)

The requirement for appmenu-gtk2-module is for newer, Gnome3 systems, it allows dbus comms between the app and Gnome3 style menus.  Its not necessary on older systems, especially true GTK2 ones but I cannot make a package that can decide at runtime. 

Your message is, I think, missing a word, "but if I the MX package installer,"  - what should that say ? "use" ?   Has trying to install -ng stopped your installer from working ?

I don't think appmenu-gtk2-module needs any config at intsall time (?)

I currently offer a plain .gz of just thr binary, its a long timr since that was appropriate, maybe I should replace it with one that has a bash script that will do the install on older systems ?   Put the desktop file in place, icons etc and, at the same time, check to see if any 'extra' is needed ?
Davo

**Comment by aguador** [comment]
It would be nice if other people weighed in, but probably not to be expected. MX Linux is interesting in being based on Debian stable (= old!), but maintaining updated applications (not cutting edge, but more up-to-date than deb stable and perhaps than deb testing on many things). I am not sure this will be an issue for many people given that most will either update or continue with basically unchanged systems.

It would be nice if installation did not depend on the latest and greatest, but it occurs to me that perhaps I should try competing apps to see if they will install in older systems.

**Comment by aguador** [comment]
Took a look at some "recommended" note taking programs and it is a mixed bag on installation. There are those that install simply and cleanly on Linux systems, including those based on Debian old stable. However, there are those that require some work. I am going to change the title and see if there is more feedback. If not, it may not be worth the effort of changing anything.

**Comment by davidbannon** [comment]
Might just add a clarification here.  I think there are two types of failures -
1. Binary incompatibility. I think this only happens with Qt5 version, Qt5 has changed over time but we have seen particular changes in the FPC/Lazarus support for Qt5. The people implementing it drew a line saying we support 'this' level. Before that, no hope, after that, 'probably'.  
2. Install failures. I don't make install kits for any particular distribution, release, Desktop or display manager. One of Linux's strengths is its diversity, however, it comes at a cost.  I test extensively on my Ubuntu 18.04, fairly thoroughly on the popular ones, U19.10 and Fedora 31 each with about 4 or five desktops. Wayland and XOrg. Then, a quick 'does it work' on a handful of others. 

Both issues, but particularly the second, could be managed if I was willing to  make and test packages for each, at least, distribution and release combination. I cannot !

Clearly, when you get a package from your distribution's repo, you do get something that has an install tuned for you and tested. So, IMHO, its about the install kit rather than the binary most times.

**Comment by aguador** [comment]
I agree that the Gtk2 issue is an install one that cannot be dealt with for every Linux system. The only disconcerting part is that a system on which the .deb package installed nicely before, it is no longer possible. If that has made life easier, or possible for other OSs, fine. The affected user base should be fairly small, perhaps some Ubuntuites on older LTS versions or those who plan to ride out Debian old stable for a while.

The Qt issue was already flagged in the release notes so clearly needs nothing more.

**Comment by davidbannon** [comment]
Yep, I am afraid that's the case. Things like U19.10 apparently need that package or they experience a long delay or even a crash at startup on a gtk2 app. It relates to how GTK2 apps talk to GTK3 over DBus now. So, after some tests, I added it to the dependencies.  Did not test on MX linux.Sigh....

I have, sort of, started working on a Bash script that installs -ng, all it does is put binary in place, put icons and desktop files in place. Does not address dependencies. The idea is I can have a list of known dependencies on each system. An end user who is already using an obscure distribution is capable of manually installing the packages if they know what they are. Maybe the script checks for key ones, but it advises, not installing them itself.
Davo

**Comment by davidbannon** [comment]
Yep, as you suggested, we also have a problem with Ubuntu 16.04.  18.04 is OK
So, its a case of balancing out Ubuntu 19.10 which badly needs this appmenu-gtk2-module but its not available at all on U16.04 or your MXLinux.

Or make yet another separate .deb file for 'older' systems. Or revert and tell the U19.10 to use the Qt5 version. 

19.10 only has a supported life of 9 months, I am waiting to see what the situation is with 20.04 which is a Long Term Release, maybe, just maybe, Canonical will have added this module to the GTK2 libraries that need it ?

**Comment by davidbannon** [comment]
Ah, at last this issue is solved !
The GTK debs are no longer dependant on this module.
(users of U19.10 must manually install it themselves.)
Thanks for the report.
