### ISSUE TITLE
Ctrl+Shit+Left/Right-Arrow does not select words at a time

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#120]
openSUSE 15.1 (Leap)
KDE
tomboy-ng 0.25.2 from QT5 RPM

I thought Tomboy was dead, and I've delayed moving from my old openSUSE system for years because of concerns about needing to migrate to Gnote, and then I found this project last night and am very thankful that it exists.  With that said, I have found a couple issues I would like to help resolve as I can (I have never programmed in Pascal, but I could learn).

The current issue, which I could not find searching old issues, is that holding Ctrl+Shift and using arrow keys usually highlights a word at a time in the direction of the arrow key, which is really useful with the way I take notes (lots of them, 4200+ so far and 45 MiB in size).  Ctrl+arrow works to jump words at a time, and Shift+arrow works to select text characters at a time, and Ctrl+Shift+Arrow works in other applications on the box (e.g. kate, LibreOffice, etc.).

I'd be happy to do some testing or possible fixes on my other box (same versions, upgraded to be sure tomboy-ng would work prior to upgrading my main box here), or even to do some development on there if I can et some pointers about how to start.  I could also possibly record/post a video with an example of the issue, in case the description above is insufficient.

**Comment by davidbannon** [comment]
I think you are the second user in a couple of weeks to ask for this. I don't think it would be too hard but does involve more code intercepting each key press. At my typing speed not a problem but some people type really fast !

In the editbox unit, there is a procedure KMemo1KeyDown(), we'd need to watch for Ctrl-Shift + Arrow (and Ctrl+Arror) and move selectend accordingly. I think KMemo has some code to jump words but not everything in kmemo works right now ! While its really great code, its poorly documented.

Definitely not "real hard", given the interest, looks like it should happen.

Tell me dajoker, how do you find tomboy-ng's responsiveness given your 4K notes ?
One day, I'd like to move the notes into a database but that would break compatibility with Tomboy.

Davo

**Comment by davidbannon** [comment]
OK, have committed code that makes ctrl-shift-arrow and shift-arrow work as expected.
Turned out to be very easy. But don't let that put you off having a play with the code dajoker !
Lots more things need fixing !

**Comment by dajoker** [comment]
Well that's great!  Thanks for taking that on.

I'm not sure what the right process is here, if I should comment/close or just comment, but feel free to enlighten me.  In most business environments I do the opening and engineering/development does the closing after releases happen, so for now I'll leave it open.

**Comment by davidbannon** [comment]
I tend to leave them here as a reminder until I release the next version. I then like to clean up the list a bit.  If you want to be experimented on, I'll cut you a binary, GTK 64bit I expect ?
Davo

**Comment by dajoker** [comment]
Works for me, and yes please.  RPM-based, if that works, or else I need to get the build working here so I can just do it directly, especially if we end up doing this a bit (fine with me).

**Comment by davidbannon** [comment]
Easiest for me, **hardest** for you is for you to setup your own Lazarus install, pull down from git. Honestly, you would need to put aside several hours, things you are probably unfamiliar with. Not hard, just unfamiliar always take a bit of extra time. There is a doc in the wiki, I should probably review it before you start.
Pretty easy for both of us is, as long as you already have an install, I send you a zipped up binary.  (Don't know why I use zip instead of gz, think its because lots of Windows users and zip works everywhere).  You can then either put that binary somewhere and call it directly or use it to overwrite the one in /usr/ bin   I keep my test ones in ~/bin and my path looks there before /usr/bin, works for me.
Thirdly, yep, easy to send you a test rpm. I generate packages on another machine, and always stamp a new version number to prevent confusion, not trivial but pretty easy. Advantage is you get xypd's pretty new icons, but rpm requires you to remove the old one first, as root obviously.  Other down side is that its difficult to switch between the 'official' one and what ever you are testing. 
Davo

**Comment by dajoker** [comment]
If you want to verify the wiki is correct I'll try #1 first, since that might be useful to have reviewed by somebody else (are you the only builder currently?), and maybe I can find some way to make it easier on my side (i.e. I'll create a script).  If you happen to have a .zip (or .7z, or .tbz, or .tgz) archive, I'll use that on my test system for quick validation too.

**Comment by davidbannon** [comment]
Yes, only builder currently but some others have built it in the past.
I have updated the content of build.note in the doc directory. Its the source of the wiki build page which I have not, yet updated.
If you have any issues (bet you will) please open another ticket.
Good luck !
Davo

**Comment by dajoker** [comment]
The selection works as expected in Lazarus, so I guess that means this is working.  I have tested a bit as shown in this little video thingy which I thought might help confirm stuff, or help others know what was meant for the desired functionality in the first place, so I'll try to do this more often since Peek makes recording on here super-simple.

![2020-01-03-ctrl-shift-selection-working](https://user-images.githubusercontent.com/307648/71759864-31ce3080-2e71-11ea-94fb-f84c92e8f848.gif)

As a small note, while I can Ctrl+Shift+Left/Right to move words at a time (and eventually across lines as I reach the end of one), Ctrl+Shift+Up/Down does nothing while Shift+Up/Down does work a line at a time (see video).  Not a huge deal, but if it took almost no work to make Ctrl+Shift+Up/Down work like Shift+Up/Down, that might be a better match for how other editors work, maybe.

I tested in LibreOffice's Writer and KDE's Kate for comparison, and LO Writer does allow Ctrl+Shift+Up/Down to select stuff; Kate actually moves the selected text up/down when doing that, so not the same everywhere.

**Comment by dajoker** [comment]
Building Tomboy-ng on openSUSE Tumbleweed was done with these steps, followed by building kcontrols and then opening the project file within Lazarus:

sudo zypper install git vim-plugin-fugitive lazarus make
gitRepoDir="${HOME}/code";
mkdir -p "${gitRepoDir}";
cd "${gitRepoDir}";
git clone https://github.com/tomboy-notes/tomboy-ng.git;
lazarus tomboy-ng/Tomboy-NG.lpi;

I did not see an obvious command line argument to have Lazarus add the kcontrol thing, but if anybody knows of a way to script that it would make this whole thing automated; as it, that's the one step left I think.

**Comment by davidbannon** [comment]
That way you will get a substantially older version of Lazarus, while you may be able to patch it, but that will only find the problems I found and fixed, newer Lazarus is a lot better.  I would not recommend use of anything earlier than 2.0.6

And you do certainly need to patch KControls before building, without that pasting multiline plain text near the end of a note messes up. I have had a bug report and fix for that in for about two months, sigh ....
In fact, you don't need Lazarus but do need the LCL (Lazarus Component Library). There is a purely command line script in there, 'buildit' from memory, but it does not wait for the patching of KControls. Might be in the main -ng source directory rather than /package. I am not sure that I recommend it .... 
Davo

**Comment by dajoker** [comment]
Just to be clear, the version of Lazarus installed using the method above was lazarus-2.0.6-1.2.x86_64 and, as a result, I assumed that was good enough (no need necessarily to rebuild from 2.0.6 to 2.0.6), especially since testing had everything working nicely.  If I can find a way to patch KControls from the CLI I'll add that, but so far the steps you had on the wiki for that made it simple.

I see biuldit.bash under the tomcat-ng directory in the repository, but it fails, I think because I lack a 'Pascal' directory in my home directory.  No worries if not recommended; Lazarus was simple enough.

**Comment by davidbannon** [comment]
Ah, I am impressed, openSuse are shipping Laz206 ?  Are you using tumbleweed or Leap ?
Anyway, excellent. From memory, 2.0.6 lacks some code to select the right TrayIcon on particular Gnome desktops, mainly Fedora.  To my surprise openSuse displays the Icon OK, I have not tried Tumbleweed, it probably uses a newer Gnome. And Wayland......

**Comment by dajoker** [comment]
That was on my test rig, so Tumbleweed; Tumbleweed's purpose is to basically have the latest of everything, so being current is its job, sometimes to a fault (new code sometimes has bugs, or so we hear ;-) ).

Leap ships with 2.0.2 currently, but you can get 2.0.6 for it from either the Education or the devel:languages:pascal branches on the Open Build Service (OBS): https://software.opensuse.org/package/lazarus

My test rig is KDE, so I'm not sure about the Gnome or Wayland stuff there.

**Comment by dajoker** [comment]
Verified fixed in 0.26 release.

**Comment by davidbannon** [comment]
Great, thanks
