### ISSUE TITLE
Using double-quotes to search does not treat enclosed strings as a single search token

### ISSUE THREAD

**Issue by dajoker** [tomboy-notes/tomboy-ng#122]
tomboy-ng 0.25.2 (qt5 RPM)

I suspect this is an enhancement, but it was how Tomboy (Mono) worked, and I am missing it already.  Basically if a search term is quoted, e.g. "daily note", then the search should only searches for instances of "daily" followed immediately by a space followed immediately by the string "note".  Currently it seems that instead the search function tokenizes everything between spaces (0x20) and searches for those strings.  Unfortunately, this means that searching for "daily note" actually searches for things that have both:
"daily
and
note"
somewhere in them (line brakes added for clarity), which is seldom what is desired.  I have tried with single-quotes, just in case, but no luck there either.  Ideally I think the case-insensitivity setting (if checked) should still be followed, as that is how Tomboy worked in the past, but it would be great if quoting things worked differently.

As before, if somebody can point me at the correct place to impact this functionality I'd be happy to try fit it myself.  I'm on Linux, so I presume it should not be too much work to figure out how to clone the git repo (I can do that part for sure) and then get the build working (might need help there).

**Comment by aguador** [comment]
Actually what you want in -ng is the default situation. If there is a problem it is that there is no "or" operator.

First, note that there is a button for options, which allows you to search for "any combination" or not. If that is NOT checked (which I believe is the default), the words in the search box are treated as a single string or token.

For example, I have one note on one of my computers that contains "problemas traducción". If I search "problemas" from the search form, four notes are found (including that one). If I search "traducción" two are found (including that note). If I search "problemas traducción" (without the quotes), that specific note is found. If I search "tracucción problemas" (that order, no quotes), no notes are found. (If I search "problemas traducción" [with quotes], NO notes are found as the search is for the string INCLUDING the quotation marks -- which does not exist.)

Second, if the "Any combination" is checked, the order is ignored: "problemas traducción" and "traducción problemas" (both without the quotes) yields one note. The "Any combination" option simply ignores the order of the terms given, but has to find both of them in the same note.

If the search operated as you expected (and as you might expect in a search engine), "problemas traducción" without quotes should yield 5 results because it would include all notes with EITHER search term.

**Comment by dajoker** [comment]
I appreciate the time taken for that response.  Happy New Year.

First, I am not completely sure I follow all that you wrote, so please correct me if that is the case.

I saw the button with the options you pointed out, including the "AnyCombination" (sic) option, but while I think that's a good option to have available, it does not change what how I think it should work, or how it worked in Tomboy (mono), or how I think search engines I use (Google primarily) work.  My understanding of how things did/do (Tomboy/Google) work when double-quotes surround something is that the quotes themselves are not part of the search term, but the entire string within (spaces and all) is considered one big search term, not a bunch of individual strings.

The difference for me is that I regularly search for a bunch of these multi-string (where string is defined as a space-delimited something) search terms, all at the same time.  While the AnyCombination option does work if I leave out all double-quotes, it does not work as well as it could if the system would do as suggested in this enhancement request.

To help make this clearer, and possibly point to my own bad practices as being at fault for causing this, I create at least one note ever day, and have for years, and it is named, for example, with "Daily Note" somewhere in its name, along with the current date (e.g. 2019-12-31).  In there I keep track of work stuff done for the day (I'm an independent contractor, so tracking what I do matters to people who hire me).

In addition to those daily notes, I also create notes for lots of other things; journal entries, specifics about a visit to a client, neat things I figure out at the command line, etc.  Computers are meant to store data, and while many people may use a 'documents' directory to store lots of files, I just use notes to hold tons of miscellaneous data.  It has worked fairly well, though the Mono version had its own "quirks" (memory usage, wow!).

Back to my use case, I regularly want to search only in the things that are daily notes, but the words "daily" and "note" end up all over other notes because they are common words, and I do not want any notes that do not contain that exact string (maybe a bit longer with a particular year or something right after it, like "Daily Note 2019" to rule out previous years' notes.

If I can get a double-quoted string to be a single search term, as Google and Tomboy  (Mono) do and did, then I can search for something like this:

"Daily Note 2019" ldapsearch cupcake

This might find me all the notes from this year which had me running an ldapserach against a server called "cupcake".  The last two terms can be anywhere ("AnyCombination"), but the first search term needs to be that entire string, or else I might get commands from other years.

Maybe that helps, or maybe I missed your point.  I think this is different from what you described, but feel free to correct me as you see fit.

Happy New Year!

**Comment by aguador** [comment]
You are right that I did not respond properly to your original post. As you note, searching the two words (daily + note) with "AnyCombination" yields all instances win which both search terms appear, whether together or not.

However, the **capability** you want to **match a string exactly** is the default -ng behariour (that is, no quotation marks, "AnyCombination" not checked). So what is missing for you is not the capability, but invoking that capability with quotation marks as you did in Tomboy or do in a search engine.

Beyond, that, your point that "AnyCombination" is seldom wanted is arguable. In the example I tested, "problemas traducción" appeared in the name of the note. Had it been in a complete sentence it might have been "problemas de traducción", "traducción con problemas", "traducción de problemas", or in a list in shortened form as "traducción, problemas" or "problemas traducción" (given that we are, after all, talking about notes rather than formal texts). If I cannot remember how I may have written such a phrase, I may indeed want all instances in which both terms appear.

What is not possible in your case is retrieving all notes that have **either** "daily" or "note". To use a hypothetical, let's say I wanted to retrieve all notes that talked about errors. Given that I might have used "error" or "mistake" (not to mention "blunder", "gaffe", "faux pas" and others!) I would want to see all notes containing either word, which I cannot do at present in a single search.

In summary, tomboy-ng covers two of three possible cases in a two-term search:

1. exact match (without AnyCombination)
2. both (with AnyCombination)
3. either/or (not possible at present)

If you can have only two of three, whether 2 or 3 is more important is likely in the eye of the beholder.

(Veering a bit off topic: this exchange has prompted a bit more exploration on which **Davo might wish to comment** and about which I may want to open a feature request. I just tried "problemas and traducción". Without "AnyCombination" there are no matching notes. However, with "AnyCombination" the note with "problemas" and "traducción" in the title appear. The word "and" does not appear in the note, but is present in the middle of a word in that note. That is,  the searches are for strings not for whole words. Can whole word searches be implemented easily?)

**Comment by dajoker** [comment]
Ah, I think I better understand you.

The either/or functionality would be a nice-to-have, but I use it so seldom in a search engine that it's not something I'd try often enough other places unless I'm actually using regular expressions, but that's probably a whole other topic, and if that happens to be a way to mete your #3 as well as my desire for what I'm after I could live with that, though it'd be non-trivial regex implementation to do the fairly-simple thing I'm after when combined with "AnyCombination".

As a note, I did not mean to dismiss the use of "AnyCombination" generally; in fact, I think most people would want that as a default, though perhaps only because that's how search engines work.  Text editors typically do not work as Tomboy-ng does, and that's great, but that will lead us into a discussion about whether the main Search feature (among notes, not within a note) is more like a search engine (I would argue yes) or a search feature within a basic text editor.

I've seen text editors that had a "whole word only" option, basically putting in word boundaries around search terms regex-style, and that might be nice to handle your "and" case, but that might mean a big change in the search functionality again (to something regex-y).

Anyway, I'm still interested in double-quoted strings being treated as a single string to match within notes, including their titles.

**Comment by davidbannon** [comment]
Interesting discussion !  I think I follow what you mean.   If we have a couple of notes that have, respectivly, the following content -

Note1 a b c
Note2 a c b
Note3 c a b

and we search for ["a b" c] you want to get Note1 and Note3, 'c' can appear anywhere but 'a' and 'b' must be exactly one space apart ?  Possible but would slow down searching. Unless I am mistaken, Google no longer searches like that, used to but now anymore. Thats why I switched to duckduckgo because it does let me that specific. And, I believe, google claim it confused people searching for double quote marks (is that really a problem) ?

Yeah, could be done I think.

**Comment by davidbannon** [comment]
aguador, at present, as you guessed, without "AnyCombo", it searches for string. So, the spaces are not deliminators, they are part of the search string. With AnyCombo, the string is broken up by spaces into discrete words and any one will work.

Does highlight how hard it might be to provide everyone's idea of a search and keep it simple. I wonder if we need a more elaborate search mode ?  No, I'd not suggest regex dajoker, I don't want to explain regex to Windows users.  But an "Advanced Search" button that opens a form allowing several strings to be entered, each line a search string and logical AND or OR between them ? Or is that getting too cumbersome ?

**Comment by aguador** [comment]
I have been thinking about the issue as well. I think that way search currently works is probably close to a default for most applications. The question is whether there are people like Aaron/dajoker with hundreds of notes. For me, hitting around 100 notes would mean that I need to delete some or convert them to something more substantial given that I use these applications for shorter term things: e.g., recent bug reports, notes on things to do or follow up on. So it depends on the broader -ng user base . . . .

**Comment by dajoker** [comment]
@davidbannon I think Google still works that way, handling double-quotes as suggested in this "issue", or at least it seems to in my testing.  Certainly the results change, getting smaller, whenever I add them around search terms after a completed search, and the summaries of results I see seems to support that.  Anyway, that's them, not Tomboy, so just a data point.

Yes, your summary of what I'm after is basically what I am after.  While it's a bit more complex, thus slower searching as you pointed out, I'm guessing even over my few-thousand notes it's going to spend less additional time searching than I spend refining the results or manually looking for the right thing, so it might take another second, or two, but I'm taking much longer to get through the huge set of results than I would spend through a smaller set of results.

Ultimately I think most people today probably don't use double-quotes at all in searches in -ng, so most users would probably not notice a change, but for those who ARE using double-quotes, I would guess they are doing so for the same reason I do, in order to make one bigger space-ridden search term.  Of course, it'd be nice to know rather than merely to speculate.

Just to be clear, this isn't my top priority, though it'd be nice to have, and maybe easier to implement than some other things (e.g. "undo" in the editor).

**Comment by davidbannon** [comment]
OK, its far too hot here to go outside today so had a play with the code.

I have checked in code that implements this, or, what I am pretty sure is this !  It only affects things if you have AnyCombo selected, does not make sense other wise. I have also added code to show a hit of the search options state when you hover the mouse over the button to make it a bit clearer.

Not well tested yet.

**Comment by dajoker** [comment]
Testing in Lazrus looks so beautiful!!!!  The search works just like I thought it should.  I haven't tried much, but I've tried searching through my test notes, gradually limiting the results with a couple quoted strings, and some non-quoted strings, and it all seems to be great!  Thanks for taking that on.

**Comment by aguador** [comment]
OK, I have not seen this in action, but if I understand what Davo has done it is to create two ways to search exact strings: 1) without AnyCombo and without "", 2) with AnyCombo and with "". This means that there is a) no increased functionality and b) more potential for confusion. (The only difference I can imagine here is it that if, for some reason, I wanted "" included in the search string I would have to use double sets of "" in case 2.)

Sorry, dajoker, but I think this is a **_very_** bad idea. I know the -ng behaviour is different from the Tomboy one, but the -ng behaviour **is the default** in other applications such as LibreOffice Writer or text editors such as Leafpad. This is also the default behaviour when searching on a web page. As an example, go here - https://en.wikipedia.org/wiki/Google_Search - and search on the page for "Google Search" (without "") and only exact matches will appear (e.g., it will omit the "Google Web Search" string). If you search with "", you will find only one instance in which the string appears with "". This is exactly what -ng 0.25 does and it is the way text-based searches are **_supposed_** to work. While Tomboy may have used browser-like searches, neither it nor -ng are browsers.

Sorry if I have overdone the bold and italics, but I really do think this change is a bad idea and one which should be reverted. If Davo is going to spend time on search, it should be on an advanced search, **_if_** there is demand for it and as a longer term project.

**Comment by davidbannon** [comment]
Yes, I agree its a hard concept to present (but we did mention Regex as an alternative).  I am half wondering if needs three 'modes', with the "use inverted commas as a third one".  Its definitely not a four way, 2x2 matrix.  

D

**Comment by aguador** [comment]
Yep, you mentioned regex. Having two (or more) ways to do the same thing is not the end of the world, but it seems to me the options we are used to in the broadest sense is between basic search and advanced search. So basic search would be the most common way, which I have argued is simply entering a string of words and searching for an exact match (the current -ng default), and normally one that is not case sensitive. Anything beyond that might be considered advanced search with and, or, wildcard, and all the many combinations and permutations (or some significant subset of them) offered by regex.

However, if there are no more options than exact or AnyCombo with the "" being used to override the latter, why retain the current exact match default? Simply use AnyCombo as the default and require quotation marks for exact match. That is not necessarily my preference, but it makes a great deal of sense under the current scenario as it allows you to eliminate the need to set an option. The options box could then simply be a check box for case sensitivity rather than options that need to be shown by hovering about!

Adopting regex raises a more existential question: what niche is tomboy-ng to fill? Is it to be a turbocharged Evernote-type competitor -- in which case the more flexible/powerful/complex the better, or something intermediate between that and temporary sticky note reminders -- which would argue for user-friendliness over power?

**Comment by dajoker** [comment]
@aguador I think what you wrote is only half of the result which I requested and which @davidbannon implemented.  Yes, you can now search for exact strings using either no-AnyCombo or by using AnyCombo and a double-quoted string and the functionality is (or should be) identical if you have just one search term.

What is new now is that you can also have multiple search terms with spaces in them, in any order.  The order may not be the biggest deal, but the ability to search for many of them without having one big search term is really nice, and that's new.  The original way of no-AnyCombo means you only get one big search term, no matter how long, that must be exactly in any matching note.  Now I can know a few clues, with spaces in them, that may be in the notes and that makes finding much easier.

Regex would be nice, but it wasn't the goal of this particular issue, at least for me.  I think it'd be a good issue on its own, but I think it'd be something else entirely.  I use regexes a lot in things like vim, JEdit, or Notepad++ (when on windows), but usually more in the search/replace sense than in the "find in any note" sense, but that's just me.

**Comment by aguador** [comment]
@dajoker You are absolutely right. I was not thinking about the cases of 3+ terms where only some of them are treated as a unit. I have been missing a key point, which was stupid of me. I would now reverse my position: the exact search should just be eliminated as the default. There is no need to have two ways to do the same thing, especially when one of the ways is more flexible.

The changed behaviour can be flagged in release notes for current users, and, perhaps be covered in a note in Setting for new users, something like:

_tomboy-ng search operates in a browser-like way in that searches will be for any combination of multiple terms. Place all or some between quotation marks ("") to have them treated as a unit to be matched exactly. Set default case sensitivity here. It can be changed on a per-search basis in the search form._

Of course default case sensitivity need not be set in advance, but simply via a checkbox for each search (defaulting to remembering the last selected). In that case, there is no need for anything in Settings, and the interface becomes even simpler so that where it now says simply "Search" in the search box it could say:

_Search: exact matches for terms between " "
Buscar: usar comillas para búsqueda exacta_

(The Spanish is less specific, but should work and both fit in the search box.)

**Comment by davidbannon** [comment]
OK, now that #128 has raised its ugly head, I would like to push out a fix. And perhaps at the same time, deal with this.
Right now, the search does, sort of, operate in two and a half different ways. I agree with aquador, it needs to be simpler. Even my obsession with allowing the user to change everything has its limits !
So, following aquador suggestion, I will remove the Search Settings button and associated menu and replace them with just a tick box setting case sensititvity.  The state of that tick box is automatically reflected in the Settings page and saved whenever its changed. And, obviously, remove the tick box from Settings that controls search. 
Will experiment with setting a 'hint' on the search entry field that mentions the inverted commas as per aquador's example above.
Thoughts ?

**Comment by dajoker** [comment]
Verified fixed on 0.26 version.

**Comment by davidbannon** [comment]
great !
thanks
