### ISSUE TITLE
Ubuntu 18.04 problem

### ISSUE THREAD

**Issue by pisulski** [tomboy-notes/tomboy-ng#124]
I search a notes like this.
I installed before a tomboy.
Later I installed tomboy-ng.

When I close all notes and next i try open it again i have error

Another instance of tomboy-ng appears to be running. Will exit.

Something was wrong.

**Comment by davidbannon** [comment]
Hi pisulski, thanks for your report.
You get that message in versions of tomboy-ng up to v0.24 when you try to start a second instance. Its a bad idea to have two instances running at the same time so I check to see if another one is running at starts up.

( The current version, V0.25, does this much better, rather than giving you an error message, instead, it automatically opens the first instance's seach window and closes itself down. )

So, to solve your problem, look to see if you do already have one copy of tomboy-ng running before starting another.   If you cannot see the System Tray icon but still get that error message, it is possible that tomboy-ng has crashed but left something running in memory. 
To see if there is a 'zombie' tomboy-ng running, try this command at the command prompt -

ps aux | grep tomboy-ng [enter]

It will probably pick out and show you the command you just entered but if it also shows a second entry that has been running for longer, there is your problem. 

You should upgrade to the newer version, V0.25.   But if you do upgrade, please make sure the older V0.24 is not running  before you start the new one !  Thats quite important.

If you have problems wih tomboy-ng crashing, please start it from the command line and see if you see some error messages. And let me know !

Davo

**Comment by davidbannon** [comment]
Hi pisulski, have you noted that 0.26 is now available ?  I recommend .....
Davo

**Comment by davidbannon** [comment]
OK, guess this is all OK now.
D
