### ISSUE TITLE
Notebook search issues

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#133]
Two minor things have popped up as I have resumed using notebooks on one of my machines, which means using some notebooks created with old gen Tomboy (which may/may not be relevant).

System: Mageia Linux with 0.26, Gtk2, dark theme

First, in the **bug** category: in moving notes around and creating a new notebook I have seen this two or three times, yet I have not been able to recreate the exact steps which led to it. Some combination of searching in a notebook and editing or creating or assigning a note to that notebook and closing the search form, leaves not only the notebook filter active, but fails to show the other available notebooks. That is to say what shows in the "filter" pane is the notebook header with only the selected notebook listed. When the "Clear filters" button is clicked, the other notebooks reappear.

**For users reading this**: Could you try to reproduce this?
I will post later if I can hit on the magic sequence to reproduce it.

Second, in the **behaviour** category: if one opens search and chooses a notebook to find a note quickly (with small notebooks you may be able to have all of them in the search pane, obviating the need for a name/keyword search) and close the search form without clearing the notebook filter, the filters are not cleared. This has two effects: a) reopening the search form the notebook filter is still active and b ) only the latest notes from the notebook filter applied show in the popup from the systray. It is even possible to have the filter set to a notebook which no longer has any notes, particularly disconcerting in the case of the popup.

To elaborate a bit more, in the case of the search form, if I have applied a notebook filter without selecting a note, the form reopens showing the seleted notebook outlined in red. However, if a note had been selected, the note is outlined in red and not the notebook, the application of a notebook filter being less obvious in this case.

1) Is this behaviour intentional? The most desirable? Shouldn't the filters be cleared automatically in closing the search form?
2) Whether or not the filter can be cleared when closing the search form, would it not be desirable to leave the notebook selected highlighted in some way? I know that the "Clear Filters" button is active, but it would be nice to know what filter is applied.

This leads to a possible solution to both these issues: a) Change the "Clear filters" button to a toggle between "No filters" and "Filter(s) applied:" and b) make what I assume to be the anomolous behaviour the norm by showing only the notebook (or other filters if added later) selected in the filters pane. Complication: this would also mean adding some sort of indication of filtering in the popup as well, or showing only the most recent notes with no filter applied (which may be even more complicated to pull off).

Sorry, this has become a lot more complicated to explain that expected. I hope it is at least somewhat clearer than mud.

**Comment by davidbannon** [comment]
Yes, I have a feeling dajoker was also a little confronted by seeing the 
popup menu containing only notes present in current selected notebook.

Seperating them does involve quite a bit of restructuring, I use the 
grid they appear in on the search page to sort and maintain the recent 
list. But its actually a slow process and maybe should be done by a 
standalone list. As such, it would be faster but use a touch more memory.

Hmm....

Davo

**Comment by davidbannon** [comment]
Hmm, actually, not that hard at all. And the restructuring does provide a useful speedup too.
I now sort the note meta data directly, by the nature of the data structure, that is pretty fast. I don't update the content displayed in the search window if its closed and thats a substantial saving.
But, importantly, a byproduct is that I populate the menus recent note list from the data structure itself rather than the searchwindow data. So, not filtered.

If anyone complains, I can, I think provide an option.
Davo

**Comment by davidbannon** [comment]
I have committed code to break the main menu recent items away from the search results.  And a few other fixes.
If you want to be experimented on, there is a 64bit tgz (no rpm, deb nor 32bit) that you can extract the binary from and either over write the one in /usr/bin/tomboy-ng or put somewhere you prefer.  It reports itself as v0.26d

**Comment by aguador** [comment]
OK, a couple of quick tests shows that the popup is good -- most recent notes. The list of files is also back to all by date with most recent first. However (sorry, you knew that was coming, right?), the filter pane makes it look as if the notebook filter is still being applied, i.e., only the notebook(s) where notes meeting the last search are shown. Any way to clear to filter to clear the conflicting messages?

**Comment by aguador** [comment]
One other thing related to behaviour with some more playing around:

- Search for a term
- When the results appear, the search term is highlighted (easy to erase/overwrite)
- Close the search form
- Reopen the search form and the search term remains highlighted/selected (can close & open multiple times and term remains selected)
- Although the search term is highlighted and only the notebooks with notes containing that search term shown, the results are not there. So to see them again:
- Click on Update
- Results reappear, BUT the search term is no longer highlighted/selected

I would expect the search term to remain selected after Updating the search

This is a very minor issue, but I assume one that can be corrected/made consistent easily.

**Alternative** (dajoker and others, please comment if you are following this"):

Rather than selecting and highlighting the word, after a search/update have the cursor positioned at the end of the search term. This approach is close to that of search boxes on internet sites or the search bar in Vivaldi and FF. For ng this alternative comes with one disadvantage and two advantages:

- Disadvantage: changing the search term requires selecting or erasing it (a relatively minor disadvantage) - or a clear button (see below)
- Advantage: the update button can be eliminated
- Advantage: by eliminating the update button, the search from can be smaller, more like original Tomboy ([http://media.ladda-ner.nu/2011/11/tomboy-anteckningar.png](url)) -- which I had forgotten had a small clear button rather than an update one

For me the search box on old Tomboy had a simplicity that was not only aesthetically better, but seemed more user friendly. The two basic columns one needs are note title and last update. The creation and file name could be hidden columns capable of being viewed by enlarging the box. The "clear search box" button worked nicely with simply a relatively well-known icon. As I recall that approach allowed searches of either all notes or selection of a specific notebook in which to search, which could be nice (and faster) for those with many notes. Like old Tomboy, we are then also talking about getting rid of the clear (all) filters button, a further cleaning up of the search form appearance.

OK, I started with what seems an easy-to-solve inconsistency in behaviour and have proposed a redesign in the end. Perhaps I need to pull this out as a feature request???

**Comment by davidbannon** [comment]
OK, in reverse order ....

**proposed a redesign** - I have been working on a redesign of the searchform, that beta you saw is quite different.  But am stuck with things that do relate to this thread. In particular, when to refresh the searchform results.  After you do a search, suppose you open a note, make a change. Should the search results reflect that change ?  If you are a good typist, you can make a lot of changes, I don't want your typing to be held up by a rewrite of the search results, its slow, especially if you have a lot of notes.

dajoker suggested, I think, that the search results should stay frozen until the user choose to poke at something. I am starting to think the same way even though its a bit inconsistent with Tomboy's model of requiring minimal 'pokes'.
 
**update button** - do you mean refresh ?  I think its a redundant anyway now...

**Search term selected** - I have no idea why that happens, its silly.

**(sorry, you knew that was coming, right?)** - yeah, of course I did ;-

**creation and file name could be hidden** - they are only there because I needed them in the very early days. No need for them now.

 **look as if the notebook filter is still being applied** - yes, agreed and its turning out to be hard.  I see little green arrows in the column heading if you click it, the arrow indicates that the data is sorted according to that column. But I cannot clear/delete/change those arrows so even when I have sorted by lastchangedate (eg when new data has been inserted) we will see a little green arrow above, eg, Name.

Davo

**Comment by aguador** [comment]
> After you do a search, suppose you open a note, make a change. Should the search results reflect that change ? If you are a good typist, you can make a lot of changes, I don't want your typing to be held up by a rewrite of the search results, its slow, especially if you have a lot of notes.
> 
I am not sure I follow. Are you saying that ng indexes AS you are making the changes? I assume only if you do not close the search window? What I would expect if you close the window is that the filters simply clear (or is that part of the difficulty you mention below?). Should you leave the searchform open, perhaps there could be an open note flag to prompt a rewrite of search results only after a changed note has been closed.

Perhaps if needed there could be some sort of warning icon that one or more notes had changed and the search needed to be updated, or the search term changed to red or yellow?
>
> dajoker suggested, I think, that the search results should stay frozen until the user choose to poke at something. I am starting to think the same way even though its a bit inconsistent with Tomboy's model of requiring minimal 'pokes'.
> 
He is a much heavier user than I, so probably a better source. I don't have more than 150 note and most of them quite short. I will admit, however, that last night I was playing with my small machine with SSD. The older machine with traditional HD is noticeably slower.
> 
> **update button** - do you mean refresh ? I think its a redundant anyway now...
> 
Yeah, I was back translating from Spanish where the same term is used.
> 
> **look as if the notebook filter is still being applied** - yes, agreed and its turning out to be hard. I see little green arrows in the column heading if you click it, the arrow indicates that the data is sorted according to that column. But I cannot clear/delete/change those arrows so even when I have sorted by lastchangedate (eg when new data has been inserted) we will see a little green arrow above, eg, Name.
> 
Sounds as if that one is going to get ugly!

**Comment by davidbannon** [comment]
> ...Are you saying that ng indexes AS you are making the changes? I assume only if you do not close the search window? 
Yes, I inform the internal data structure that notes have changed and that change is then sent to the SearchForm. (I do not mean the on disk notes are reread, only the internal data structure).  That beta you have is the first to not update the SearchForm.  Its never closed, just invisible.  

> Perhaps if needed there could be some sort of warning icon that one or more notes had changed and the search needed to be updated, or the search term changed to red or yellow?
Yeah, that the refresh button I guess. It used to reread the on disk notes, that is never necessary now. MacOS won't let me colour a button though ......

Stinking hot here, power has been off since 8:00am, I only have a bit of battery left. Ah, first world problems ....

Davo

**Comment by davidbannon** [comment]
OK, major changes to the search form in this release, lets hope we have these things here covered.

Davo
