### ISSUE TITLE
When to update links in text

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#15]
This is a question how to implement link updates in notes (see also #11).
1. mark a word and click link => it should turn into a link (refer #12) - it does however stay a plain word, until the curser changes text around it
2. delete a note => links to this note in open windows stay intact and open a new note on click => on deletion open windows should be updated to remove the link, or (as it may be disturbing to rerender all notes at once) a note window could get rerendered when focused (this however could lead to confusion, when many notes are arranged next to each other, some showing old links/unlinked text and others something else)
3. assuming that a user has a fast computer, rerendering on any new / deleted note should be no performance issue. However some users have many notes and old hardware. In this case an a global preference `auto_rerendering=off` and a button / context option to manually rerender a note may make sense.

What do you think?

**Comment by davidbannon** [comment]
Bit uncomfortable with all options to be honest.
I think best (of a bad bunch) is 3 -
Provide an setting "_Auto update links in open notes when a note is created, deleted or changes title._"
The, in mainunit, when this happens, iterate over internal list of notes, sending each open note a signal to rerender itself. Thats going to be slow for large or large quantity of notes. And because it involves the GUI, cannot be in a separate thread. However, I now have code that checks links and does not rewrite ones that don't need it. I think.
Hmm, this is not going to happen quickly !

**Comment by traumschule** [comment]
Sure, this is nice to have, but in no way urgent.
I prefer the "auto update" option and if it is disabled a label in each note window with the text "This note needs an update, press F5 or click 'Rerender'".

**Comment by davidbannon** [comment]
We hve had, for some time now, an option in settings that allows us to turn off "show links". With older, slower hardware (eg my 2011 atom powered netbook) normal working with links turned on with a largish note is impossible. Untick the setting and it is usable. There may be a case to have a manual, "update links" menu item under tools but I'll wait and see if anyone is interested.
