### ISSUE TITLE
Background colour after highlight cleared

### ISSUE THREAD

**Issue by davidbannon** [tomboy-notes/tomboy-ng#150]
If text is highlighted and then cleared, it has a white background, not the cream it should be. Wonder what happens in a dark theme ....

**Comment by aguador** [comment]
I DK who would use a light theme :-), but more to the point - what theme has a cream background?

I just played around: Mageia Cauldron (Vertex and Adwiata light and dark, Shades-of-gray-patina) and MX Linux 18 (Blackbird, Greybird, Raleigh and Shades-of-gray-patina), both with -ng 0.26 Gtk:

Dark themes (all): Highlight is grey (making white letters harder to read -- really bad on an 11,6" screen!). Removing the highlighting leaves a faint ghost that disappears when the note is closed and reopened.

Light theme: All light themes tested have white backgrounds, so highlighting then clearing it works perfectly. (I suspect what you were seeing is the ghost effect on an off-white background.)

So the bad news appears to be that you started with one problem -- a sort of ghost left when clearing highlighting -- and now have that plus the ugly highlighting in the dark theme!

**Comment by davidbannon** [comment]
Ah, I was just wondering why I have not heard from you for awhile. I know things are pretty grim in Spain ....

Cream was the initial Tomboy background.  I set one a bit lighter.   So, unless you walk on the dark side, you get cream !

That 'faint ghost' you mention is the same problem this ticket is about. I believe. Anyway, I thought the intention of dark themes was to make them hard to read ? 
  
>"Light theme: All light themes tested have white background..."   

What ?  No, light theme should have a cream background for notes.   Dialogs etc pick up system colours but KMemo has to be set manually and I set it to cream. Does not yours look like the attached ? 
!
[LightTheme](https://user-images.githubusercontent.com/6291248/77705720-81f20480-7014-11ea-847b-652626947739.png)

I suppose I could allow users to choose their own colors ?   You would need to select, at least background, text, highlight background, highlight text, heading.  It would be only for the notes (hmm, I do manually set some string grid colours too now I think of it.)

**Comment by davidbannon** [comment]
> Dark themes (all): Highlight is grey (making white letters harder to read ....

Honestly, I don't understand dark theme !  It looks horrible and gives me a headache, so I am really not in a position to judge.  I just had a look at it in the two dark themes that come with U18.04 Mate and I find it readable. Its a black background with light grey text, the highlight is a mid grey, somewhere between the text and background so it shows up against both.  
I probably have room to make the highlight darker, do you think that would help ?  Or maybe Blue, like the heading used to be ?  I rejected any colours because you dark folk don't seem to like that sort of thing. See attached.
I suspect its a case of different monitors presenting different results
(Gee, that row of buttons across the tomboy-ng note window look terrible in a dark theme don't they ?)
[DarkTheme](https://user-images.githubusercontent.com/6291248/77752882-83571780-707c-11ea-8e77-7d8a56ce49a6.png)

**Comment by aguador** [comment]
OK, I see that there is a pinkish tinge to the background (another set of eyes chose to call it salmon), not purely white or grey on either of my machines. Light background tests: 

- Small laptop (Mageia7): background matches yours AND clearing highlight leaves the white ghost
- Asus laptop (Mageia8): background matches yours BUT clearing highlight leaves no white ghost

System differences:

- Asus is an Optimus sysem with Bumblebee and nouveau driver, but presumably using the 2nd gen Intel integrated graphics by default. No hardware acceleration set (one of those many E settings!)
- Small laptop has only Pentium N4200 Series integrated graphics. Same results with OpenGL and no hardware acceleration (restarting between changes).

Now for the interesting part, discovered by accident:

1. Highlight a string like this "Starting well and Ending badly, Another word", selecting from "Ending" only up *to* the comma
2. Now clear the highlighting (leaves the string selected)
3. Move the cursor a space to the right and hit Ctrl-H or Ctrl-U: " Another word" is now highlighted or underscored (i.e., to the end of the line as happens normally if nothing selected)
4. Move the cursor to the left (clearing or not) and Ctrl-H or Cntrl-U, and now the comma is highlighted or underscored (in other words, even though I am not selecting the comma, it is treated as if I am)
5. Clear the comma and move the cursor some characters to the left, Ctrl-H/Ctrl-U will highlight/underscore *to* the comma (again, treating this as selection even though I am just moving the cursor)
6. Close the note and repeat the first 2 steps, then move to the beginning of the string: Ctrl-H/Ctrl-U will underscore "Starting well and ", that is everything up to what was previously selected/highlighted rather than the previous position of the cursor

You can play with some variations, but the behaviour is consistent:

- If you move the cursor to the right of the formerly highlighted string, Ctrl-H will highlight everything from the cursor to the end of the line
- If you move the cursor to the left inside the formerly highlighted string, Ctrl-H will highlight everything to the right up to the last location of the cursor
- If you move the cursor to the left of the previously selected/highlighted string, Ctrl-H will highlight everything up to the previously selected string (not the previous cursor location)

I guess this means you have three problems now:

- Odd string selection behaviour
- Ghosts of selections past
- Nearly illegible highlighting in dark themes (Why not yellow as I do not want to make it illegible?)

**Comment by aguador** [comment]
I find that the light backgrounds, especially with light themes overall (Adwaita about the worst) blinding.

The white on grey can be read, but is indeed ugly, and intuitively makes me want to skip over the highlighted part rather than read it. I just looked at gnote with its yellow highlighting -- and that really, truly is illegible. OK, there are no other models I can think of, and, frankly I have never used highlighting in notes. If no one else joins in on this, just leave it or darken the grey in the highlight a tad to allow the letters to stand out a wee bit more and forget it unless/until someone raises the issue.

The other issues are more important.

Oops, and on a personal note, please, please, please do not use blue. It is everywhere literally everywhere -- social networks, themes (including E's default) and distros like Mageia and Arch. Besides, colours that are likely to be used in application themes to highlight selections should not be used.

**Comment by davidbannon** [comment]
My little netbook, atom processor, intel graphics shows a note background of grey-ish yellow, no where near the cream I see on my working laptop. Only solution I see is to let those who care (I would) select their own note colours, have that selection override system/default colours.
My first cut at a dark theme did leave the original bright yellow highlight in place but I received a number of complaints so that why I drifted down the "three shades of grey"  model, (if I was to add another 47 shades ....).

I use highlighting quite a lot, but of course its bright yellow for me.  First thing I do on a new system is config the terminal colours. 

I will have to sit down this evening and try and replicate your selecting, moving cursor, lifting left foot of ground and pressing Ctrl-Something recipe.  Far to early in the day to try that.

I have laid to rest the ghost of highlight's past, that was easy.

Davo

**Comment by aguador** [comment]
Glad the hear the ghosts have been laid to rest!

I realized today that I did have another model for dark themes that I use every day: Evolution. For messages, the interface alternates bands of dark and very dark grey to help differentiate messages (the shade being determined by the theme). "Highlighting" is handled in a couple of ways: changing the colour of the letters, using a strong background colour (red), using a pale background colour with black letters.
Those, and the (blue!) icons, are set by Evo itself. The colours for a selection or alternating greys depends on the Gtk theme. Here is a breakdown based on the colour picker in Gimp, plus screenshots.

Note there is one difference with the highlighted messages: the letters are essentially bold which improves readability, although even the regular letters (e.g., Carpeta, Todos) are more legible with the somewhat darker grey than that used for ng highlighting.

ng highlight:              Hex 808080 - CMKY%:  0.0, 0.0, 0.0, 49.8

Tasks (Evo)
- Red (Overdue):	 Hex fe0000 - CMK%:  0.0, 100.0, 100.0, 0.4
- Rosa (Notice):		 Hex fdd4d2 - CMYK%:  0.0, 16.2, 17.0, 0.8 (black letters)
- Pale Blue:	         Hex bdcede - CMK%:  19.9, 7.2, 0.0, 12.9 (black letters)

Adwaita
- Red (Important):	Hex 8c3d38 - CMKY%: 0.0, 56.4, 60.0, 45.1
- Blue (Selection):	        Hex 1a4d8e - CMKY%: 81.7, 45.8, 0.0, 44.3 (also when note open)
- Very dark grey:	        Hex 1b1b1b - CMKY%: 0.0, 0.0, 0.0, 89.4
- Light grey:		Hex 2d2d2d - CMKY%: 0.0, 0.0, 0.0, 82.4

Shades of Grey Patina
- Patina (Selection):      Hex 3f6e5e - CMKY%:  42.7, 0.0, 14.5, 56.9
- Dark grey:                 Hex 3f3f3f - CMKY%:  0.0, 0.0, 0.0, 75.3
- Light grey:		 Hex 433f3e - CMKY%:  0.0, 6.0, 7.5, 73.7
- Selection grey:		 Hex 6b6b6b - CMKY%:  0.0, 0.0, 0.0, 58.0 (when note open, 1st msg - 3rd shot)

I have to admit that Adwaita Dark is a really nice theme (as opposed to its light kin), but I usually use Shades of Gray Patina or Harvest to have less blue!
![Adwaita-dark-2020-03-28](https://user-images.githubusercontent.com/8114758/77822031-4ed07380-70ef-11ea-98ef-34e4dc9a7d70.jpg)
![Shades-of-grey-2020-03-28](https://user-images.githubusercontent.com/8114758/77822183-b63af300-70f0-11ea-957d-ff23b6ded5c5.jpg)
![Shades_of_gray_hi-2020-03-28](https://user-images.githubusercontent.com/8114758/77822199-c8b52c80-70f0-11ea-8980-51981385d53a.png)

**Comment by aguador** [comment]
I could come to like AppImage! It allowed me to download and see how the competition does highlighting without installing.

![Joplin-highligh-2020-03-28](https://user-images.githubusercontent.com/8114758/77829671-d6d07080-7123-11ea-818b-dc87d08c0f9c.png)

The yellow highlight works really well by switching the letters to black. Is this doable without a lot of code?

**Comment by davidbannon** [comment]
Yes, I can change the text colour under highlight. I'd rather not if it can be avoided because it adds one more call out every time changes are made. Not a big penalty but small penalties add up. So, maybe its a last resort ....

Last night I coded up a this dialog, it will let users change the four main colours (could easily add highlight text colour).  If we can solve it this way, that would be nice. As a side benefit, it helps people who's OS does not support (eg) dark themes (Mac, early Windows) .
![Colours](https://user-images.githubusercontent.com/6291248/77835651-e5aa3800-71a2-11ea-83ba-c3ddef776077.png)

So, this is a useful addition even if it does not solve the issue we are talking about. It does, of course complicate the settings interface a bit more. But its just  button, don't press it if you are happy with what you have. And you can revert back to the default with two buttons.

If you are like me or like you (think Enlightenment) and like a complicated interface, well, thats good !

Davo

**Comment by aguador** [comment]
Ah, this is exactly what I wanted to know. I mentioned coding, but often processing (the important part) and coding are separate matters.

I think the colour selection solution is perfect. As good as the changed font colour looks in the screenshot, I doubt the processing cost is worth it.

I do not believe you are unnecessarily complicating the UI. Most users will simply accept the defaults or find something they like better, set it and forget it.

Somewhat off topic, having browsed through other note-taking apps, I think that ng, besides not being cloud independent, offers just the right balance of compactness with features. One cloud-using application has the basic UI with everything else, including the dark theme, being an exension -- for which you must subscribe. Sigh!

The other note-taking fad seems to be offering two panels (as above) showing both markdown and formatted text. Other than a way of learning markdown language, I am not sure why anyone would want this. And, should you want a markdown version of a note, ng has that as an export.

(Aside, your theme is one of those light themes I find exceedingly ugly. When I first switched to Linux I found dark themes strange, but after starting to use them will not go back. [There was a DeLorean theme that offered a grey version that was an acceptable alternative to a truly dark theme, but that was left in the dust by Gtk devs trashing themes regularly.])

**Comment by aguador** [comment]
One further thought, which I may conflict with the colour selection idea: Is it possible to design ng to pick up the application theme? Since you are developing for Win, Mac, and Linux (Gtk & Qt), I suspect this would be a horror, but thought I would ask.

**Comment by davidbannon** [comment]
Lazarus, which tomboy-ng uses, displays the operating system widget set. So, it does pick up what the underlying OS wants us to show.  Unlike Tomboy which uses GTK2 and GTK2+ on every platform.
However, I use a component called KMemo to actually display the note and while it uses the underlying widgets it has its own ideas about colours. So I override. There are a few other components that also don't use OS colours. Windows has only recently introduced the idea of a Dark Theme, all it is at present is a setting, apps are expected to read that setting and act on its advice in any way they see fit.  Newer OSX also 'support' a dark theme but my test machine is one version before that was introduced !
While I use markdown, I'd hate to have to write my notes in it, rather use plain text. Indeed, to update the github (markdown) pages, I write in tomboy-ng and export as markdown !

**Comment by davidbannon** [comment]
Fixed in 0.28, thanks for the report.
