### ISSUE TITLE
Change image pixel value to background default if it's initial value is null

### ISSUE THREAD

**Issue by light42** [tomboy-notes/tomboy-ng#152]
![image](https://user-images.githubusercontent.com/6873314/77848246-a8b76300-71ed-11ea-981b-26db637b9649.png)

Image used is from kubernetes tutorial (https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/).

**Comment by davidbannon** [comment]
I am sorry, I really don't understand what this message is about ?
tomboy-ng does not save images, if you paste an image into a note it is displayed (only because I played a little in that area some time ago and forgot to disable it).
So, if you are suggesting how an image in tomboy-ng can be better displayed, I am afraid you are barking up the wrong tree !

Davo

**Comment by light42** [comment]
Understandable, closing the issue now.
