### ISSUE TITLE
Left/Right button on icon tray

### ISSUE THREAD

**Issue by grosjo** [tomboy-notes/tomboy-ng#157]
Hello

Is it possible to take the good practice from old Tomboy, with left click giving a dropdown list of latest used notes (meaning last accessed, not necesseraily latest created) + create new, and righ button accessing the menu as it is today ?

**Comment by davidbannon** [comment]
No, unfortunately not.  Its all because the definition of what can be in the system tray has changed. The Gnome developers ran a campaign against the System Tray claiming it was causing screen clutter. About five years ago IIRC, Gnome stopped supporting it altogether and they keep making changes that block it.  At the time Ubuntu was developing its ill fated Unity interface and they were a bit more moderate and introduced the AppIndicator, its what most distros use now. It only responds with one menu, in different systems it might be the left or right button ! I have mapped tomboy-ng to respond to either but various desktops get to override that.

Strict Gnome distributions like RedHat Fedora completely block anything that looks like a System Tray, I sure would not use Fedora for that reason alone. There are some distros out there that do still support the tradional System Tray but they are based on old code and are few and far between.

Rather ironically, I can still do the full System Tray thing in Windows or Mac !

Davo

**Comment by grosjo** [comment]
In Cinnamon, provided by most distro, they support great tray icons

**Comment by davidbannon** [comment]
Yep, but most linux users use Gnome3.  Redhat in particular, not surprising given that they are, to some extent, the Gnome Developers !  But even Ubuntu and OpenSUSE, default desktop is Gnome3 !  Between those three, thats probably three quarters of Linux users.
(Not me by the way, I use Mate and it works quite well with the system tray icon too.)
Davo

**Comment by grosjo** [comment]
Then maybe you can do a submenu. 
So Notes are available right away, and settings/etc... goes in a submenu not disturbing ?

**Comment by davidbannon** [comment]
Is that because you believe the menu is too long ?  It has 18 entries, to most recent notes and 8 'system' functions.
Help is already a submenu, if we make the system things a sumbent, we end up with three tiers, maybe thats a bit too complicated ?

**Comment by grosjo** [comment]
From a user perspective, the menu shall be (similar to old Tomboy):

* New note
* Search 
* Submenu to all other fnunction (about, sync, settins, help, quit, ...)
* Recent notes

**Comment by davidbannon** [comment]
I will determine just what it shall be.  Even allowing for the fact that English is not your first language, your statement is rude and offensive.  
The Tomboy main menu changed a number of times during it's life.  I choose to deliver it like it is now. It stays that way.

**Comment by davidbannon** [comment]
Closed
