### ISSUE TITLE
Help users to fix issues in the frontend

### ISSUE THREAD

**Issue by alexanderadam** [tomboy-notes/tomboy-ng#184]
I migrated some notes from tomboy to tomboy-ng and I got this screen:

<div align = "center">

<img src="https://user-images.githubusercontent.com/372620/82024241-c2bedf00-968f-11ea-8797-d4034a8b9d43.png" alt="Sadly, on this OS or because of a Bad Note, I cannot let you dismiss this window - Failed to index one or more notes" title="Sadly, on this OS or because of a Bad Note, I cannot let you dismiss this window - Failed to index one or more notes"/>

</div>

So I guess it would be helpful if the error messages from console could be made visible in the frontend as well (i.e. "`open log`").
Or at least some text like "`Please open an issue at https://github.com/tomboy-notes/tomboy-ng/issues/new`".

For end-users it is not possible to react on this in the way it is now.

**PS:** Just to clarify — this is _not_ about the issue itself (#116) but about the way it is shown to the user.

**Comment by davidbannon** [comment]
Alex, this message happens when tomboy-ng finds a note with bad XML, not at all uncommon for people moving from Tomboy to tomboy-ng. As far as I can tell, Tomboy just ignored bad notes, most users often did not notice there was a missing note and business proceeded as normal.  I am obsessed with keeping this data safe (but still mess up occasionally!) and flag the problem and make sure user cannot ignore it.

So, its not something that users need to log as a bug, its fixable, one way or another within tomboy-ng.  The question might be how clear that is to a new user !

There is a hint, cannot remember exactly, that tells you to open Settings, Snapshots and Recover Lost Notes.  There are some tools there that may allow you to recover some of the missing content.

As the next release will drop the need to keep this window open with particular uncooperative distros, might be a good time to review exactly what is shown.

Good heads up !

Davo

**Comment by davidbannon** [comment]
ps - hover the mouse over that message, 'Failed to Index....' to see that more helpful advice.
D

**Comment by alexanderadam** [comment]
> ps - hover the mouse over that message, 'Failed to Index....' to see that more helpful advice.

Indeed! But this is far away from obvious, isn't it? :wink:

**Comment by davidbannon** [comment]
Because I no longer need to forcibly keep this window open (have a better approach for the hardline Gnome users), I have simplified the little splash screen, and hopefully addressed this issue too.

![badnote](https://user-images.githubusercontent.com/6291248/82718766-e1545400-9ce7-11ea-8c18-9912ed144745.png)

Users can ignore and close the screen now but it will popup on every start.

Davo

**Comment by aguador** [comment]
Looks good, Davo. Now that you have solved the hard (programming) part, one minor and three of super minor comments.

Minor: aren't the "Failed to index ..." and "Bad notes found" lines redundant? Perhaps only one statement of the problem followed by "go to"?

Super minor 1: shouldn't "See" be lower case?

Super minor 2: shouldn't "Welcome to tomboy-ng" be centred the way "tomboy-ng" is in the frame?

Super minor 3: the left-hand margin in the snapshot is a bit ragged with slight differences between "Let's see", the check marks, the checkbox and the last two lines. Proposal: a) left align all the lines of text ("Let's ...", "Don't ..." and "Failed ..."/"Bad ..."). b) For "Don't show ..." you could leave the checkbox further left, aligning the text only if you like so it stands out ore. c) Perhaps indent the checklist itself, again to stand out a bit more. Md insists on "correcting" my alignment, but the general idea is:

     Let's see . . .
          X
          X
          X
          X

 O Don't ...

     Failed . . .

**Comment by davidbannon** [comment]
> Minor: aren't the "Failed to index ..." and "Bad notes found" lines redundant? Perhaps only one statement of the problem followed by "go to"?

Yes, agree. Just remove the "Bad note found" bit I think.

> Super minor 1: shouldn't "See" be lower case?

Yep.

> Super minor 2: shouldn't "Welcome to tomboy-ng" be centred the way "tomboy-ng" is in the frame?

Yes, but I would have to do it in code, I think.  Will expirement.


> Super minor 3: the left-hand margin in the snapshot is a bit ragged with slight differences 

Yes, I agree.  Again, will have a play.

Davo

**Comment by davidbannon** [comment]
OK, because the "Welcome to tomboy-ng" is a translated string, I cannot determine its size at design time.  While I could scale it at run time, its easier to line it up with the other,now, nicely lined up items.
Scaling at runtime would be better I think but a touch risky because of the potential for unicode characters in there.  Generally, I can accurately measure unicode char but sometimes .... 

![Error](https://user-images.githubusercontent.com/6291248/82744287-b5a19e80-9db9-11ea-805c-1912d9008d24.png)

**Comment by aguador** [comment]
OK, very nice. I know these are very little things, but the core is so good it is polishing time.

I thought of the translation problem with centering, but thought it might be possible. This is a good solution.

**Comment by davidbannon** [comment]
yes, quite agree. If @alexanderadam had not brought it up, I would not have looked at that screen. And it was seriously out of date, in particular it no longer needs to be kept open on the hard line Gnome distros.  Maybe the time will come when its not needed at all.....

Thanks for input Adam and aguador.

Davo

**Comment by davidbannon** [comment]
Fixed in v0.29

Thanks for the report.

Davo
