### ISSUE TITLE
Setting "Autostart at logon" does not work on Windows 10 for tomboy-ng 0.28b

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#185]
When trying to click "Autostart at Logon" in tab "Basic" in the settings, I get the error message:

> Error settingautstartCannot find C:\Program
> Files\tomboy-ng\tomboy-ng64.exe

This makes sense because the binary in the ``tomboy-ng`` directory is called ``tomboy-ng.exe`` (no 64).

**Comment by davidbannon** [comment]
Oh, thats my bad mistake.  Because I ship both 32 and 64 bit binaries in the installer, I give them different names. Initially I installed them with those different names but later found it easier to rename them during the install.  It looks like I have not tested auto start on windows since then !
Very quick fix if you want yet another variation of 0.28.   
I do have a few bug fixes lined up right now, 0.29 might be out around early to mid July.
Davo

**Comment by erik-brangs** [comment]
I'm fine with waiting for the new version.

**Comment by davidbannon** [comment]
Fixed in v0.29

Thanks for the report.

Davo
