### ISSUE TITLE
Feature request: easy method for selecting the entire note title

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#186]
Given that most people will want meaningful titles for notes in place of the default time stamp, it would be nice to be able to select the whole default title.

At present if one double clicks on any part of the default title it selects only that part (word, date or unit of time). To replace the entire default title you must use the keyboard or mouse/touchpad to select it.

One possible approach, similar to that used, e.g., in Firefox, would be to enable triple click to select the whole title.

**Comment by davidbannon** [comment]
I think that makes sense but it is a (very) hard one.  Lazarus and LCL do not support a trippil click at all.  Might be possible to add one but would be low level stuff on each platform. 

Otherwise, I could declare a double click in the title as meaning select the whole thing but it would be distinctly non Tomboy behavior and, I suspect more confusing than I would be willing to risk.  We don't have a 'gutter' to click in. Hmm, Shift Click is available in next release, maybe that will help. 

No real better options I am afraid.

Davo

**Comment by aguador** [comment]
OK, it's not that big a deal, more habit on my part. I am used to triple clicking from Basilisk & Firefox, but not every program has it. Just have to remember to place the cursor at the beginning of the name go from there.

**Comment by davidbannon** [comment]
On release of v0.29, we can now do a shift click, maybe that helps ?

With cursor at start of title, shift click at end of title ....

Closing
Thanks
