### ISSUE TITLE
Newly Created Link does not update its font in parent note after cntl L and adding text.

### ISSUE THREAD

**Issue by tomboyuser** [tomboy-notes/tomboy-ng#187]
6-8-2020
platform ; windows 7,
tomboy-ng : version 0.28b
build date 2020/04/20
TargetCPU x86_64 OS Win64

I am seeing an issue where a
Newly Created Link does not update its font (to underline and blue) in parent note after a "cntl L" and then adding text to the new note.
[example.txt](https://github.com/tomboy-notes/tomboy-ng/files/4747496/example.txt)

**Comment by davidbannon** [comment]
hi tomboyuser, welcome aboard !

i just tested this on the current version and am wondering if the problem you are seeing relates to how it is supposed to work.

I take some shortcuts to ensure performance is reasonably fast, especially with people who type a lot faster than I do !  If you don't mind, I would like to spell it out so we can determine just what you would like to happen -

I look for things like links that need to be updated only in the immediate vicinity of where you are editing, if I check the whole note with every keystroke, a big note can get quite slow.

If you have a note with many line of text, and highlight some text (perhaps well back from where you are typing), then press ctrl L, the new window opens, you type into it. At this stage, the first note does not have focus, its not updated at all.  Then you click back on the old note, its still not updated because no recent changes have been made. (Maybe that's the issue ?)  Then you continue typing at the end of the note, again, the link is not updated because you are too far away.  

Now, I could, perhaps scan the whole note when focus returns from a new note, do you think that's what you are seeing ?  If its the special case of just after a Crtl L, a full scan may not be too big a impost. I think ....

Thanks for your help here ....
Davo

**Comment by davidbannon** [comment]
Just a touch more info on this issue. Firstly, its only an issue if you don't make any changes near the "would be link" when you switch back to first note. Secondly, if you make no change to the new note, its not saved and you don't want a link to it anyway.  But there are some  scenarios that don't currently work. 

If you select some text, ctrl L, and then when the new note pops up you type something into the new note and jump back to first note immediately -  no hyperlink is marked and I cannot fix this. Until the note is saved, either because you close it or because auto save is triggered, it officially does not exist !

However, if you type something and close the new note or wait (or keep typing away) for about 10 seconds, the new note gets saved and I can make it so that the link in the old note is so marked.

That may go part way to helping you I hope.  It will be the next release, v0.29, "soon".

Thoughts ?

Davo

**Comment by tomboyuser** [comment]
Thanks David for getting back to me so quickly !
I am so grateful.

I think I understand what you are saying.

I want to go and check the operation of tomboy-ng on my windows7 computer
tomorrow,
and will check linux mint cinamon and windows10 tonight.  I want to make
sure the issue
presentation is the same on all platforms.

I was not aware of the 10 sec maturation function, or the autosave feature.
I was relying on the note closure to ensure a save happened.

So I want to take your replies and go back to my notes to make sure I know
what the issue
presentation is, in light of what i have learned today.

I am using microsoft onedrive to perform the syncing (not for the linux
mint though).
I think I will change to a thumbdrive for the syncing so that I can sync
across all platforms
to check the experience with note updating and linking, and make sure i
can describe any
issue fully.

thank you again, and will send you an email in the next few days, hopefully
I can check
my perceptions in light of the intended functionality you have described.

sincerely,

pat jorden
round rock, tx

**Comment by davidbannon** [comment]
Yeah, there are some OneDrive Linux solutions but they all sound a bit rough.

I have used insync to manage my google drive and I would not be without it.  I paid for it, maybe four years ago ?  Never regretted it. Looks like they have a paid solution.

The thumbdrive will work but its annoying, I use it while travelling. At home, I have a home router with a thumbdrive slot, that does smb, works with everything.  I also have a raspeberry pi setup as a music player, its also has a few gig mounted as smb, I use that for testing.

Easy solution if you have access to a linux server somewhere is sshfs, its so easy !

Davo

**Comment by davidbannon** [comment]
OK, its now a little better in this aspect but -ng cannot show a link before the linked to note is saved.
So, I guess this issue is closed now, on the release of v0.29
Thanks for the report tomboyuser
Davo
