### ISSUE TITLE
Request for documentation update - importing from old Tomboy

### ISSUE THREAD

**Issue by dannaughton** [tomboy-notes/tomboy-ng#194]
I just started with tomboy-ng.  I've used Tomboy forever.  Is there a way to import the tomboy notes - do I just change the settings to the original tomboy location  ~/.local/share/tomboy 

Thanks - looking forward to using this.

**Comment by davidbannon** [comment]
Oh, wow, at last an easy question !
Welcome on board dan.  Tomboy and tomboy-ng have completely compatible formats as long as you don't set tomboy-ng to allowed a note to be in multiple notebooks. No harm will be done even if you do that, its just Tomboy won't believe you.
To get to the notes, you really have three choices -
* In tomboy-ng settings, there is a button on the first tab labelled "set path to note files", using that you can point to your existing Tomboy notes. tomboy-ng will then always look there and always save there.
* Alternatively, first make sure both tomboy and tomboy-ng are stopped, manually copy all your notes across from .local/share/tomboy/ to .local/share/tomboy-ng/. Restart.
* If you are already using Tomboy in some sort of file sync, just point tomboy-ng to that sync location.

Hmm, I guess I should have some import function, don't know how many Tomboy users are still out there .....

Davo

**Comment by netlore** [comment]
I have hundreds of notes from tomboy that I've not been able to use for a long time... I must admit putting off the decision to try porting them elsewhere, try to use gnote, or get all the dependencies for the old tomboy, so I'm happy to see this project, but I'm unsure how to import...  Perhaps you can advise?

In the old tomboy folder, there is a folder structure with many numbered sub-folders. I've pointed tomboy-ng at the old tomboy folder, but when it started up, it said "found 0 notes"... I noticed that if I created notes with tomboy-ng, they appear in the root of the tomboy-ng folder, without any structure... should I collect all the note files from their folder structure, and place them in the tomboy-ng folder?... will any of the notebook structure remain, etc?

**Comment by davidbannon** [comment]
Hi netlore, it sounds to me like you are looking at a file sync repo, not a working repo.  So, rather than setting that dir as a notes location, please try to set it as a sync location.  tomboy-ng will sync with it, pull down the appropriate version of each note and put it in the 'proper' note working dir.  And all good things should happen.

As you have been changing the note working dir, might be a good idea to do a fresh start, remove your tomboy-ng config dir. On linux thats $HOME/.config/tomboy-ng

ps: don't be surprised if you get messages about bad notes, the old Tomboy did not alert you to to a corrupted note, it would just ignore it so, early users do find when they start using tomboy-ng tha it finds all those 'lost' ones and nags you to try to fix them. Your choice.
 
Davo

**Comment by netlore** [comment]
Ahh, you are right.... TBH, it's a long time since I've had this working, so I must have forgotten.  I will say tho, that the sync kinda failed... it said "Found a Note and then lost it... " on about 500 of the notes, but imported ~60 OK.   That said, I remember at some point getting an old version of Tomboy running, and that also failed to sync.  I tried simply copying all the ".note" files to the tomboy-ng folder and that seems to work just fine.... and was able to create a new sync folder and sync them back out... is this an acceptable way to go about it?

**Comment by davidbannon** [comment]
yep, if it got you your notes back, thats all that matters IMHO.

I actually have a (very rough and ready) tool that can dive down through a sync repo finding notes.  Over a long period it does get quite spagetti like and if one of the many manifest files gets broken, things get lost. But if you have managed to navigate that spagatti, all good !

That "found a note and lost it" is an indication that the repo claimed, in its manifest, to have a note somewhere where it did, in fact not have a note.

Anyway, sounds like you are a happy camper, thats great.

Davo

**Comment by netlore** [comment]
Yes, certainly happy... thankyou for reviving this tool, sometimes we just loose really great tools because some aspect of the platform moves on.... I simply did this, from the sync folder.
find ./ -name "*.note" -exec cp {} ~/.local/share/tomboy-ng/ \;

**Comment by davidbannon** [comment]
Closing this, all under control.  Should mention netlore's find command in the docs somewhere ...

Thank !
