### ISSUE TITLE
Search and splash screen uses highlight color as background in Linux dark themes

### ISSUE THREAD

**Issue by aguador** [tomboy-notes/tomboy-ng#214]
This has been tested in Enlightenment (Gtk+2) and MX Linux 18 and 19 (Gtk+2 and Qt).

Light themes work as expected picking up the application theme color (e.g., white, light grey). However, with dark themes the background color is the one defined by the highlight color for the notes (changing after restarts when that color selection has been changed).

Worse,  the alternating "colors" in the search window are alternations between white/light grey on black and white/light grey on white!

![ng-31-dark-splash-12_12-29-09](https://user-images.githubusercontent.com/8114758/102011845-3cfb3300-3d47-11eb-8ed2-227482fd55a5.jpg)
![ng_search_at_start-12-13_13-18-02](https://user-images.githubusercontent.com/8114758/102011846-3d93c980-3d47-11eb-8346-ba772bc295be.jpg)

(Off topic, the font of the first line of the splash screen suggests that it is substituting a font that is not installed on Mageia, but is available on the MX Linux screens.)

**Comment by aguador** [comment]
I suspect and hope that the background color problem is easy to track down. From a dark theme user's perspective, I'm not much enthused by the alternating color scheme in search. Perhaps the easiest (?) thing is to kill the alternation if a dark theme is in use.

**Comment by davidbannon** [comment]
Aguador, I have sent you a private message with a couple of test binaries, few days ago.

In dark mode the alternating colours 'should' be black and dark gray, in your case it obviously did not switch, I don't know why. I tried to reproduce you experience on a Debian Testing but failed. But the background being set to highlight on the splash screen was a typo on my part, a bad one.

If you did not get that direct message from me, can you please let me know, I want to hear your thoughts ...

Davo

**Comment by aguador** [comment]
Tested the versions as soon as I got them, although Qt lacked a library on MX Linux 19 and may not have been completely reliable on my Mageia Cauldron due to an ENV that gets set somewhere.

By changing note background colours, I see that the background in the splash is set to the note background colour. The Gtk version works OK with the themes I use the most on MX Linux and Mageia. Buttons and drop-down/pop-up menus appear to display the theme color. 

Qt, perhaps because of the ENV override issue on Mageia shows the first button with the theme colour, the others with the note background colour, which was a problem when the background was set to black, ditto for the check box. (Should the theme also use black in Gtk, I assume the same issue would arise there.) The drop-down/pop-up menus appear to use the theme colour with not problem.

On both Gtk and Qt the search form, unfortunately, appears as it did before. It also still picks up the highlight colour.

One other curiosity: the Gtk version picked up the Spanish interface, the Qt did not. Go figure!

**Comment by davidbannon** [comment]
Right, think I have it all now. Some quite sad errors made I am afraid. Too distracted by the Debian stuff. Issues, one by one -

To run the qt version, you would have had to manually install libqt5pas1 unless you have used it before.

The QT version shows that Menu button in a different colour because thats zero in tab order. So, if you hit enter, that button will be activated. Pressing tab will step through the various controls.

> the others with the note background colour, which was a problem when the background was set to black...

Yeah, thats why I don't use dark themes. Serious, I see some border around the top half of the button, the button it self, unlike the real background, has a graduated Light Black to to Black that makes it, sort of, visible. I would not use it ....

> On both Gtk and Qt the search form...

Yeah, thats the sad bit. I made a very minor change during testing and did not realised it disabled some initialisation of colours if a dark theme is in use. It was reusing the Light Theme colour for that role. Not happy. Trouble is there are now so many combinations I have to test against. 

I still wonder if I should have made the gray (that I hope you now see) a bit darker ....

> Spanish interface, the Qt did not.

Thats easy. If you were installing from a package manager, the Qt5 binary would have been renamed tomboy-ng but the one I sent you was called tomboy-ng-qt.  And you don't have language files installed for a binary called tomboy-ng-qt.  Had you renamed it tomboy-ng, it would have been OK.

Thanks for you help here, I have attached a pair of new binaries, that will be basis of tomboy-ng v0.31a if you want to have a further look. If happy with them, you could copy (the gtk one assuming you have v0.31 gtk installed)  over top of your existing /bin/tomboy-ng

[Test2.zip](https://github.com/tomboy-notes/tomboy-ng/files/5707248/Test2.zip)

Thanks !
Davo

**Comment by aguador** [comment]
OK, I knew about the Qt library issue -- and should have thought about the renaming!

That said, all seems good. Tested on both MX Linux 19 (XFCE) and Mageia 8 (E), and Gtk follows the theme well. In Mageia the Qt config issue means it defaults to Adwaita Dark, which is OK. However, the line heights in the search form makes it a bit crowded.

As far as the shade of grey: don't go any darker. I just tested with the basic grey of the "Shades of gray" theme, and darker might reduce the contrast too much. Below (reduced by abou 1/3 to save space): 1. ng-Qt Adwaita, 2. ng-Gtk Vertex Maia Dark, 3. ng-Gtk Shades of Gray

![ng-Qt-dark-search-2020-12-17_15](https://user-images.githubusercontent.com/8114758/102504380-0bed6c00-4081-11eb-8c98-f898442bfd9c.jpg)
![ng-Gtk-dark-search-2020-12-17](https://user-images.githubusercontent.com/8114758/102504410-14de3d80-4081-11eb-8749-7714323b0383.jpg)
![ng-Gtk-ShadesGrey_search-2020-12-17](https://user-images.githubusercontent.com/8114758/102504433-1d367880-4081-11eb-9700-95348eb78870.jpg)

I saw your commit. Unless the Qt search form can be made a less clutered (or the screenshot dismissed as my configuration problem), go for it!

**Comment by davidbannon** [comment]
Yes, the Qt search form IS cluttered.  For reasons I don't understand, when I use the LstBox in "owner draw" mode, necessary to get that alternating colour bands, we loose the spacing between rows of text.  I have increased the text size to compensate but I still see it as very ugly.  But its a long term fix, not an immediate one.

Other wise, its all good now. We have a v0.31a out there for Linux, in the PPA and in process, into Debian.  I am yet to test that change on Windows and Mac, may be a useful fix there too but not likely.

Will close .....
