### ISSUE TITLE
Tomdroid sync without sshdroid

### ISSUE THREAD

**Issue by mvglasow** [tomboy-notes/tomboy-ng#215]
It would be nice if Tomdroid sync did not rely on sshdroid (which comes with its own challenges).

As I understand it, sshdroid is just a way to allow tomboy-ng access to the Android file system—there are other options to achieve that. For example, if the Android device is connected through a USB cable, files can be accessed via MTP.
It would be a big step if I could just specify a path in the file system where the Tomdroid folder of the Android device can be accessed. This could be the path where the phone file system is mounted via MTP, or any other option of your choice, possibly even just a local folder that is then synced to the device via some other mechanism (Syncthing or the like). (Granted, syncing comes with its own challenges, but let’s not worry about that now.)

Implementation would be even less complex than the current sshdroid mechanism.

**Comment by davidbannon** [comment]
Ah, mvglasow, on the face of it a very good suggestion. But ..

When I first tried, I did try to use Linux's direct "file system over MTP" to do just that because, like you, I thought that an excellent approach. However, I quickly found just how poor a fit MTP is. In the past, I found it is not practical to mount a directory full of photos for example, the protocol just does not work when thinking of it delivering a file system. I have waited for 20 or 30 minutes to refresh a directory with no more than than a few hundred photos.  I found trying to do a sync just as impossible, not only incredibly slow but prone to crashing and a mid sync crash is not pretty !

I did some reading and found a lot of similar stories, all very critical of the decision to make the Android FS available over MTP as a file system. 

Hmm, but your comments perhaps suggest using MTP directly, not relying on an OS provided FS over top of MTP ?  Maybe that is worth looking into.  I believe some of the desktop/laptop Photo applications work reasonably reliably with MTP devices, I am guessing they use MTP directly ?

Davo

**Comment by mvglasow** [comment]
Yeah, MTP isn’t perfect (for example, running git on a mounted MTP volume just ain’t gonna work). Though here, we are talking about a lot less data—in my use cases, some 80 notes, each around 1K in size.

Plus, what I had in mind is just syncing against a filesystem path. That can be MTP, a mounted network drive (using the protocol of your choice), or a local folder you’re going to sync with Syncthing. You might have to stick to some discipline when using Syncthing in between, but then again, sshdroid isn’t hassle-free either. Being able to sync against a filesystem path would open up a whole host of such opportunities, rather than restricting users to one single technology.

**Comment by davidbannon** [comment]
Oh, I see what you mean. My existing Tomdroid sync work work if it was provided with a (very simple) file transport layer. It would still have to be a one to one sync. And I would need some sort of test setup, despite your thoughts, I don't think an MTP mounted android directory would work, does SyncThing work with Android devices ?

I have several hundred notes in my normal working tomboy-ng repo, but I have many users with thousands.  One solution might be to declare a Notebook, ie Android, and only notes in that Notebook get synced to the android device. In my case, there would be only a limited subset of my notes that need be on the device.  And Tomdroid itself does not know about Notebooks.

Incidentally, don't ever use SyncThing in any sort of direct part of a Tomboy or tomboy-ng sync, it does not know about the Tomboy standard meta data and quite bad things can happen.

Davo

**Comment by aguador** [comment]
>  does SyncThing work with Android devices ?

Not to steal anyone's thunder, but, yes, there is a Syncthing for Android.
> 
> One solution might be to declare a Notebook, ie Android, and only notes in that Notebook get synced to the android device. In my case, there would be only a limited subset of my notes that need be on the device. And Tomdroid itself does not know about Notebooks.

That is actually a feature request I have thought about. I have some notes that only need to be on one machine, but others that would be nice to share across devices. Android devices add another layer as one does not want to overload those systems with extensive notes.

BTW would that be a notebook, which is essentially a label, or a seperate database, say one set for a single workstation, one to be shared with other work stations, one for mobile devices, and one, perhaps, for all. (Yeah, this is significant, perhaps impossible work, but I thought I would throw out the idea. If too over the top it can die here, otherwise it can be moved to a new thread.)
> 
mvglasow is obviously more knowledgeable about the inner workings than I, but syncing via a direct cable connection makes syncing a lot more attractive. It might also motivate someone to maintain and update Tomdroid, which is really a quite nice note app.

**Comment by davidbannon** [comment]
OK, I just managed to get SyncThing to replicate a dir full of notes onto my laptop. It did it fast and painlessly once setup but I found the setup quite slow !  Syncthing on Android requires a QR reader to connect to (eg) a laptop. A specific QR Reader that incidentally has a serious problem with very invasive full screen ads even when it is not running.

The other problem with SyncThing is it seems to reserve the right decide when to sync, it does not have a mode of "sync when I tell you" and thats a real problem !

To use it with Tomdroid the process is something like this - 

1. In Tomdroid, do a file sync to 'export' the current notes.  I suspect Tomdroid keeps it's notes in a database, if we could get to that, things would be a lot simpler !
2. Then start SyncThing to make a copy of that dir on your PC.
3. Then, in tomboy-ng, run the as yet unbuilt one-to-one sync unit aimed at that directory we created in step 2.
4. Now, again run syncthing to scoot the changes back to android device.
5. Restart tomdroid and do another file sync to move those changes back into its internal database.

Its pretty much the same process at existing tomdroid sync, its just that we have replaced ssh with syncthing.  And, from above, you can see that timing of each step is critical.  We cannot risk syncthing jumping in too early and we cannot handle it running as soon as we are actually ready to go. 

Would be a simpler process if we relied on a mounted file system providing access to that content created in step 2. But that means MTP...
Or better still, get our hands on the Tomdroid database file, its probably sqlite, but android is getting quite awkard about such asccess.

Thoughts ?

Davo

**Comment by mvglasow** [comment]
Side note, I have Syncthing set up between my Ubuntu laptop and Android device and been using it with no issues for quite a while. When running, it periodically scans for changes and transfers them as soon as the other end is listening. While it does a great job at letting peers discover each other (even when you are not on your home network), it is just a dumb file sync tool. Above all, when changes are detected on both ends, it cannot merge them or even show a diff: the user needs to choose one version to keep (or maybe keep both, renaming one version)—it does take a bit of user discipline to prevent that situation.

**But that’s not the point.**

My point is: I would really like to be able to sync against a random folder in the file system. Just assume the folder is there (the path may vary), and everything dropped into that folder magically appears on the Android device (and vice versa). Assume the process in itself is transparent and don’t worry about how this works—the ways to achieve this are too numerous to mention already, and possibly increasing as I write these lines. Basically, I am talking about a layered architecture, rather than a monolith dependent on one specific technology.

**Comment by davidbannon** [comment]
OK mvglasow, I do have bit of a working system.  After your prodding, I went back to the code I wrote a year or so ago trying to make Tomdroid sync over a mount mtp: directory.  At the time, as I remembered eventually, the issue was that you cannot create a file on that directory using the mount point, only using a File Manager.  So, eventually I found that there is a utility, gio, that lets you do some of the file i/o you cannot otherwise do (on the mount point).  Its not as cool as calling gvfs library calls directly, that may come in the future if this model looks viable.

So, now I have a system that does work over a USB cable. Needs no ssh, password or profiles, heaps easier. You still need to follow the process -
* On Tomdroid, touch sync. Exit Tomdroid.
* Connect the USB cable, tell android to permit access to file system.
* Run the sync from tomboy-ng
* Restart Tomdroid and run sync again.

So far, under my tests, seems quite reliable. It does depend on gvfs/gio packages being loaded, there were already on my system, are generally preinstalled but not, apparently on Debian bullseye ??? I don't have the capability to test on a range of platforms unfortunatly.

**So, testing**

Do you want to try out a test version ?  You should make a tomboy-ng snapshot first !

**sync against a random folder in the file system**
Thats an interesting one. Any sync system relies on keeping some meta data between syncs, if it does not, its just a 'merge' not a sync. A true sync can keep track of notes that were previously synced and then deleted, it must ensure they are then deleted at both ends.  A merge will risk restoring deleted files every time its used unless the file has been deleted at both ends. 

A merge is dead easy, in practice tomboy-ng does a merge when creating an initial sync. It looks for notes that may have started out as the same one, determines if they are different, if so, shows you the difference, lets you decide.  If a note exists at one end but not the other, it just makes sure both end have that note.  But a note could exist at one end but not the other because it was deleted at one end, you don't want it restored then !    

Tomboy notes have internal meta data that makes doing that sort of thing much better that, eg, SyncThing that can only use standard file metadata.  

Merge with a random folder is possible, even easy. Sync is not.

Please let me know if you want a (risky) test version.

Davo

**Comment by mvglasow** [comment]
Thanks a lot! That is really great news, and I am definitely interested. How can I get my hands on a test version?

As for the packages, I am running Ubuntu 20.04 and using gvfs. As far as I can tell by looking at the Ubuntu package repository, gio is part of glibc2.0-0, and I have the `gio` and `gio-querymodules` on my path, so that looks OK as far as I can tell.

BTW, by “random folder” I just meant that one can designate any file system path as the location at which the files of the other end will always be found—**not** that the path can change from one sync to the next. Thus, if you somehow manage to mount your Android device on your PC, just point the sync to the mount point, without worrying how the files got to appear there in the first place.

**Comment by davidbannon** [comment]
I have uploaded to the main Release page (not the Wiki Release Page) a 64 and 32bit GTK and a 64Qt5 version called 0.31b.  They are full install kits and come with an updated Tomdroid help note.

'Out of the box' they will look for a Tomdroid sync dir in the place where I believe it should pop up, /run/user/$USERID/phone/tomdroid and that requires gvfs and gio to be installed. Its also possible to redefine the location of that dir and call it a general purpose One to One sync using an env set to the dir you want to sync to.  In either case, its behaviour is the same, it will suggest a Join if you have not been there before and a Sync if you have initialised that dir with a previous Join. Details in the Tomdroid help note but something like -

$ TB_ONETOONE=/home/mydir/MyOneSync  tomboy-ng

Please make sure you have a snapshot of your notes before installing.

Your comments very welcome !

Davo

**Comment by aguador** [comment]
Just gave this a shot on an up-to-date MX Linux (Debian Buster) system. Installed via gdebi which confirmed dependencies were installed (in addition I manually confirmed that gvfs with gio module is present). The first time I tried I got an error message that said that ng could not see _Android_Android_ba0da805/Almacenamiento interno/tomdroid/_ on the phone. However, Thunar and Double Commander both see it. Subsequent attempts bring up the sync screen where ng simply says that it cannot find a Tomdroid sync directory on the device.

Note two things. First, that the name of the directory sought, even allowing for the Spanish strings, is not the same as that given in your help note. Yet, second, despite that, ng is apparently looking for the right directory -- which both exists and has notes.

**Comment by davidbannon** [comment]
Disappointing but not particularly surprising.  But I am surprised about the names we are seeing.

Please run it in debug mode, right at the start you will see something like below : 
```
tomboy-ng --debug-sync <enter>

....
TAndFileSync.CheckRemoteDir RemoteDir = /run/user/1000/gvfs/mtp:host=%5Busb%3A001%2C058%5D/Phone/tomdroid/
TAndFileSync.CheckRemoteDir MTPDir = mtp://%5Busb%3A001%2C058%5D/Phone/tomdroid/
....
```
If I see your result, it will help me understand just how gvfs works, its really quite undocumented. Right now I am guessing, I cannot do my usual trick of building a VM because the VM does different things when its told to mount the host usb connection.

Then, from the command line, please try to 

`ls /run/user/1000/gvfs `
   
(your UID may not be 1000, but its probably the only entry at that level, so use whta is there)
And can you please translate "Almacenamiento interno" for me ?

I have assumed, perhaps incorrectly, that linux structural things like "run", "user" etc in /run/user/1000/gvfs/ would not need translating.  At the other end, in my case, gvfs mounts the filesystem on a dir called "phone" and we tell users to call the next directory "tomdroid".   But maybe different phones offer a different mount point name ?  

Hmm, I think I read somewhere that Android has two possible filesystems it offers, mtp: and another photo specific one ???

Sort of knew this could not possibly be as easy as I first thought ....

Davo

**Comment by davidbannon** [comment]
Yeah, so firstly, 'phone' was a bad assumption.  My Tablet says 'table', my older phone, a sony xpedia says "Internal Storage" - sounds a bit like what aguador saw (but, obviously in Spanish).

So, I cannot use that keyword 'phone' to indicate I am in the right place. Perhaps I use whatever I find there iff there is only a single entry. I would still insist on finding a dir beyond that called "tomdroid".   Fail if there is more than one directory below the mtp:~ bit (perhaps because of an extra SDCard ?)  and fail if there is not a directory below called tomdroid.  I guess I could run if I find 

`/run/user/1000/gvfs/mtp:*/*/tomdroid  ` 

Thats a bit guessy and I don't like pocking around in an end user's phone with wild cards but ....

Davo

**Comment by aguador** [comment]
```
$ tomboy-ng --debug-sync
TAndFileSync.CheckRemoteDir RemoteDir = /run/user/1000/gvfs/
TAndFileSync.CheckRemoteDir MTPDir = 
TAndFileSync.CheckRemoteDir ServerID = 
Remote address is (n.a. Tomdroid) /run/user/1000/gvfs/
Local Config /home/aguador/.config/tomboy-ng/android/
Notes dir /home/aguador/.local/share/tomboy-ng/
```

`ls /run/user/1000/gvfs` - no output (from file manager confirmed that dir is empty with "Android" mounted)

Almacenamiento interno = Internal storage

**Comment by davidbannon** [comment]
OK, so you are not seeing anything in /run/user/100/gvfs ?  That I can understand. I suspect I have an answer for that.  But then, where did it get the "Almacenamiento interno" from if not from an mtp: mount ???  That is a mystery.  I am currently making a version that is a lot smarter about building that mount dir, all will be revealed.

Please see if you have gvfs-fuse installed and install if not.  I have found it there on Ubuntu machines but not, eg, Bullseye.  Its needed for you to be able to see those mount points from the command line. I need to see them (in tomboy-ng) so I can derive the gio mount point.  (this process needs to get better ...)

Davo

**Comment by aguador** [comment]
Yep, gvfs-fuse present and accounted for in MX Linux/Debian 10.x.

It is also in Debian 11: https://packages.debian.org/testing/source/gvfs

Reveal soon! I'm holding my breath!!! :-)

**Comment by davidbannon** [comment]
But pre installed ? That is, is it installed on the machine you are using ?

(I found it was not pre installed on my D11 and when it was not there, the mount points we are talking about, did not appear.  I installed it, and all was well.)

Davo

**Comment by davidbannon** [comment]
Hmm, I am seeing caching issues. Seems to be a particular problem with an older android phone I just tested but I can, at random time, demonstrate it on my current phone.  Whats happening is the file system (on the phone) is caching writes, you remove a note during a sync, the (gvfs) file system is unaware its been deleted until you try and read it. I have a few ideas how this might be fixed (using gio calls) but its not going to happen tonight.
Tomorrow is reserved for me to watch Australia defeat India in the third test so I may get a bit done then ...

Davo

**Comment by mvglasow** [comment]
Unfortunately I haven’t yet found the time to try this out myself, will report back as soon as I get to it.

As for the path, however, I guess it is better to have the user select it rather than trying to guess it—MTP mount paths have varied even across versions of the same distribution. With Ubuntu 18.04–20.04, MTP mounts are found underneath `/run/user/$UID/gvfs`, where `$UID` is the numeric user ID.

With older versions of the MTP library, the folder name was composes of two numbers, increased for each new device plugged in, and reset at reboot—meaning your device would pop up at a new path every time you unplugged it and plugged it back in (great fun if your USB cable has a bad contact). A while back I proposed (and started working on) a change to introduce stable identifiers; someone else eventually took over and introduced that into the stable release. For folks sticking with Ubuntu LTS, 18.04 still had the unstable identifiers, 20.04 has stable ones. Folder names are now something like `mtp:host=Acme_X2001_ea7d09f00d`, i.e. composed of manufacturer, model and hexadecimal device ID.

So, if you are on an older version of the MTP library, you are out of luck—unless you create a symlink to the mount location of your phone , keep the name stable ad update it each time you plug in your phone (not sure if that actually works), or update to a more recent version (again, might not work because of dependencies).

**Comment by aguador** [comment]
> But pre installed ? That is, is it installed on the machine you are using ?
> 
Yes, it was installed at the time I did he tests. The phone is running Android 6.0.1.

**Comment by davidbannon** [comment]
Hmm, 6.0.1 ? I am testing here on a 5.1.1 and thats the one with nasty caching issues. Issues I think I can solve by not using the mountpoint for file i/o, using gio instead. Needs to be proven.

There is a gio command that lists all the mounts it knows about, please try -

`gio mount -l `

(thats a lower case L for list) and look for a line that mentions mtp:   If that is not there, you don't have a mtp connection. If you can still see files (on the device) in your file manager, then its a fair indication you are connecting is some other way.  The dmesg command might show us something, type dmesg  <enter> just after you have plugged the phone in and authorised it.

There may be other things required in that chain between gvfs and gvfs-fuse, have you ever tried to connect to, eg, a smb (ie Samba or Windows share) ?  It uses the same tools.  If you sync tomboy-ng to some windows share, I used to use one built into my home router for example, you would be doing pretty much the same thing.

Davo

**Comment by davidbannon** [comment]
> Unfortunately I haven’t yet found the time to try this out myself, will report back as soon as I get to it.

Just wait a bit, I am still working on some things. May post something tonight ....

 
> As for the path, however, I guess it is better to have the user select it rather than trying to guess it—MTP mount paths have varied even across versions of the same distribution. With Ubuntu 18.04–20.04, MTP mounts are found underneath `/run/user/$UID/gvfs`, where `$UID` is the numeric user ID.

Yes, I found that.  My code now allows for either model but must be down in /run/user/$UID/gvfs and must start with 'mtp:'.  So, I can cope with the changing mount point and the varying top level device directory (it does not need to be in English). But in both the above cases, only one of each is allowed, if you have two mpt devices plugged in, fail.

I need to assume /run/user/$UID/gvfs because very few users will have every heard of this location so no use asking them to specify it. And I may be able to abandon even that and do it all through gio but I have not proven that yet.


> With older versions of the MTP library, the folder name was composes of two numbers, increased for each new device plugged in, and reset at reboot—meaning your device would pop up at a new path every time you unplugged it and plugged it back in (great fun if your USB cable has a bad contact). 

Thats OK, I can handle it.  But not the bad cable !

> So, if you are on an older version of the MTP library, you are out of luck—unless you create a symlink

No way would I depend on that, mpt is a file system in name only, you can not depend on any of the file i/o calls we expect to work. I do almost all of it now with gio calls.  Makes for  lot more complicated code than I expected but its now just starting to look a bit stable. A bit ...

I am testing with  two Android phones, 8.0.0 and 5.0.1, will also try against my Tablet.

But because the difficulties in getting USB working on Virtual Box (ie the Extensions) I can only test it on my U18.04 box.  So I will need some help ...

Stay Tuned....

Davo

**Comment by aguador** [comment]
OK, here is more information. BTW the phone mounts right away. Just has not to be locked.

```
$ gio mount -l
Drive(0): KINGSTON SA400S37480G
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
  Volume(0): Volumen de 379 GB
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
  Volume(1): Volumen de 537 MB
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
  Volume(2): Volumen de 21 GB
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
  Volume(3): Volumen de 537 MB
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
Volume(0): Android
  Type: GProxyVolume (GProxyVolumeMonitorMTP)

```
```
$ dmesg
...
[  411.097415] usb 1-1: new high-speed USB device number 5 using xhci_hcd
[  411.246306] usb 1-1: New USB device found, idVendor=19d2, idProduct=0306, bcdDevice= 3.10
[  411.246312] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  411.246315] usb 1-1: Product: Android
[  411.246316] usb 1-1: Manufacturer: Android
[  411.246318] usb 1-1: SerialNumber: XXXXX
```

I don't sync between any of my machines, so do not know what to say regarding Samba, except that it is installed on this machine.
```

**Comment by davidbannon** [comment]
Android 5 and 6 mount without asking, 7 and 8 need permission.

But I am really worried about just where your system is mounting it, or, if it is mounting it as we know the term at all.  On my bullseye, it does what is expected, (while I cannot make a USB mount, smb works the same) 

```
gio mount -l <enter>
....
Mount(2): store2 on greybox -> smb://greybox/store2/
   Type: GDaemonMount
....
```
I can then use that "smb://greybox/store2/" as a location in another gio command.  I can only assume that MX Linux has  decided to do something different. We may need to find out why your 'mount' is of type  GProxyVolume  and mine is of type GDaemonMount.  Hmm, gio mount will take an -i so, please plug your phone in and type -

`gio mount -li   <enter>`



.. and when you hover a mouse over your GUI file manager, specifically where it shows the Android Phone mounted, do you see a hint popup with some label, mpt://something ?                     

Davo

**Comment by aguador** [comment]
```
$ gio mount -li
Volume(0): Android
  Type: GProxyVolume (GProxyVolumeMonitorMTP)
  ids:
   unix-device: '/dev/bus/usb/001/005'
  activation_root=mtp://Android_Android_ba0da805/
  themed icons:  [phone]
  symbolic themed icons:  [phone-symbolic]  [phone]
  can_mount=1
  can_eject=0
  should_automount=1
```

Hovring in Thunar shows nothing (actually first showing it not yet mounted, after mount, nothing). Repeating with Double Commander, nothing on the hover, but switching to Adroid in a pane shows the mtp://Android_Android_ba0da805/ seen above.

**Comment by davidbannon** [comment]
OK aguador, that does, to some extent, make sense given the paths we saw in your first post to this thread.  It says the gio 'location' (their term, not mine) for your phone is - mtp://Android_Android_ba0da805/

So, the next test would be you try and use that 'location' -

`gio list mtp://Android_Android_ba0da805/`

My guess is that may show you the top level directory of your phone. Perhaps thats Spanish for "Internal Storage" ?  If it has a space (boo, hiss!) you will need to wrap it up in inverted commas for the next step, ie -

`gio list mtp://Android_Android_ba0da805/"Internal Storage"/`

If that works, it should show you the directories that appear in your Android FS, things like Android, Photos, tomdroid  (the latter only if you have created it in Tomdroid). You can list the files in tomdroid the same way, note we have not referenced the /run/user/1000/gvfs/mtp: mountpoint in getting to here ....

What I do not understand is why its displayed in a totally different way than I would expect following my survey of some distributions but mounting a smb: share rather than a mtp: one.  I believe its a valid test because gio uses the same syntax for all the shares it manages, I think. My test command, after mounting that smb: share, is 

`gio mount -li | grep store2`

I have tested Ubuntu 18.04, v 2.56.4; Ubuntu 20.04, gio v2.64.3; Debian Bullseye, gio v2.663; Fedora 33, gio v2.66.3; MX Linux 192, gio v2.58.2 and in every case got an identical response with my smb: share mounted -

```
Mount(0): store2 on greybox -> smb://greybox/store2/
  default_location=smb://greybox/store2/
```
That looks like something we can work with iff it translates to mtp: and we can at least understand why it does not work for aguador.

Both Mageia 7.2 and SuseLeap in KDE guise seemed to have viable gio versions but I could not mount my smb: share, sorry, I have got to used things like that just working out of the box to be willing to struggle with it for now.  And maybe the smb: is not a viable test.  I am starting to think that I will have to build real OSs to test, ones I can use the USB socket on, not relying on VMs. Thats not going to be fun.

Davo

**Comment by davidbannon** [comment]
Too hot here to do anything outside. So,  I made a bootable USB drive with MXLinux 19.3 on it (looks pretty good except for the dreary grey colours) and ran some tests. 2.58.3

And found a few things -
1. Yep, it has its (gio) locations in a different format as mentioned above by mvglasow, heaps better too, they don't change with every new connection.  My two phones were mtp://SAMSUNG_SAMSUNG_Android_52004dfb47a785e5/ and mtp://Sony_C6903_BH90BT9N13/
2. Apart from the actual 'location' being a bit different, the output of 'gio mount -li' was the same as the others, I don't see any problem in using that data.
3. I did notice that MXLinux seemed to need a slightly different process when connecting a phone or whatever. My Ubuntu18.04 triggers a permission dialog on the phones as soon as its plugged in. On MX, on initial connection, an entry for the Phone appears under Devices in MX's File Manager but nothing happens and if you just wait the phone goes back to sleep and you have lost your chance. The secret seems to be that you must click on the new entry as soon as it appears, then and only then do you get a permission dialog on the phone. In earlier phones, the dialog is skipped but you still must click on that new File Manager entry. And must do it before the phone goes back to sleep.

I can confirm that once that connection is established, you can use that location to poke around with gio, in my case, where the Phone's top directory is 'Phone' I can 

`gio list mtp://SAMSUNG_SAMSUNG_Android_52004dfb47a785e5/Phone/tomdroid/`

And see a list of notes for tomdroid sync use.

Too bad that most of the current systems I tested use the old format, it would be good to use that ID in my config files to ensure we are talking to the right sync repo. But that aside, I am convinced that I can now do a tomdroid sync without using that dodgy gvfs mount point.

I will push out a tomboy-ng v0.31c shortly, it will still have the hybrid mountpoint/gio transport model but its a reasonable proof of concept right now I believe.  

Two things (plus any bugs!) are still needed -
1. Its not completely safe to use more than one Android device, if you do, a note deleted by one device can be resurrected by the other device.
2. Drop the hybrid model, all gio, will remove dependency on gfvs-fuse and probably make it future and past safer.

Davo

**Comment by davidbannon** [comment]
Ah, one more thing aguador !

Can you please connect your (Spanish speaking) phone to your (Spanish speaking) PC and after making that connection, type :

`gio mount -l  | grep mtp:`

and then copy the url like thing (which we will call LOCATION) and type :

`gio info LOCATIONAndroid <enter>`

That is, append 'Android' to your long winded location as revealed by the first one. Can I see the 10 or 15 lines it will produce please ?

It has just occurred to me that if the keywords that gio spits out have been translated to spanish, I will have problems getting my model to work with any language we have not translated. And our translation will have to be exact ...

Davo

**Comment by aguador** [comment]
OK, there is some sort of trick, but I don't clearly understand what MX is doing. I recall in Thunar yesterday Android appeared, but I had to right click to mount the phone. Something similar happened just now. It appeared in Double Commander, but until I clicked to open the Android location in a pane, it was apparently not mounted. After mounting:
```
$ gio list mtp://Android_Android_ba0da805/
Tarjeta SD
Almacenamiento interno
```
The the following does indeed work:
```
$ gio list mtp://Android_Android_ba0da805/"Almacenamiento interno"/
Android
.
.
.
tomdroid
.clipboard
Telegram
```
```
$ gio mount -l | grep mtp:
  Mount(0): Android -> mtp://Android_Android_ba0da805/
Mount(1): mtp -> mtp://Android_Android_ba0da805/
```
In the last command, appending "Android" does not work (saying the folder does not exist), but it's OK without it:
```
$ gio info mtp://Android_Android_ba0da805/
nombre que mostrar: Android
nombre: Android_Android_ba0da805
tipo: directory
tamaño:  0
URI: mtp://Android_Android_ba0da805/
atributos:
  standard::type: 2
  standard::name: Android_Android_ba0da805
  standard::display-name: Android
  standard::icon: phone, phone-symbolic
  standard::content-type: inode/directory
  standard::size: 0
  standard::symbolic-icon: phone-symbolic, phone
  id::filesystem: mtp:host=Android_Android_ba0da805
  access::can-read: TRUE
  access::can-write: FALSE
  access::can-execute: TRUE
  access::can-delete: FALSE
  access::can-trash: FALSE
  access::can-rename: FALSE
  filesystem::size: 36184547328
  filesystem::free: 27994918912
  filesystem::type: mtpfs
  filesystem::remote: FALSE
```
And the business of translation? The user will have to indicate the interface language of the mtp device, I suppose a user might have different devices with different languages. Sounds complicated.

**Comment by davidbannon** [comment]
> ... but until I clicked to open the Android location in a pane, it was apparently not mounted., 

thats the impression I was getting. Potentially very confusing.


> ```
> $ gio list mtp://Android_Android_ba0da805/
> Tarjeta SD
> Almacenamiento interno
> ```

Oh, thats unexpected. Two entries at that level ?    You must have a removable SD card in there too. I will have to allow for that. Sigh...


> In the last command, appending "Android" does not work (saying the folder does not exist), but it's OK without it:

Thats because I gave you the wrong command. It should have included either the "Tarjeta SD" or "Almacenamiento interno" in there. Because you output is so different to mine, and to be absolutly sure, can I please ask you to try again -

`gio list mtp://Android_Android_ba0da805/"Almacenamiento interno"/tomdroid <enter>`

But you have shown me most what I needed to know.  Firstly, that the top level directory name may well be LOTE (Language Other Than English)  and, importantly, so is the key data in the output of "gio info", but the data itself is English.  That means I either have to have a language look up table or (risky) rely on its position in the output. For example, the third line is "tipo: directory". Right now, my code says if the last word in line 3 is "directory" its a directory. Fragile but maybe all I can do ?

> 
> ```
> $ gio info mtp://Android_Android_ba0da805/
> nombre que mostrar: Android
> nombre: Android_Android_ba0da805
> tipo: directory
> tamaño:  0

While useful, thats the "Location" rather than a directory within your phone. The command I suggested above will show me more, and possibly different information.

> And the business of translation? The user will have to indicate the interface language of the mtp device, I suppose a user might have different devices with different languages. Sounds complicated.

Yes, if I can be convinced it works, I would much prefer to ignore language.  As I said above, while the key (ie "tipo") is in Spanish, the data ("directory") is not. Maybe I can make it work ?

All very interesting.  Thanks for you help, it would not be possible to do anything without you different perspective.

Davo

**Comment by davidbannon** [comment]
OK, I have uploaded the 0.31c I promised. Its a pure gio driven model so that should relax some of the constraints. It can handle more than one top level directory in the Device and does not rely on the gio output being in English. But as noted before, its very, very untested.

Extract from my changelog as 'release notes' :

    2020/01/13 Ready for testing, aware of three issues -
        1. An error in older version of Android MTP, a deleted note can appear to remain
           in the sync dir but be unreadable until phone is rebooted. Msg appears std out.
           Seen often in Android 5.1.1, not at all in 8.0.0
        2. When a note is deleted on one Android device, it will be restored by another.
           I need to add an entry in each current Android Local Manifest noting that it
           is a deleted file.
        3. All this and related code does not work in Windows but its it is exposed to
           the compiler. Some ifdef's are in order here ...

**Comment by aguador** [comment]
As expected:
```
$ gio list mtp://Android_Android_ba0da805/"Almacenamiento interno"/tomdroid
4e8ee92c-fbce-49a5-bebc-f7de779b3f2f.note
e7430a18-4673-4eac-ab24-302ecb20b241.note
792c1822-8c1c-4dd7-bde0-634bf94401e9.note
07e57a7f-d45f-4156-9281-ebf50183a241.note
6bba38cf-7df9-429e-b289-0d0231243c26.note
dee0da49-9bfb-4361-85b7-fdb8c4236d92.note
```
Testing of 0.31c yielded a sort of 1/4-1/3 sync:

- ng asked me to join the sync
- synced after joining and files from phone transferred to computer, Tomdroid shows no notes received. Hmmm
- edited a note on the phone
- sync did not detect the changed note. Hmm - cache issue?
- stopped tomdroid on the phone, restarted, it synced - no change detected
- rebooted the phone, synced -- no change detected
- edited an ng note on the computer
- synced - ng showed one note changed, left pane of ng sync window showed which note, said it was uploaded - Tomdroid does not show changed note
- edited a Tomdroid note with ng
- synced - ng showed one note changed, left pane of ng sync window showed which note, said it was uploaded - Tomdroid does not show changed note
- poke around with the FM on the phone: there ARE 13 notes in the directory, but Tomdroid only shows the six that were written on the phone -- and without changes made with ng
- repeated editing a Tomdroid note and ran debug (see log attached):
[ng-debug-sync.log](https://github.com/tomboy-notes/tomboy-ng/files/5811670/ng-debug-sync.log)

Two other observations on transfers from Tomdroid:

- Character codes must be different between Tdroid and ng as ASCII code shown for é
- Notes received from Tomdroid open by default in a really small window -- readable but small

**Comment by aguador** [comment]
OK, I'm a jerk. I forgot about that sync button on Tomdorid. (You can give a user a help file, but you can't make him read it!) When I pressed that all changes showed up -- on both sides of the equation. So overall quite a success. :+1: 

On the ng sync window it would be nice to label the panes in some way. Once a sync has been successful, it becomes obvious, but it would still be nice to show something like "Changed note list" and "Sync log" (or something similar).

**Comment by davidbannon** [comment]
Ah, OK, abandoning partly written message. That [ edit - sync- close Tomdroid - connect USB - run -ng sync - disconnect - restart Tomdroid - sync ] cycle is not going to get any shorter I am afraid, its a must.

 I agree about keeping user informed, I would also like to have some progress indicator, you know, "reading remote files", reading Local file", "uploading 10 notes", "downloading 6 notes", "killing your cat" .....

But you did get a sync then ?  Great !  Thats the two things I cannot test here, Spanish and two items in the Phone's top level directory.  

 
>    Character codes must be different between Tomdroid and ng as ASCII code shown for é

Thats a worry, 'something' in that quite long chain is not handling unicode ?  

>    Notes received from Tomdroid open by default in a really small window -- readable but small

Strange, I have not noticed that one.

Further research is needed ...

And you are up very late !

Davo

**Comment by aguador** [comment]
It was late, and too tired tothink about a screen capture of a Tomdroid notes for size and "é":
![Tomdroid_sync_note](https://user-images.githubusercontent.com/8114758/104553826-981c9000-563b-11eb-8125-0a501d91e887.png)

**Comment by davidbannon** [comment]
OK, the UTF8 issue is the big one, as near as I can tell -
* Tomdroid rewrites any UTF8 characters it find in the Text of a message with an HTML Entity, eg, `&#911;` and thats what it send back to us. 
* Tomdroid totally goes crazy if it encounters a UTF8 character in the Title, the xml is trashed, an extra copy of the title is added and its unreadable back in tomboy-ng. Strangly, it remains readable in Tomdroid so I suspect that the mess up happens during the "Tomdroid sync to the syn dir" operation.

So, this means that I will have to escape any unicode character I find in a note during "tomboy-ng sync to sync dir" stage, then reverse that during the "Sync Dir to tomboy-ng"  stage. Going to be an issue ....

Davo

**Comment by davidbannon** [comment]
OK, I have put version 0.31d debs up there, notes edited in Tomdroid now display extended characters as they should, a couple of other tidy ups.  I will stop now for a bit until I can merge it back to the master stream, a few things still needed but I think right now as a proof of concept its ready to test.

If anyone wants packages other than debs, please let me know.  Note that at this stage, the Tomdroid interface is Linux only.  Potentially extendable to Windows.  I assume Mac use would not be interested....

Davo

**Comment by davidbannon** [comment]
Pre-release version now available that addressed this issue. Please see https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.31
If you do use it, please watch for anything unexpected and please report what you find, good or bad.

**Comment by aguador** [comment]
Just tested sync with 0.31f and the extended characters are OK. Notes produced on the phone still show in that tiny size when opened on the desktop, not critical but could be annoying for those who rely on syncing with Tomdroid.

**Comment by davidbannon** [comment]
This is done as long as you are a Linux users.
Thanks for the report, it is a very worthwhile improvement.
Davo
