### ISSUE TITLE
Tomboy tray icon pulldown menu under wayland.

### ISSUE THREAD

**Issue by netlore** [tomboy-notes/tomboy-ng#216]
Tomboy-NG, creates a tray widget... and so does steam, both use X, but clicking the widget on steam opens a pulldown menu below the widget when you click on the widget, and that works fine... but Tomboy.... Tomboy opens a pulldown menu at the location of the cursor when you click on the widget.
But Tomboy is an X application, so... if you have opened an X app that starts Xwayland, then the menu appears wherever the mouse last left a part of the screen controlled by an XWayland application... so your pulldown menu probably appears somewhere miles away in discord or another app that depends on X... AND, if you have not started an X based app since booting... you click on the widget and the pulldown menu does not open, because the location of the mouse in X has never been defined!
In the attached image, I opened xeyes as an example X application, to show the effect.

![Screenshot from 2020-12-20 19-00-38](https://user-images.githubusercontent.com/457759/102721967-f16ff880-42f5-11eb-8783-85c40b31984b.png)

**Comment by davidbannon** [comment]
Netlore, you don't mention the desktop/operating system you are using. But I am guessing that its Fedora with Gnome 3 ?
(Thats based on the symptoms you describe and the sad fact that you don't have a single file or directory on your desktop. But if thats the case, you must have some Extension in place to be able to see the icon at all ??)

Anyway, if I am right, or even close, please see the Fedora section of https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release#fedora

Gnome and their close friends, Red Hat, are determined to stamp out the System Tray as we know it. Their excuse is 'clutter'. When they first started this campaign there were a number of Gnome extensions that restored a working System Tray but every new release had changes leaving bystanders such as me wondering if they were there expressly to prevent those Gnome Extensions from working.

So, I altered the way that tomboy-ng works so that its possible to use it without the system tray, as the wiki article explains, you add tomboy-ng to your 'favourites' on the dock. Then, start tomboy-ng, click "Hide" and you see nothing. But clicking the tomboy-ng icon in your Dock will popup the initial instance's Search Window (it won't start a new instance) and that window has the same menu available in the System Tray.

I recently discovered tint2, also mentioned in the wiki. Lo and behold ! It gives you a new panel including a fully functioning system tray.  I don't know how its done on Wayland  as someone has gone to some trouble to "System Tray Proof" Wayland but it does work. My guess is its already been logged as a bug ...

Davo

**Comment by netlore** [comment]
The desktop is actually Ubuntu 21.04 devel (but same issue happens on 20.04), what you see above is just a small part of the desktop, hence the lack of any apparent content... I've attached a full screenshot for your amusement (note the smaller tomboy-ng icon).

I did some more research / testing and discovered a couple of interesting things... hopefully it will interest you, but I also have a question regarding the choice of GTK2 and/or QT, and if the app will "fall back" top GTK.

So, I switched to the QT version, and noticed a couple of things.... primarily, I got different results when starting tomboy-ng from the command line to starting it from the "startup applications" group!...  when starting from the command line, I get a smaller icon which does not need the "TopIcons Plus" system tray extension running to be displayed.... while if I started it from the "startup applications" group, I got a slightly larger icon, apparently rendered by said extension... (running the GTK version I always get the latter).

I initially thought it might be some environment value that was different, so I called a script from "startup", and ran tomboy from the script so that I could check / inject environment values.... but this did not work.  Ultimately I discovered that if I put a small "sleep" in the script, then I always got the icon that does not require the system tray extension.... which does not exhibit the issue pictured in the earlier post above.... note that the issue occurs only when the desktop is Wayland, and hence the app is running using XWayland.

A friend tested on KDE Neon, with the QT version, and found that he got the error below, and I verified that if QT is configured to use the native Wayland backend, this error is displayed, and tomboy-ng will not start... but if QT is configured to use X (via XWayland), it starts OK.

I'm wondering if:-
a) There might be some initialisation code which falls back to GTK (or the GTK tray icon) if something isn't detected, which is in a race condition with the Gnome startup when tomboy is started as a "startup application".?
b) Perhaps here is some code which references X directly, causing issues when there is no X, or only Xwayland?
c) I'm a little confused regarding the reason to use GTK2, when GTK2 EOL has now been announced along with the release of GTK4.

QSocketNotifier: Can only be used with threads started with QThread
[FORMS.PP] ExceptionOccurred 
  Sender=EAccessViolation
  Exception=Access violation
  Stack trace:
  $000055631BC2D723
  $000055631BC12229
  $000055631BD2E1D8
  $000055631BD2DB6A
  $000055631BD29E2C
  $000055631BC74699
  $000055631BC7459B
  $000055631BB45DFA
  $000055631BB438C3
[FORMS.PP] ExceptionOccurred

![Screenshot from 2020-12-22 15-26-15](https://user-images.githubusercontent.com/457759/102908368-4420f000-446f-11eb-8b5c-299568c510bb.jpg)

**Comment by davidbannon** [comment]
Hmm, one seriously hi res screen !
It appears you have done some quite useful research for me here, I thank you. I will try and respond bit by bit. 

I have not bothered testing on Ubuntu under wayland as Cannonical are still (??) shipping xorg as the default.  I do test under wayland on Fedora and thats why we need to use it it that different mode I mentioned. Sorry, its not great but until we get a workable GTK3 version, thats best I can do.  I strongly recommend using xorg itself, not Wayland, its bigger, slower and does not do what we need !  There are a number of documented issues with Wayland and QT that are apparently unlikely to be fixed.

> So, I switched to the QT version, and noticed a couple of things.... 

None of which I can explain. I can replicate that error msg too !  But not the differing icon size. No idea why that would be.  A delay is interesting, there used to be a problem for people using the Enlightenment desktop that was fixed by a short delay, the Enlightenment people eventually fixed the problem and it appears I removed that option. Maybe related to DPI scaling ? Some further work ...

> There might be some initialisation code which falls back to GTK ...

No, the GTK2, GTK3 (don't ask) and QT versions are built from same code base but different compiler options, there 'should' be no GTK2 code in Qt and visa versa. But In Gnome 3, there are a number of compatibility layers loaded, I wonder if you are starting up before that is complete ? 

> Perhaps here is some code which references X directly, causing issues when there is no X, or only Xwayland?

Well, in a way, possibly. QT is, it self a library, it may well make some assumptions about display manager that is well out of our sight.  

>  I'm a little confused regarding the reason to use GTK2

It is the most stable interface. There is a GTK3 interface but its quite incomplete. The problem with GTK3 is Gnome keep fiddling with it. I, personally have submitted patches to fix various GTK3 interface issues only to find, a month later, that GTK3 functions they call have just been deprecated !  Lazarus does not have a huge team of developers tracking the whim of the Gnome people.

There is some hope that with GTK4 on the scene, maybe they will stop changing GTK3 enough for us to catch up. However, GTK3 is, compared to GTK2, huge, slower and much, much more complicated. One wonders what the benefit is .... 

Qt5 on the other hand is quite small, either stable or predictable, fast and looks good. But there is, perhaps a licensing issue, currently not affecting us but ....  And there is definitely a problem with Wayland. Again, one wonders why ?

James, very grateful for your input here, its very useful info and raises matters that I must and will deal with to the best of my ability. But it will take time !

As a matter of interest, why do you choose to use Wayland ?

Davo

**Comment by netlore** [comment]
I've used Tomboy for many years, so the least I can do is test these odd edge cases to help out!... It's been a very useful tool, and I hope it will continue to be, so thank you for your work here!

Some takeaways from my investigations are:-

1) With that sleep at startup, using the QT version, under Gnome, I do not need the extension for system tray icons... perhaps QT is doing it via the libappindicator interface which I think I read somewhere is supported by Gnome now?

2) I added "export QT_QPA_PLATFORMTHEME=gtk2" to my profile which caused the QT version to follow my theme quite passibly, although several of the icons on the edit note screen appeared not to.

3) Ultimately I did get a fully working setup, so thats good.

I must admit, I've had discussions with several other people (less so recently) about the issues caused by the fact that GTK3 seemed to be too tightly integrated with Gnome, and had become a moving target as a result... but it was my understanding that they recognised that the moving target was causing an issue for adoption, and it improved a lot.  From what Ive seen, GTK4 has some good improvements over GTK3, especially performance, and hopefully they will have learned a lesson about keeping the APIs stable.

As for wayland, I resisted it for years... stuff like client side decoration seemed like a recipe for disaster to me, and although it still is. it's better... and it's next to impossible to avoid it now, so I figured that eventually I'm going to have to deal with Wayland, and so I decided to switch, and do some testing to see exactly there the issues are... along with trying to make sure that everything that can be GPU accelerated actually is, which is a lot more complex than you'd think....

**Comment by davidbannon** [comment]
Wow, I learn more from each of your 'questions' !

> With that sleep at startup, using the QT version, under Gnome, I do not need the extension for system tray icons.

Are you saying that works OK with Wayland ???  That would rock me !

> export QT_QPA_PLATFORMTHEME=gtk2

I did not know about that, it may be quite significant as -ng is not picking up most of the colours it should pickup from XFce on Dedian Bullseye.  And I am sort of hoping I will get it into the Bullseye repo before feature freeze. More research is indicated ....

I guess I have not looked positivly at Wayland for some time. I made the(Lazarus)  System Tray interface for GTK3 based around libappindicator3 but concluded that it would not work with Wayland. But that was on Fedora and RedHat are not keen on libappindicator3 because of its origions in Unity. And who can blame them. But if Cannonical have got a working libappindicator3 on Wayland, its a whole new ball game !  Can you please check if you have libappindicator3 installed ?

`find /usr -name "libappindicator*" 2> /dev/null`

Davo

**Comment by netlore** [comment]
>> Are you saying that works OK with Wayland ???

It appears to work just fine.... I mean, obviously the actual tomboy-ng application is running with Xwayland, but the icon and pulldown menu is fine, just as long as I put that little sleep in there.  Come to think about it, it also works fine on my other machine running the GTK2 version (using Xorg), without the extension.... so that must also be using the the same method.  It does not have/need a sleep which could be a) because it's Xorg b) because this machine is WAY faster c) different video driver d) insert more guesses here.

>> I did not know about that

Well, then perhaps this will be useful also!  My system did not by default have the wayland "backend" plugin for QT5, but once I installed that (package is called qtwayland5 on ubuntu), I was able to set QT_QPA_PLATFORM=wayland, which is what generated the FORMS.PP exception above, it appears to default to the "xcb" backend... but set that variable to something invalid, and run a QT app, and it'll list all the available plugins.

>> Can you please check if you have libappindicator3 installed?

james@trinity:~$ find /usr -name "libappindicator*" 2> /dev/null
/usr/lib/x86_64-linux-gnu/libappindicator.so.1.0.0
/usr/lib/x86_64-linux-gnu/libappindicator3.so.1.0.0
/usr/lib/x86_64-linux-gnu/libappindicator.so.1
/usr/lib/x86_64-linux-gnu/libappindicator3.so.1
---SNIP---

This in fact appears to be in the "main" repo, and is in all supported (and dev) versions:- https://packages.ubuntu.com/bionic/libappindicator3-1

Are you saying that libappindicator originated with Unity, I thought it was a KDE thing that was adopted by Unity... perhaps I'm wrong?!....

>> Wow, I learn more from each of your 'questions' !

Honestly the feeling is mutual... I like a good "deep dive" into these issues... but I'm not a developer, so it can be hard to confirm some of my conclusions, hence this is pretty useful to me also.

As an aside, with regard to GTK, this seems pretty compelling when you look at the frame rates in the top right of each:-
https://www.youtube.com/watch?v=p_YMhaBvWIQ

**Comment by davidbannon** [comment]
> It appears to work just fine...., just as long as I put that little sleep in there. 

Can I clarify, if you start tomboy-ng 'manually', after the machine has finished booting and had a little rest, you don't need that sleep ?  Might explain why I don't see this problem.

> QT_QPA_PLATFORM=wayland

I clearly have some reading to do ! 

> libappindicator

IIRC, it was about the time Gnome declared war on the system tray because of the clutter. And, honestly, there was a problem, people were building incredibly complicated apps all happening inside the system tray !  Gnome said never, the Unity people said we can make a very limited, one popup menu, model.  They may well have been inspired by something going on in KDE, I am not sure but I think they championed the model. And good thing too.

That is all good news, the Lazarus GTK3 System Tray is appindicator3 based, and last time I checked, works.  I wonder if it works with Wayland ? My guess is not but I am pinning my colours on qt to be honest.

That demo with GTK3 v 4 is impressive but from memory, GTK3 was not too bad early on, its just they kept adding layers to it, you cannot call this function X any more, you need to declare an object Y, that in turn internally calls X. Oh, and you need a special handle to initiate Y, you can that by creating Z and passing it something you get by ..... 

Grizzle mode off.

Lazarus does not even have a GTK4 plan at this stage, I think everyone is just so unhappy with GTK3 no one wants to work on it. And it is a completely volunteer project. So, no external pressure to keep up. Sigh ...

Davo

**Comment by davidbannon** [comment]
Oh, forgot to mention, with Qt, the qt5ct app is a neat way to setup your colours, 'qt5ct' is then the target for env var you mentioned earlier.
D

**Comment by netlore** [comment]
> Can I clarify, if you start tomboy-ng 'manually', you don't need that sleep?

Correct, it only occurs if you start it at login from the "startup applications", and as I said, I've not tested exactly why, but using my other machine (which runs Xorg, and the GTK version), I do not need the sleep.... tho it may be due to that machine being faster.

> the Lazarus GTK3 System Tray is appindicator3 based, I wonder if it works with Wayland..

I honestly don't see why not, as you can see from my screenshot I have a number of icons up there, for some pretty mainstream apps, some of which are GTK3.

> Lazarus does not even have a GTK4 plan at this stage

I really hope that GTK4 ends up being an admission that GTK3 had some pretty serious issues... have to wait and see I guess... but I know the feeling when it comes to a volunteer project as I have an SSH related project here on github (OpenAKC).... honestly, tomboy uses so little of the toolkit that it's not even really obvious in normal use that there's a difference between the GTK and the QT version.

**Comment by davidbannon** [comment]
So, some related progress. I now have code that can detect if a Desktop does have a System Tray at startup, that may allow me to pop up a warning if it cannot, and to direct user to appropriate alternatives.  

But I cannot duplicate the problem you see at startup.  And have found that if I start -ng on a system without a System Tray, then start, eg, tint2, the icon shows up cleanly in tint2's panel without restarting -ng.  So, struggling to explain your experiences. A suggestion ?  If I make a trivial app that tests for the existence of a System Tray could you set it to autostart and tell me what it does ?  I am expecting, on your system, that the System Tray is not available for a few seconds after startup, this idea will clarify.

"a few seconds"  ? just how long a delay did you find necessary ?

Davo

**Comment by davidbannon** [comment]
Just a follow up, my code that asks X if it has a SysTray or not continues to surprise me -

* It gets it wrong on Ubuntu Gnome 20.04, says there is no SysTray but in fact, there is.
* But the above only applies after doing the test.

To clarify the above, U2004 Gnome will not display the Icon in v0.31, but with my new code, it does because I do that test before trying to display. Hiensenberg Uncertainty, by measuring it, I alter its state.

Overall, its clear Ubuntu Gnome does 'something' to provide its own way to a SysTray, its done behind X's back somehow.  On Fedora, for example, you can only display the icon using things like TopIcons (which fails when using Wayland) or, my recommendation, tint2.

Fedora uses pure Gnome 3, the Gnome devs have declared they will not tolerate a working SysTray.  Ubuntu use a workaround. It seems the workaround is being activated when I poke the X SysTray ....

Interesting ....

Davo

**Comment by davidbannon** [comment]
Pre-release version now available that (may, to some extent) addressed this issue. Please see https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.31
If you do use it, please watch for anything unexpected and please report what you find, good or bad.

**Comment by aguador** [comment]
The 0.31f splash screen tells me that I "might not" have a systray. Yes, in E it is an optional module, but on my system it is loaded and running. No way to detect it?

Even on XFCE the notification area on the panel is indicted as something "external" and is, AFAIK, optional. Yet 0.31f does not show the warning on startup with XFCE.

XFCE raises a separate issue: terminology. Less experienced users may recognize the "notification area" terminology more than "system tray".

**Comment by davidbannon** [comment]
OK, I have done the very best I can here.  -ng now detects the absence of a conventional SysTray and puts a warning in the little splash screen, points to a detailed not on the subject. Unfortunatly, it does generate a false warning on some operating systems that have an unconventional SysTray, if I get a lot of time on my hands, maybe I will inverstigate just wha an unconviontional SysTray is (but probably not).

Ubuntu seems to have no problem building a Gnome Desktop that displays a reliable SysTray, I feel bad that instead of thanking them, I suggest, incorrectly, that it does not work. Sigh ....

Davo
