### ISSUE TITLE
OSX no tray icon

### ISSUE THREAD

**Issue by lhaig** [tomboy-notes/tomboy-ng#22]
The Application does not have an Icon so the default Icon is shown.

<img width="36" alt="screen shot 2017-12-01 at 15 23 11" src="https://user-images.githubusercontent.com/329713/33486802-998c6450-d6ab-11e7-9176-eb3bfe30987c.png">
<img width="197" alt="screen shot 2017-12-01 at 15 24 01" src="https://user-images.githubusercontent.com/329713/33486855-b4a27266-d6ab-11e7-9258-0ce116c2b26e.png">

**Comment by davidbannon** [comment]
Thanks lhaig, I have to admit I knew that but pushed it to the back a bit while on concentrate on function issues. Same thing under Linux and Windows by the way. 
_A warning, unless you are working from the source version, please stop testing until a new release. Have found a bug that messes up the XML of your notes and I don't want to happen !_

**Comment by davidbannon** [comment]
Treating this ticket as tracking Application Icon's for all three platforms. This is the icon that appears on Plank or toolbars when a note is open.

I suspect some of this info is out of date - http://wiki.freepascal.org/Application_Icon

**Mac** (because its a Mac) needs its application icon in a special format. http://www.macinstruct.com/node/59 and the file, once made, is added to the Application Bundle. I have not tried it yet. may involve making a Info.plist file - http://wiki.freepascal.org/Application_Bundle

**Linux** - apparently the two big models, Gnome and KDE agree on how its done. Appropriate resolution files are put in the` /usr/share/icons/hicolor` - hicolor being a icon theme of last resort.  Then a $APPNAME.desktop file is put in `/usr/share/applications/.` that includes eg `Icon=tomboy-ng`. However, I cannot get that to work on my system. If I use a explicit path and file name it works, but thats not how it should be done.
eg -` Icon=/usr/share/icons/hicolor/48x48/apps/tomboy-ng`
https://specifications.freedesktop.org/desktop-entry-spec/latest/apc.html

**Windows** ? http://wiki.freepascal.org/Windows_Icon

**Comment by davidbannon** [comment]
OK, we now have application icons on all three platforms, by that I mean we see an appropriate icon on system tray (or whatever) for a running app. I have not worked out how to make the Mac show an icon when you look at the binary with Finder. We still see the Mac default "paper and pen" thing. 
We do now have a pretty icon when you open the dmg file an "mount" the disk image within, pretty useless IMHO, you only do that when installing ??

Anyway, this ticket is about icons on system tray (or maybe 'plank') either case, its done.
