### ISSUE TITLE
Feature Request: Mass import from text files.

### ISSUE THREAD

**Issue by turgutgenc1** [tomboy-notes/tomboy-ng#227]
Need a script/tool to mass import *.txt files.
Thanks in advance!

**Comment by davidbannon** [comment]
I had a way to do this but it has not been tested for some time and might be a bit risky ....

Hmm, the --save-exit is still there, it was part of a work flow I added for someone who needed it "one off". I don't think I would suggest you try it however.  And my TomboyTools app is, at the moment a pretty messy experimental work bench.

I think I could / would add a command line switch that imports, eg, all *.txt files in a directory. The new notes would, of course, pop up in your main note repository.  Would not be too hard. Is that how you are thinking ?  Something like -

tomboy-ng --import-text /home/dbannon/somedir

Where there are a number of *.txt files in that directory ?

Davo

**Comment by turgutgenc1** [comment]
Yes, that's exactly what I would need :)

**Comment by davidbannon** [comment]
Hmm, thinking about this problem, I think rather than add more bloat to tomboy-ng, I make a second, standalone app. I have one almost ready in fact, I use it to test out all sorts of crazy ideas before they go into tomboy-ng.  So, it just needs a bit of a tidy up.
I call it TomboyTools, or TT, it can be a GUI app or a completely command line driven one. And does things like export all the notes in a given notebook, import all the notes in a particular directory etc.

It works with plain text or markdown and will use your default tomboy-ng directory, or some other dir you care to nominate.

No reason you need this built into tomboy-ng is there ?

Davo

**Comment by turgutgenc1** [comment]
No reason to build this into tomboy-ng, a separate tool would work for me!

**Comment by davidbannon** [comment]
OK, here is a very rough and ready attempt.  Please be careful and watch what it does, at least until you know its working OK.
It can be used as a GUI app or a command line tool, typing `TomboyTools -h <enter>` will give you a nice confusing help page. The GUI on the hand is quite clunky !  Both need a lot of work ...

It does not have an installer yet, just a binary in a zip file. Unzip and copy the binary somewhere on your path, if you want the GUI, you will need to add it to your menus manually or just start it from the command line.  If you use just TomboyTools<enter> it will start the GUI. Otherwise, some switch on the command line will force a command line operation.

I think you wanted to import a directory full of text files into tomboy-ng ?

```
cd Some_Dir <enter>
TomboyTools --action=txt2note <enter>
```

Should do it.  If you want those new notes to be in a particular notebook -

`TomboyTools --action=txt2note --notebook="some note book" <enter>`

Some warnings -
* I have not tested it on Windows, under some time pressure at the moment. Its not doing anything clever, should be OK.
* It does not yet advise tomboy-ng that the import has happened and tomboy-ng should re-read its note list. Seems a really good idea to stop tomboy-ng before you use the importer.
* If you mention a Notebook, it must be one that exists already in tomboy-ng, maybe one day it will be able to create the notebook if necessary but not yet.
* It does not look to see if a note title that its going to use already exists in tomboy-ng's repo, messy if you end up with two notes with the same Title.
* No installer, I can make one but its a time issue right now. If this is a problem, please let me know.
* All this assumes you are using Windows, if you (or anyone else) wants a Linux version, trivial. A Mac version may not be a good idea, it has some funny ideas about one app looking at another app's data.

[TT.zip](https://github.com/tomboy-notes/tomboy-ng/files/5970636/TT.zip)

* please be careful and let me know what you find !
Davo

**Comment by turgutgenc1** [comment]
Just imported ~650 txt files, all seemed successfully imported.
Though when opened the Tomboy-Ng, it complained about a few notes, which had & character in the file name.
Other than that, all went smoothly.
Thank you!

**Comment by davidbannon** [comment]
TomboyTools now lives in its own repository, https://github.com/davidbannon/TomboyTools so I have opened a ticket there to esc the characters XML gets excited about when importing ...

Thanks for the heads up turgutgenc1, I'll close this ticket because its not a tomboy-ng issue.

Davo
