### ISSUE TITLE
Feature Request: keep it simple

### ISSUE THREAD

**Issue by salamander2** [tomboy-notes/tomboy-ng#231]
Hi. Thanks for doing this. I am now just on the point of upgrading from the original Tomboy notes to yours.  The main reason is that I need fixed with formatting for when I paste code snippets and I also would like more font options than bold and yellow highlight.

That being said, please please do not make this too complex. This is designed as a simple notetaking app.  It's perfect as it is. We do not need multilevel bullets; we do not need it to connect to Google Docs; we don't need the notes stored in an SQL database.  We don't need to handle massive notes and tens of thousands of notes without freezing.  If people need these functions, then they probably need a completely different note-taking program.   Trying to be all things to all people ends up in disaster.  The only current feature request that makes sense that I've seen is a search/replace function which should be simple.

If you do decide to make it more complicated, could you please split the project into two versions, and keep the simple one going? Or maybe I'll just make a fork of the current one just in case.  Since we're not dealing with megabytes of data here, storing as text in XML is great. I want to be able to recover from crashes and sync nicely (I use rsync, not trusting other people's sync)

FYI: 

```
#!/bin/bash

#This is the relevant part of my general rsync syncronization script

#General global variables
REMOTEIP="mylaptop.local"
DRYRUN="--dry-run"
DRYRUN=""
DELETE=""
PROGRESS="--progress"
PROGRESS=""
CURRENTDIR=$(pwd)
EXCLUDEFILE=$HOME/bin/rsync_exclude

function pushMe {
   rsync -avzui --safe-links --exclude-from=$EXCLUDEFILE $DRYRUN $PROGRESS --stats "${LOCAL}/" "${TARGET}"
   #rsync -avzui --safe-links --exclude-from=$EXCLUDEFILE $DRYRUN $DELETE $PROGRESS --stats "${LOCAL}/" "${TARGET}"
}   
    
function pullMe {
   rsync -avzui --safe-links --exclude-from=$EXCLUDEFILE $DRYRUN $PROGRESS --stats "${TARGET}/" "${LOCAL}"
   #rsync -avzui --safe-links --exclude-from=$EXCLUDEFILE $DRYRUN $DELETE $PROGRESS --stats "${TARGET}/" "${LOCAL}"
}   

########### SYNC TOMBOY NOTES ##########
printf '\033[01;46m Sync Tomboy  \033[00;37m\n'
LOCAL="/home/griffin/.local/share/tomboy"
TARGET="$REMOTEIP:/home/griffin/.local/share/tomboy"

#copy from local to target
printf '\033[01;31m\n'   #red
echo "###### Push to remote ... ######"
printf '\033[00;37m\n'   #norm
pushMe

#copy from target to local
printf '\033[01;32m\n'   #green
echo "###### Pull from  remote ... ######"
printf '\033[00;37m\n'   #norm
pullMe
```

**Comment by davidbannon** [comment]
Hi salamander2, thanks for your input, its always good to hear 'front line' feedback. A few thoughts ...

Hmm, "font options' ?  Apart from Bold and Highlight, we already do four font sizes, italic and underline. Monospace and Proportional. You can select the base fonts used.  Not sure what else I could add ?  'Pasting code snippits' ?  do you want some language specific formatting ?  I suspect that might be a bit too specialised for most people, I'd need to automatically identify the language used and I cannot see that happening reliably.  Perhaps you can enlarge on that idea ?

I agree re multilevel bullets, personally I don't need them, given its a note tool, not a presentation one.

No way would I connect it to google docs. Google does not get to see my notes !

I do however have a number of loyal long term users who have either (or both) very large notes or a very large number of notes. They are important to me so keeping performance acceptable for them is a KPI. Doing so also ensure more modest note collections are usable with users on low end hardware too.

I am working on a Undo/Redo capability but its not, in any sense, simple under the skin. But I am convinced its needed.  So, I will allow people to select to use Undo or not, depending on their needs. I guess a search and replace would be nice to have but maybe a lower priority right now.

I do not intend to split the codebase into higher and lower functionalities.  Thats what brought the orig Tomboy to its knees, first a separate Mac version, then windows version became dependent on specific versions of GTK2+, no, all my spare time is committed to just one version so that means it does need, in some respects, to be a compromise between competing KPIs. But life is like that, isn't it ?

I too use rsync, its a cool tool. But not actually useful when syncing Tomboy notes. The reason is notes contain significant last update fields that rsync cannot be aware of, we record, according to the Tomboy standard, both a last change and a last metadata change date. And, important if you have more than two parties to a sync, tomboy-ng incorporates means to display differences between notes when a clash is detected. Its a remarkably complicated process.  In practicse, a Tomboy note is rewritten with slightly different content quite frequently even if you don't make any deliberate changes. Rsync will not be able to dismiss such unimportant changes.

So, use your script by all means but be aware that even with just a two party sync, it can have problems.

Thanks for your input !

Davo

**Comment by salamander2** [comment]
@davidbannon Thank you for your gracious and detailed reply. You have obviously spent far more time thinking about this than I have. 

Yes, I realize that what I said about fonts was bizarre. I hadn't looked into the options. The main thing that I wanted was a second highlight colour. (It wouldn't be too hard for me to modify the code to do this.)

I had no idea about what caused Tomboy's demise. I can't tell from the github repo that there were problems with OS releases.  I only use it on Linux so it doesn't affect me. 

I might actually have something useful to contribute.  I contacted the author of KControls about undo/redo and he/she said 
_"It is planned. It has highest priority of all todos at least for tracking text changes. But it seems first I have to sell my company to get enough time and concentration for this."_  Surely there would be some Pascal programmers who would be willing contribute to an open source project and help out?

Best wishes.
