### ISSUE TITLE
Not all notes appear in menu dropdown

### ISSUE THREAD

**Issue by tundratim** [tomboy-notes/tomboy-ng#235]
It seems that the dropdown menu shows the last 10 notes edited.

Is there a way to change to either show all existing notes, or at least way more than 10, the way tomdroid does?

**Comment by davidbannon** [comment]
Hmm, from what I remember, Tomboy only showed the most recent 10 too ?  Maybe I am wrong there.

I certainly cannot show "all", I have about 250 notes and have users with 20,000 ! And many users use smaller screens and the current size of that menu is about the limit for them.

But it should be possible to make that a config option, it would need to be a "restart option" because I allocate space for the menu during startup but thats probably acceptable. The menu system is quite complicated because it appears in several places, so changes in there require some planning and careful testing, I'm not committing to be able to do that quickly !

Davo

**Comment by tundratim** [comment]
Well ... since I am asking for the moon here ;)  The most desirable way to do this would be to have a menu element that an scroll through the available notes and the ability to select how they are ordered (by datetime, by name, by size....)  Failing that, a config option to set max displayed would be most useful.

Thanks for saving my notes!

**Comment by davidbannon** [comment]
Well, ask for he moon by all means!  But most  cases, you'll probably just get a meteor I'm afraid. But it does no harm to ask !
The scroll-able and sort-able note list is in the search form (although I don't do by size) and I think it would overly complicate the menu, making it slower and even harder to use as intended.  I would not be able to use the OS Menu APIs, would need a new popup window. The full strength Search Form is only one click away ...

I will look at making the number of notes listed in that menu configurable but probably won't make next release but will try for the one after.

Thanks for your input, very important !

Davo

**Comment by tundratim** [comment]
I think being able to bump it up to a larger number should suffice.

Do you want this issue closed or left open as a reminder?

**Comment by davidbannon** [comment]
Please leave it open, we'll close when a release addresses the issue.

Davo

**Comment by aguador** [comment]
Yes, original Tomboy used the search form as a sort of main window. I recall clearly because, having Tomboy as a program loaded at startup, I always modified the desktop file in Linux to prevent it opening the search window, preferring to access it from the systray when needed. What Davo has done with -ng is give access directly to the most recent notes without opening the search form.

@tundratim, if you prefer having access to a scrollable list, but there is an option to launch -ng with the search window open (on the first config tab). Would that work for you? You can later keep the window open and minimize it, or invoke it from the popup. Using search directly also allows you to ease your scrolling by choosing specific notebooks, if you use that feature. I don't believe the search window size/number of rows is configurable, although it can be maximized to see more. However, but it should be easy (an adjective that emerges from the perfect ignorance of a non-programmer!) to have a "preferred window size" option or even allow choice of type size for the search window to allow more to be seen.

**Comment by aguador** [comment]
Another approach just occurred to me: what if there were a switch to open either the current popup OR the search window when clicking on the systray icon? While I like the current approach, offering direct access to the search form would save a click for those who want to have access to their full list. Those who want the full list would lose nothing as they still have access to other options via the menu button on the search form.

**Comment by tundratim** [comment]
@aguador One click to open the full search menu might be interesting, but IMHO the default behavior (or a config option) should be that once you pick the note, the search menu should disappear, just as the dropdown does today.

In any case, having a configurable dropdown length would still be helpful.

Another approach would be to enable organizing notes in folders/by topic so that the dropdown could navigate both individual notes at the top level, or through a folder hierarchy below it.

**Comment by davidbannon** [comment]
I am not keen on the idea of having, even as an option, one click on the tray icon to show the search form.  At present, that one click shows 10 recent notes AND a number of options, all those options (New Note, Settings, Sync ....) would be hidden if we went straight to the Search form.

And, honestly, its just one more click, the mouse is already highlighting the entries there, Search is the second entry down, its about as easy as it could get IMHO.  Back when tray icons were allowed to respond to a right click perhaps we could help but I have to say, I don't see either any scope to improve it or really, much need. 
As aguador said, we can start tomboy-ng with the search form open (there is a setting for that as well as the cmd line switch), but if you then hide it (or it hides itself when you open a note) we are back to where we started, aren't we ?

On my current desktop, every tray icon (and I have a few) pulls down a menu, you must choose a menu item, I don't think that is that bad a UI issue.

Davo

**Comment by davidbannon** [comment]
Another approach I forgot to mention.  If tomboy-ng is already running (either visible or hidden), and an attempt is made start it again, the search form for the existing instance is opened and brought to your current view.  So, if you have a shortcut to tomboy-ng on your desktop or any one of the other ways of starting an app, using it will automatically bring the search form into view.

Davo

**Comment by tundratim** [comment]
@davidbannon that last one pretty much solves for my issue, though I'd still love to be able to increase the number of displayed menu elements and/or be able to organize by tags.

**Comment by davidbannon** [comment]
I have had a look at this idea of making the number of recent notes displayed in the menu configurable but have decided against it, the problem is that tomboy-ng auto saves as you are typing, that happens every 10 seconds of so.  When that auto save is triggered, it rewrites the menu and there is an upstream problem there that I cannot fully understand, it makes the update slower than it should be. As that happens while you are typing I don't want to lengthen the delay and extend it by having to look up your settings to see how many entries you want.

Hope you understand.

Davo
