### ISSUE TITLE
Access violation if launched under KDE Wayland

### ISSUE THREAD

**Issue by RussH** [tomboy-notes/tomboy-ng#243]
If started in a KDE Wayland session I receive an 'Access Violation' warning. No issues if started under a normal X session. 

Doesn't appear to be an actual issue, just receive an access violation message.

**Comment by RussH** [comment]
launching with QT_QPA_PLATFORM=xcb  tomboy-ng removes the warning

**Comment by davidbannon** [comment]
Hmm, access violations are always nasty !  I find that QT and Wayland don't seem to be a good mix, not just with tomboy-ng.  

Setting xcb like that tells QT to use the older (but more stable) X model, almost all of xlib is now in libxcb.  Right now there seems absolutely no downside to bypassing wayland so, if it works stick with it. But I think that the GTK2 variety is preferable in a Wayland system.

So, who is shipping KDE with Wayland at the moment, I thought it was only happening with Gnome for the time being ?

Davo

**Comment by RussH** [comment]
Hi @davidbannon Fedora 34 has KDE using Wayland by default - but I'm using KDE Neon which has Wayland as an option. 

I see that   QT_QPA_PLATFORM=wayland tomboy-ng still causes the error message. Enabling debug didn't generate anything, but I did get some errors sent to console;

> russh@russ-surfacepro3:~$ QT_QPA_PLATFORM=wayland tomboy-ng --debug-log=tomboy-wayland-debug.log
> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
>

**Comment by davidbannon** [comment]
Hmm, I develop on a HiDPI screen and usually see Qt5 as sharp (or better) that GTK2.  If you could send me a snapshot of that, might be helpful.  

Those lines dumped out by Qt don't look too threatening, probably just noting that Wayland is not being used. If nothing else untoward happens, I would not worry about it. The fuzzy Windows on the other hand is much more of a worry.

The --debug-log switch is normally only used on Windows and Mac, Linux gets a real console so we see everything.  But nothing to see (usually) unless you also turn on one of specific debug categories. And I am afraid there is not a specific debug category for the issue you are having. Its 'upstream' from my code.

If I were you, I would consider the GTK2 version, even if you don't already have the GTK2 libraries, you will need them sooner or later !

Davo

**Comment by davidbannon** [comment]
My only (?!) KDE test machine is MXLinux, pretty sure it does not use Wayland. But tried anyway, nothing that could be called a fuzzy window. Looks good in fact. Sigh ...

**Comment by RussH** [comment]
here's what I have.. possibly just 'less sharp' rather than 'fuzzy'
![Tomboy-ng-HiDPI-wayland vs xcb](https://user-images.githubusercontent.com/282748/122372951-018d2b80-cf59-11eb-87fe-fdd82fd26953.png)

**Comment by davidbannon** [comment]
OK, while initially I preferred the left hand side, zooming in tells me the Wayland, right hand side is sharper. I wonder if we are seeing a difference between black text and dark grey ? Or, maybe, a thinner stroked font ?  
A rendering issue anyway I am afraid. Outside what I have any control of.
I note tomboy-ng splash screen in the background of Wayland version, those buttons should be of equal width, what version are you using ?

Davo

**Comment by RussH** [comment]
Thanks for checking into that, must just be a native rendering issue wayland vs xcb - and I've got I've got tomboy-ng/now 0.32 amd64 [installed,local]

**Comment by davidbannon** [comment]
V0.33a now released.  I'll close this if you don't mind.
Davo

**Comment by davidbannon** [comment]
cboling2, thanks for that. Are you refering to the Access Violation warning or the Fuzzy text when using xcb ?
I have been using KDE on Debian 12 quite a lot recently (testing new Lazarus feature using native dialogs) and have not experienced either problem at any stage. So, sorry, more questions -
- When do you see this AV ? At startup, when opening a note etc ? Do you see it only once of repeatedly while working ?
- I guess you use the tomboy-ng direct from the debian repo ?  
- Can you tell me what (if anything) QT_QPA_PLATFORMTHEME is set to ?  (Command prompt, "echo $QT_QPA_PLATFORMTHEME <enter>")
 
I expect the problem lies in the Qt5 Lazarus interface, not the tomboy-ng code. There has been some substantial improvements to Lazarus's QT5 recently, maybe, if you are willing, I could send you a newly compiled version and see if that solves the problem. Sadly, I cannot get those improvements into Debian at present, they are in an as yet unreleased version of Lazarus and Debian is quite strict about using released only code. But if I send you a deb, you can install it manually (and Debian will later overwrite it when a higher version is released).

Davo

**Comment by cboling2** [comment]
(Oops, I replied yesterday but for some reason my mail client ignored
the Reply-To field and replied to ***@***.*** That address
is a black hole; it didn't bounce it.)

Sorry for being, er, fuzzy in my description. :-)
I was referring to the Access Violation error.

The message occurs each time I run the program. So far, it seems to be
stable after that. Quit and rerun tomboy-ng, and the error occurs.

To clarify something that RussH noted: the "qt.qpa.wayland" console
messages do not appear until after the AV dialog box is dismissed.

I'm indeed using the version from the stock Debian repo.

(My workstation running Ubuntu 18.04 -- and the original tomboy -- lost
its motherboard, so I'm trying to rebuild my life... better, stronger,
faster...)

$QT_QPA_PLATFORMTHEME is not set in the environment.

I'm happy to take a package test to try. Just the executable is fine,
too. You won't catch me writing kernel modules, but I've used *ix for
>30 years and am quite comfortable bumping around in the shell.

Heck, if we fail to find the trigger that way, maybe it's the excuse I
need to move past Delphi 5* and install Lazarus. :-)

(*Oops, I forgot, I upgraded to 7 a while back. I learned Delphi to
write a fairly major app in 2001, and still maintain it in the same w2k
VM that it started on!)

-- 
Charles Boling

PGP Public Key: http://www.boling.us/pgp/charles.html

**Comment by davidbannon** [comment]
Sorry, been neglecting this issue.

Unfortunately, I cannot replicate this problem.

Firstly, yes Charles, install Lazarus, join us, do not be afraid, you will be assimilated ....

However, I suspect its not a tomboy-ng, nor even a Lazarus issue. More, probably somewhere between Qt5 and Wayland. The fact that it does not disturb tomboy-ng itself says the AV is being handled at a lower level, we do not mask AVs. I have been quite surprised just how unhappy Qt5 apps seem under KDE/Plasma where they should be most comfortable.

In the past, I have recommended KDE users use the GTK2 version of the app (for people who get it direct from github, they have a choice) but with Debian 12 we moved to Qt5. And see lots of various messages since KDE adopted Wayland. On the other hand, it seems to be getting better. The as yet unreleased Lazarus 3 does Qt5 and Qt6 heaps better, particularly native dialogs. I will, in the not too distant future, release v0.37 of tomboy-ng. Unless Lazarus 3 has been released by then, tomboy-ng will be built with the dev version of Lazarus for users who download from Github. But Debian does not play games like that !

OK, enough gossip. Here are our options.

* Wait for 0.37 and do a manual install.
* Wait for a 0.37 beta (soon) and try that.
* Want to try a Qt6 version ? The Lazarus Qt master believes it is more stable that even Qt5 !
* Go backwards and try a gtk2 version of tomboy-ng, no, please no.
* Experiment with different QT_QPA_PLATFORMTHEME settings.
* Experiment with QT_QPA_PLATFORM - this bypasses or directs around Wayland.
* (I don't suppose you would consider installing Mate DE, you would be amazed how much faster your machine runs ;-) )

Given I cannot see this issue here, I cannot say with any surety what is the best approach.

Hmm, my KDE install (in Virtual Box) does also have several other Desktops installed, I wonder if thats masking the issue ?  Maybe I should try a clean install of KDE Bookworm, if I can see this issue, I can maybe, find a workaround (I don't expect to find a code fix.)  Not tonight, getting late ....

Davo

**Comment by cboling2** [comment]
I happen to have a VM w/ snapshots containing a fresh install of Bookworm w/ each of the DEs offered by tasksel; I made it for several of my children (and I) to play with in order to choose their preferred DE for their college laptops. (I chose KDE myself partly to "eat my own dog food" and be better able to support my wife, who runs Kubuntu. The younger kids' LTSP server runs MATE on their 7 workstations.)

I tried Tomboy-NG on each of the DEs. Here's the scoreboard:

**Has problem:**

- KDE

**No problem:**

- Gnome (no indicator icon)
- XFCE
- GNOME-Flashback
- Cinnamon
- MATE
- LXDE
- LXQT

Naturally, LKQT & KDE had the fewest extra pkgs needed, vs. the GTK-based environments. I wonder if it's as simple as the KDE task failing to install a pkg that all the others provide.

I have no desire to clutter my new workstation w/ stuff from extra DEs, but since I can replicate the problem in the VM, I can play all I want. Also, since I can replicate the issue in a fresh VM install, I assume you'll be able to as well.

I shall await your instruction.

**Comment by davidbannon** [comment]
OK, finally got some time to look at this. Sorry I have taken so long !

I have looked at Debian Bookworm and Trixie (testing) using tomboy-ng Qt5 and Qt6 and version ranging from that in Bookworm, 0.36a to a beta 0.36f

So, yep, I see that **AV**, it originates in the Qt5 code I am afraid, beyond my pay scale. Avoided by setting QT_QPA_PLATFORM=xcb as per https://github.com/tomboy-notes/tomboy-ng/wiki/Bugs-and-Known-Issues .  Or, of course, setting KDE to use X11 instead of Wayland. Interesting, Qt6 does not have that problem. I guess the Qt folk or the Wayland folk might be a bit more focused on Qt6 ?  I don't know ....

The other problem I see, perhaps more worrying, is that a **left click** on the tray icon pops up the menu in an apparently random screen positions. This was a common problem when Gnome first switched to Wayland, while lots of fixes were tried, eventually the Gnome / Wayland people got on top of it and thats pretty much what I expect will happen here.

Again, its not a problem if  KDE is instructed to use X11 instead of Wayland.

In the mean time, because its really, really annoying, I noticed that KDE pops up the same menu with a Right Click, and the Right Click menu pops up in the right place. So, I have made a change that appears in tomboy-ng 0.36f (and probably the forthcoming 0.37). For any KDE install, now, the left click just send a notification that says "please right click". Sadly, this will also impact on KDE who are using X11 (I sure would be if I used KDE) but I cannot tell reliably if Wayland is in use or not.

Now, the downside of using 0.36f Qt5 (or Qt6 for that matter) is you MUST install updated libqt5pas or libqt6pas libraries. The ones in the distribution do not support the good things that are now in Lazarus and won't be until Lazarus 3.0 is released and the distributions catch up. I am not pleased to force a manual update to these libraries but the Qt fixes in Lazarus 3.0 are quite significant and I cannot ignore them.

**Ref -** 
* tomboy-ng bugs and known issues page - https://github.com/tomboy-notes/tomboy-ng/wiki/Bugs-and-Known-Issues 
* Where there will be beta 0.36f packages shortly - https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.36c
* Repo for unofficial libqt5pas1 libraries - https://github.com/davidbannon/libqt5pas/releases
* Repo for unofficial libqt6pas6 libraries - https://github.com/davidbannon/libqt6pas/releases

I hope this helps, not a great set of solutions but best I can do I am afraid.

David

**Comment by cboling2** [comment]
Wow, nice detective work. Clever workaround for the left-click problem, too.  Thanks!

**Comment by davidbannon** [comment]
I believe I know just a touch more about this issue now, I think it is an AV that occurs in KDE if it appears that libayanata has been installed. If tomboy-ng thinks libayatana is available, it chooses to use it. However, that is, more often than not, especially under Wayland not a good choice.
In the cases I have been looking into, libayatana gets installed for a number of reasons, the most common is when the box has multiple desktops installed. Things like Mate, Cinnonmen, Budgie, Xfce etc all need and use libayatana. KDE does however, alone amongst the desktops, provides its own, working TrayIcon interface.

The next release, 0.37, pretty much ready to go now, has a bit finer control of just which TrayIcon model we use. I am half wondering if a blanket, if KDE, dont use libayatana is appropriate. The ayatana experience is a bit better IMHO on a X11 KDE box but everyone is shifting to Wayland. 

Anyway, pretty sure this is a "fixed in next release" !

Davo

**Comment by cboling2** [comment]
Very nice. I see your patch in the Lazarus forum, too. Thanks for your work!

**Comment by davidbannon** [comment]
OK, this issue fixed in https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release

So closing this issue, thanks for your report.

Davo
