### ISSUE TITLE
Can't disable sync info window

### ISSUE THREAD

**Issue by ZardoZAntony** [tomboy-notes/tomboy-ng#244]
Realy bad idea to show this window. It's trash info for users. And this window captures focus too. Plz, show this window only if had error.
OS: Windows 10
ver 0.32

**Comment by davidbannon** [comment]
Which window are you talking about please ?  It could be -
The initial one when you run a sync the first time. It quite possibly stays there for awhile because the first sync is quite a slow process. And also one where a number of errors may be picked up, especially if you have some old notes.   After that first sync it is usually only shown for a few seconds after you manually trigger a sync.
If you use auto sync, its not show at all (unless an error is detected) so it does not interrupt your work flow.

Or do you mean the small (grey ?) notification window that pops up, (top left) in autosync to tell you autosync  ran OK ?  I am not proud of that but using Windows built in notification system is, at present, quite beyond me. Its a lot better on Linux and, sadly, worse on Mac.

Or is it the Sync Clash Window ?  That happens in auto or manual sync if we have a sync clash, that quite important because you risk loosing content.

Sorry you don't like it but my model puts a lot of weight in keeping user notes safe. I do a lot of checks and reports that the original Tomboy did not do for example. Many long time Tomboy users who switch to -ng suddenly find they have damaged notes that Tomboy ignored but -ng worries about (and can restore for them).

I guess its the old story that one man's trash is another man's gold !

If you identify the window that's worrying you, I may be able to do something about making it optional.

Davo

**Comment by davidbannon** [comment]
sorry, accidentally closed this ticket.
Davo

**Comment by ZardoZAntony** [comment]
Thx for fast reply!

> Or do you mean the small (grey ?) notification window that pops up, (top left) in autosync to tell you autosync ran OK ? I am not proud of that but using Windows built in notification system is, at present, quite beyond me. Its a lot better on Linux and, sadly, worse on Mac.

Yes, i spoke about this window. Plz will make option for disable this notification.

**Comment by davidbannon** [comment]
Right ! That makes sense.
Thanks
Davo

**Comment by davidbannon** [comment]
OK, version 0.33, due out pretty soon, will have a setting to disable Notifications.
Davo

**Comment by davidbannon** [comment]
OK, fixed in version 0.33a, thanks for the report.
Davo
