### ISSUE TITLE
Auto Date in Title

### ISSUE THREAD

**Issue by JosephB1011** [tomboy-notes/tomboy-ng#255]
First of all thank you for taking on the task of working on Tomboy-ng.
I have been using Tomboy for many years.
There's are two things I would like to address in the settings:
Version installed 0.34 GTK2
1- There needs to be a "No Date or Blank" option is the Date option. I find that very frustrating, as I always give my notes a proper title that makes sense.
2- On Linux Mint 20.2, when I make changes to the settings page, the changes are not stored and are not applied to the next note. Even after closing the app and restarting it.
Any help would be great!
Thank you

**Comment by davidbannon** [comment]
Hi Joseph, thanks for the report.

No Date or Blank ?  You mean the default title for a new note ?  I have there, slavishly followed the original Tomboy and a couple of people have commented on that choice.  We do need to be sure there is a title because the note is autosaved if any change is made.  But, honestly, no one leaves that default, its horrible !  Hmm, what if I auto selected it on create, that way, if you started typing (without moving cursor first) what you type first becomes the new title ? Yes, "something" needs to be done.

> On Linux Mint 20.2 ...

Now, that sounds really nasty. No idea whats happening there. The config file is (almost certainly) in $HOME/.config/tomboy-ng/tomboy-ng.cfg - can you please see if its there, when it was last changed ?

Does the problem apply to all config options, not just one specific one ?

It is possible to alter where the config file is, its a command line option so, maybe starting tomboy-ng from the command line where you can be sure there is nothing added ? Don't forget to stop the existing instance before starting a new one.

I do test against Linux Mint, did not see anything like this !

Davo

**Comment by davidbannon** [comment]
Any further info on this topic ?
Davo

**Comment by davidbannon** [comment]
No further info on this problem, I guess we have to assume its no longer an issue.
So, I'll close
Thanks for the report.
Davo
