### ISSUE TITLE
Numbers are displayed in weird caracters

### ISSUE THREAD

**Issue by nguxx** [tomboy-notes/tomboy-ng#256]
Hi,
Since update to Debian bookworm, the numbers are displayed in the settings as special caracters (glyphs ? my english is not that good ;-/) (but not in the notes when you use [ctrl + t])
it looks like this : 
[CaptureOfTheDateInSettings](https://zupimages.net/viewer.php?id=21/51/ju0p.png)

Changing the font do nothing.
Any idea ?
Thanks

**Config** :
```bash
:~$ uname -a
Linux deb 5.15.0-2-amd64 #1 SMP Debian 5.15.5-1 (2021-11-26) x86_64 GNU/Linux
:~$ lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux bookworm/sid
Release:	testing
Codename:	bookworm
```

**Comment by davidbannon** [comment]
Hmm,  nguxx, I have no idea what could cause that. I use Debian Bookworm quite a lot myself and have not seen anything like that.

Can you please tell me what Desktop (gnome, plasma, Mate etc) you are using. And can you tell me what country you are configured to use ?

And your default font ?  (you may be able to tell what that is by going to settings, Notes tab and holding the mouse over the "Normal Font" button.

Its only numbers that go wrong, not letters ??  I have no idea, will need to duplicate your problem here to see whats happening....

Davo

**Comment by nguxx** [comment]
Hi David,
Thanks for your quick response.
Yes my country is France but language of my Debian is US English with French Keyboard. 
Yes it is only on numbers an only with Normal mode for the caracters
[Wrinting in a new note](https://zupimages.net/viewer.php?id=21/51/gk6p.png)
Difficult to tell what is my version with those symbols xD
[version of Tomboy-ng](https://zupimages.net/viewer.php?id=21/51/ypd9.png)

**Comment by nguxx** [comment]
Hi David,
Thank you for your quick response.
It's fixed, it just needed a reboot after the upgrade... Sooy for the disturbance.
But it was weird 
Yes it was only on numbers and only in Normal mode.
Jest for the fun :
[a new note](https://zupimages.net/viewer.php?id=21/51/gk6p.png)
[trying to read the version](https://www.zupimages.net/viewer.php?id=21/51/ypd9.png) xD
[the actual version now](https://zupimages.net/viewer.php?id=21/51/hn2r.png)
Happy holiday season!

**Comment by davidbannon** [comment]
OK, glad its all good now.  But, as you say, weird.  If I wanted it to do that, I really don't know what I would have to do !  (but its OK, I don't want it to happen!)

Hope all is well with you over Christmas !

Davo
