### ISSUE TITLE
Fix listing in Gnome Software to show that it is community built in the open

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#259]
Currently in the Gnome software store, Tomboy-NG gets shown as "potentially unsafe" due to proprietary code and in the license section states "This software is not developed in the open".

![tomboy-ng-screenshot-showing-proprietary-potentially-unsafe](https://user-images.githubusercontent.com/27131/156889046-a76f7bf0-8db5-4bd2-ab7f-145305d90d58.png)

Instead it should be saying something like the original Tomboy does: "**Community Built** This software is developed in the open by a community of volunteers, and released under the LGPL-2.1+ license.  You can contribute and help make it even better." with a "Get Involved" link to https://wiki.gnome.org/Apps/Tomboy

**Comment by davidbannon** [comment]
Mincn, I am guessing Ubuntu ?  Are you looking at an entry in the Gnome Software app's catalog or are you using that app to open a tomboy-ng deb file downloaded by yourself ?  Ubuntu have a policy of stamping any deb that does not come from their own catalog as proprietary. Its not a mistake, its deliberate as the problem has been pointed out to them on many occasions and applying to many different apps.

https://askubuntu.com/questions/1117073/why-does-software-centre-mark-any-local-deb-as-proprietary

Using gdebi is, IMHO the better way to install a downloaded deb file with a GUI, apt from the commandline. Synaptic is, by far, a better way to install applications from the official repository.

All code in tomboy-ng is stamped with a completely open source license and it has a copyright file listing all those licenses that is acceptable to Debian, and they are the gold standard when it comes to open licenses, believe me ! And, of course, Ubuntu get their packages, ready made, from Debian.

https://metadata.ftp-master.debian.org/changelogs//main/t/tomboy-ng/tomboy-ng_0.32-2_copyright

https://metadata.ftp-master.debian.org/changelogs//main/t/tomboy-ng/tomboy-ng_0.34-1_copyright

I personally have abandoned Ubuntu because of its disinterest in its users. I, and many, many other people have reported this bug, they ignore it, then there is the Snap issue, the failure to update Evolution or Thunderbird to do Google Contacts, hostility to the Tray Icon.... Perhaps because they don't really care about open source, perhaps because they want to direct you to their commercial partners ?  Its all a mystery to me. And totally out of my hands, you could try reporting it to Ubuntu (or even Gnome) but I cannot find my original bug reports so I assume its on their "will not fix" list.

Sorry I cannot be of more help.

Davo

**Comment by davidbannon** [comment]
OK, Ben, you got me thinking. While I can explain the above away, I still resent it !  But your post gave me an idea. "No screenshot provided" ?  

So, I found that Debian run a repository of all the screenshots that appear in (eg) the Gnome Software Centre, so, I have uploaded one that shows tomboy-ng and a couple of notes. The main note shown says, quite prominently, that tomboy-ng is 100% open source !

Will take a few days to be approved apparently, we'll see.  Thanks for the prod !

Davo

**Comment by davidbannon** [comment]
Hmm, no, that did not help on Ubuntu, seems it gets its screen shots elsewhere. Maybe they are a bit scared you may get accurate information.

Which OS are you using mlncn ?

Davo

**Comment by mlncn** [comment]
Debian 11 with Gnome 41.4

**Comment by davidbannon** [comment]
OK, beats me.  https://screenshots.debian.net claims that Ubuntu Software uses it, but my test says otherwise. The site, despite being a Debian service, does not claim Debian uses it.

I have established that Synaptic does, and thats a far better install manager that Gnome|Ubuntu Software IMHO. Both 
 packages.debian.org and packages.ubuntu.com do use it.

Sorry, thats all I can do. It is Open Source, the copyright file clearly says so. I have logged it as a bug against Ubuntu Software several years ago.

Davo

**Comment by davidbannon** [comment]
Hey, I just looked at U22.04, the "Software Store" no longer describes apps other than their own as Proprietary - now says "Potentially unsafe, provided by a third party" and does not mention the license specifically. As most distros use the same app (its from Gnome), I guess that's not perfect but a lot better !

( Gnome (who make the app) states that packages installed from debs or RPMs cannot have any safety information, implying that Snaps, Flatpacks etc are safer. Maybe, but slower and wasteful of memory and diskspace. And we all know how useful it is trying to influence Gnome policy. )

As most distros use the same app, I guess that's not perfect but a lot better ! I'll close this ticket....
