### ISSUE TITLE
Most notebooks disappeared After a search; pressing "Refresh" brings them back

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#28]
This is probably more a UX problem than a functionality problem, but after a previous search, the search bar was clear, and all notes *appeared* to be listed— certainly more than my previous narrow search— but only one of seven notebooks was shown in the sidebar.

v0.12 of tomboy-ng. Build date 2018/01/31 TargetCPU x86_64 OS Linux

**Comment by davidbannon** [comment]
Yeah, I had some problems here working out just what should happen around this space. It was further complicated by my need to avoid updating the recently used list because of the Mac memory leak happened at that point. But that issue is solved so I have a bit more flexibility.  
So, happy to revisit this issue. Could you outline, step by step, what you would expect to see happening ? Compared to what does ?

**Comment by davidbannon** [comment]
OK, lets get this clear. At present, you -

- Click a notebook, only notes in that notebook are shown. The notebook name is highlighted.
- Type a term in the searchbox, enter. All notes are searched, ones with the term displayed but the highlight remains on the previously selected Notebook name.

Not hard to see thats wrong but what would be right ?  Should we only search for notes in that notebook at that time ?  Thats probably the best approach ....
Alternatively, I can just clear the highlight in Notebook list to make it plain we searched the lot. But I don't think thats what a user would expect ?

**Comment by davidbannon** [comment]
Does not seem a lot of interest here.
