### ISSUE TITLE
Github Sync fails with OpenSSL error

### ISSUE THREAD

**Issue by Chlorine8477** [tomboy-notes/tomboy-ng#284]
Trying to setup the Github Sync fails with the following error:

**Unable to proceed because Github Downloader - InOutError Could not initialize OpenSSL library**
OpenSSL library in Fedora Workstation 37 is installed, everything else seems to work.

Is there a way to write a log?

**Comment by davidbannon** [comment]
Hmm, thats an interesting one. I suspect there may be an SSL incompatibility here. Its not unusual when working with SSL !
You might see a more detailed error report if you run from the command line. Where I can, I drop things like that to console. 
But I suspect I might need to do some debugging here.  Is yours a fresh install or an upgrade from previous versions ?  Has it worked with previous versions of Fedora ?
Thanks for the report !
Davo

**Comment by davidbannon** [comment]
No Chlorine8477, I have not been able to replicate the issue here. Ran it up on a F 37 vm, it synced against github just fine for me. I even tried updating the OS thinking maybe a new libssl was an issue, still fine.  Have you updated there ?

Now, I "believe" I have trapped out all the possible token or network errors (and give you a more useful error message) but I guess we have to assume I have missed one. I cannot think what else it could be. Maybe I get you a binary with a bit more debugging going on in that section of the code and you run it, show me the results ?

Which widget set are you using, gtk2 or Qt5 ?

Davo

Chlorine ? Its a poisonous gas !

**Comment by Chlorine8477** [comment]
Good morning David,
I assure you, I am not really toxic, but it makes people weary ;)
To the matter at hand: I am running tomboy-ng on GTK2 on a very updated Fedora Workstation 37, fresh out of the box. 
BUT it might be the 64-bit version, I will try the 32 bit version later today.
strace did not really output anything interesting btw....

I'll get back to you later

**Comment by davidbannon** [comment]
I sort of doubt its a 32/64 bit issue although I do know that is handled differently on Fedora than the deb based systems I am familiar with. Its an I/O error and, as near as I tell, the httpclient unit itself does not raise an EInOutException. That suggests to me that the problem relates, some how, to being unable to open libssl. It also would seem unlikely that you could have a libssl problem and be otherwise unaware of it ! Most unlikely...

Did your strace indicate that libssl was opened OK ?

Even less likely is a failure to save a downloaded file, perhaps because of write protection. I am pretty sure the error occurs before download, not after. But ...

A mystery indeed.

Davo

Warning, don't upload to here an strace with having a good look first, I suspect it could show your github token !

**Comment by davidbannon** [comment]
Hey Chlorine, any further thoughts on this ?
Davo

**Comment by davidbannon** [comment]
One way or another, this issue seems to be a stale one.

Thanks for your report.

Davo

**Comment by cleverfrog** [comment]
In case anyone has trouble with this on ubuntu - this solved it for me (not sure if it's the right way to go, but it seems to work now)

sudo apt-get purge openssl
sudo apt-get install libssl-dev

**Comment by davidbannon** [comment]
Indeed, cleverfrog, installing libssl-dev is a solution for linux users. Lazarus, when it cannot find a suitable version openssl tries the non-versioned version, which is provided by the -dev package (actually just a symlink without any version number pointing the the installed version).

I currently have a version out, built with FPC323 that directly solves this problem.  Hope to release it soon.

thanks,
Davo

**Comment by davidbannon** [comment]
This matter addressed in the new, 0.40 release of tomboy-ng.
Thank you for you input.
David

**Comment by vryy** [comment]
This problem happens in Windows (Version 10.0.19045) as well

**Comment by davidbannon** [comment]
Ah, vryy, sorry I missed this. Its usually better to open a new thread (and perhaps mention the closed one). I have reopened it (sorry to people we are spamming!) !

I am not sure exactly what the situation is on Windows. My guess is it relates to one of -

* An old version of openssl dll. Github is (quite rightly) sensitive about which version of openssl you are using. Can you tell me what version of OpenSSL you have there please ? 
* tomboy-ng not able to find your installed openssl.  Thats possibly the most common problem on Windows where you can have a system wide install of openssl or just have individual DDLs alongside individual applications.
* An older tomboy-ng ?  Early versions of tomboy-ng used early openssl protocols, ones that, as in point 1, are not supported anymore because they are unsafe.

We can find out just what is happening if we can get some logs.  On Windows thats a touch harder because the command line is not quite as useful. Right down the bottom of https://github.com/tomboy-notes/tomboy-ng/wiki/Bugs-and-Known-Issues there is a section about collecting debug info for windows, please have a look. IMPORTANT, the instructions, in your case, should say to run -

`"C:\Program Files\tomboy-ng\tomboy-ng.exe" --debug-sync --debug-log=%userprofile%\Desktop\tomboy-log.txt`

Rather than --debug-index.  I understand this sounds like a messy process, please get back to me if you have any problem at all.

Do have a look through the log file before posting it, just to make sure nothing you don't want to make public.

I am quite sure we can solve this problem.

Davo

**Comment by vryy** [comment]
@davidbannon thanks for taking a look on this. This is the [log](https://github.com/user-attachments/files/18738466/tomboy-log.txt) file that I got on my system. You are mentioning that tomboy links to openssl dll, but from the dependency trace I have not seen any (see image below). It's possible that OpenSSL shipped with 10.0.19045 is quite old. Can you suggest a name of a good openssl dll, then I could just copy to the installation folder to prove this hypothesis ?

Moving forward, it could be wise to ship tomboy-ng with its own openssl, at least on Windows, to prevent any linking issue.

![image](https://github.com/user-attachments/assets/35dbcbfd-fa98-479c-8aae-ab021685f53b)
