### ISSUE TITLE
0.36a1-1: search interface completely broken

### ISSUE THREAD

**Issue by gabrielepigozzo** [tomboy-notes/tomboy-ng#292]
xubuntu 22.10
tomboy-ng      0.36a1-1

![screenshot-20230407151706](https://user-images.githubusercontent.com/8372492/230615916-9221df5b-4989-48ab-b790-a643545f1104.png)

Previous version 0.35-2 was ok.

**Comment by gabrielepigozzo** [comment]
tomboy-ng-qt5  0.36a-1 is broken as well.

![screenshot-20230407160733](https://user-images.githubusercontent.com/8372492/230622783-55fe30a2-b255-4611-904f-893c83bb1852.png)

**Comment by aguador** [comment]
But I see no 0.36a1, and the packages with 0.36a-1 are all rpm packages. What package have you downloaded and installed?

**Comment by gabrielepigozzo** [comment]
I used the PPA repository:
deb https://ppa.launchpadcontent.net/d-bannon/ppa-tomboy-ng/ubuntu/ kinetic
main
--
Gabriele Pigozzo

**Comment by davidbannon** [comment]
Gabriele, you sure get the prize for the Bug of the Month !

I have no idea whats happening here. I have just built a U22.04 XFCe VM and the tomboy-ng from the PPA, works perfectly. I guess its some interaction with, maybe, your display theme ? What theme are you using, can you please try some default XFCE theme and see if its related ?  

Hmm, and you get the same result with QT ?  This is crazy.

What screen resolution are you running ?  I will set to same. Do you have anything else running that I should try ?

Are the other tomboy-ng screens behaving normally ?

[Wild question warning] My XFCe seems to autostart Magus, a screen magnifier, you are not looking through that are you ?  

(Sorry, I am blasting questions because I really don't know what to ask!)

[tomboy-ng_0.36.zip](https://github.com/tomboy-notes/tomboy-ng/files/11182247/tomboy-ng_0.36.zip)
I also have here a 0.36 deb (no 'a'), it was only released on Debian for bookworm and does not have some changes made to dark theme colours, mainly affecting Qt5. I have attached that as a zipped deb to try if you like, it may help us to narrow down whats happening here. You will need to remove the existing tomboy-ng because this one has an earlier version number, your notes will remain in place.

For reference, 0.36a1 is exactly the same as 0.36a, I had to add the '1' to get past a launchpad issue for the gtk2 PPA release. 

Very sorry about this  Gabriele

Davo

**Comment by davidbannon** [comment]
I think what we are seeing here is the Menu, Clear and Options buttons deciding to be huge.  I look at the code and can see absolutely no reason for it .....
Davo

**Comment by davidbannon** [comment]
Hmm, maybe I have spotted it. Those three controls are bottom anchored to the Tedit search control, it has bottom anchoring enabled but not set to anything. I have done the same time a 1000 times and never seen it cause a problem, indeed, all controls and initially set like that.  But it could explain what Gabriele is seeing. Perhaps.

Gabriele, attached is a zipped up binary with the above addressed. Please unzip and just run from your desktop and see if it makes a difference (make sure you have closed your existing tomboy-ng down first).  If this solves your problem, well, thats a bit confronting for me but you could put it in place of /usr/bin/tomboy-ng.

(You may need to mark the binary executable, not sure if zip changes that or not. Github will not let me attach a tarball).

Davo
[tomboy-ng.zip](https://github.com/tomboy-notes/tomboy-ng/files/11182719/tomboy-ng.zip)

**Comment by gabrielepigozzo** [comment]
Hi Davo,
thank you for your time.
I tried the zip file and the problem seems to be fixed.
I'm using i3 as windows manager and my resolution is 3840x1600.

Regards.
--
Gabriele Pigozzo

**Comment by davidbannon** [comment]
Hmm, further research is indicated ......

Davo

**Comment by davidbannon** [comment]
Gabriele, further digging and asking around has not really given me a reliable answer about this problem. I have tidied up the one issue I thought might cause it but the FPC/Lazarus experts do not seem convinced, but they can offer no other explanation either !

I have pushed a changed version up to the PPA, you will probably get it next time your system does an update. Additionally, it has a few other small fixes that did not make it into 0.36a. (0.36a was a mad rush to get in before Debian closed the door on bookworm.). You might notice larger notes opening a little faster for example.

If the problem comes back with the new version (0.36b) PLEASE let me know, I will have to try a lot harder to find just what is going on. Because of the way Launchpad works, I am currently locked into using an older version of Lazarus to build for there. But, honestly, I don't believe its that either ....

Thanks for your help.

Davo

**Comment by aguador** [comment]
My apologies for the noise. Since I do not use *buntus, I forgot about that you produce packages for the PPA.

**Comment by gabrielepigozzo** [comment]
Hi,
I've just installed version 0.36b-1 from PPA repo and it works fine.
Thank you!

Regards.
--
Gabriele Pigozzo

**Comment by davidbannon** [comment]
Sounds like this matter is under control. Sounds like same problem as #297. I have no idea why its cropped up now with code that has been like that for a long time. Anyway, Davo, don't tie components to other components that are, themselves, not tied to something.
Closing ....
