### ISSUE TITLE
Debian testing:  Version 0.36a-2 Wrong layout

### ISSUE THREAD

**Issue by kanehekili** [tomboy-notes/tomboy-ng#303]
As mentioned before, layout management is broken on Debian testing:
![tomboy1](https://github.com/tomboy-notes/tomboy-ng/assets/4390452/6b77a49a-2853-413e-98a2-f92435cfb391)

Dark theme is not supported correctly:
![tomboy2](https://github.com/tomboy-notes/tomboy-ng/assets/4390452/bdd0ddc4-b895-445e-a1d3-f6c418471dd3)

Distributor ID:	Debian
Description:	Debian GNU/Linux trixie/sid
Release:	n/a
Codename:	trixie

**Comment by davidbannon** [comment]
Hi [kanehekili](https://github.com/kanehekili), I cannot find your last bug report on this issue but I do remember it. 
From memory, I was unable to reproduce this problem but 'believe' that its cause by some "dangling component anchors". While I socialized the idea on the Lazarus forum, because no one could reproduce it, its an open question I am afraid.

I have addressed the issue in subsequent beta releases and am about to release 0.37, its more or less done, just waiting on translations. If you are feeling brave, I sure would be interested to hear if you can reproduce this pretty horrible problem using the 0.36h packages I have at https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.36g

(tagged on the release page as 0.36g but are actually 0.36h).

David

**Comment by kanehekili** [comment]
Hi David,
just install a debian testing and install tomboy_ng. Very easy to reproduce. I'm still using your intermediate version from 23/3/11 (QT5) which works more or less without problems. I just wanted to inform you about it. Closing it, since you are aware..
