### ISSUE TITLE
BullXXXXet ??

### ISSUE THREAD

**Issue by salamander2** [tomboy-notes/tomboy-ng#304]
I just downloaded https://github.com/tomboy-notes/tomboy-ng/releases/download/v0.36c/tomboy-ng_0.36c-0_amd64.deb 
Under the text-formatting options,  the option for ALT+  (bullet right) has text "BullXXXXet+"

I assume this is some testing code.

**Comment by davidbannon** [comment]
I have absolutely no idea why that is there and I shudder to think how long it has been like that !  (I always use the keyboard shortcut so probably have not looked it it for a long time. Thats the trouble with testing your own code. 

Considering the number of people who must have seen it.....

Thanks you for bringing it up, I'll fix in the pre-release shortly and that release will be out and about pretty soon.

Hmm, and unposted message from several weeks ago above, sorry !

OK, this issue fixed in https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release

So closing this issue, thanks for your report.

Davo
