### ISSUE TITLE
RPM Binary missing

### ISSUE THREAD

**Issue by gpshumway** [tomboy-notes/tomboy-ng#306]
Greetings.  Thanks so much for your continued maintenance of Tomboy.

I'm trying to install a new instance of Tomboy-ng in Fedora, but the link on the Download Release wiki page gives a 404 page not found error.  The file it supposedly points to is:
`https://github.com/tomboy-notes/tomboy-ng/releases/download/v0.36c/tomboy-ng-0.36c-2.x86_64.rpm`

Before I go down the bash script for deb->rpm or build from source roads, I thought I'd just ask for an rpm.  

Thanks!

**Comment by davidbannon** [comment]
Thats messy gpshumway, very sorry. Looks like I fixed a packaging issue a couple of weeks ago and forgot to update the Fedora part of that download page. Very sorry, all fixed now.

You might like to consider the current pre-release. You would want https://github.com/tomboy-notes/tomboy-ng/releases/download/v0.36g/tomboy-ng-0.36h-1.x86_64.rpm

Still has a few things to solve wrt packaging but probably a lot better product than 0.36c right now.

Davo

**Comment by gpshumway** [comment]
Thank you very much!

Fast and friendly service from my local open source developer. :-)

-Bernie Nelson (aka Gordon Shumway)

**Comment by davidbannon** [comment]
We aim to please.  :-)

I'll close this now, its all done, too easy !

**Comment by gpshumway** [comment]
Thanks again for the prompt service, Dave.

I'm afraid I've got another problem.

I stupidly did my backup for my Fedora 39 upgrade by exporting my notes to HTML in Tomboy. I don't know why I did that, in the past I've been smart enough to copy the directory.

I found SupraLance's [issue](https://github.com/tomboy-notes/tomboy/issues/104) on the Tomboy-ng Github and tried to follow the workflow using aconvert.com, but I'm having issues.

I don't see a way either with Tomboy-ng or with TomboyTools to import an RTF file. How was it that you resolved his issue? Any better way since 2018?

Thanks again, I really appreciate it.

-Bernie

**Comment by davidbannon** [comment]
A discussion rather than an answer I am afraid.

OK, we sure do have a problem here I am afraid.  TomboyTools does not import HTML, it could be made to do so but with a fair bit of work. You see, I could not make a generic HTML importer, just one to handle tomboy-ng's exported notes. So, not widely useful. And time would be a problem, almost certainly not before Christmas.

So, some questions -
You were not using Sync in any form before your upgrade ?
When installing F39, you allowed it to format the /home partition ?
No other backups ?

I ask the latter because, by default, tomboy-ng makes regular auto archives, one of those might appear in your backups ?

Next, using SupraLance's online converter ?  I'd hate to see my notes go through a public service like that. But maybe it does do a reasonable job of converting to RTF ?  I don't really know, RTF as a standard is pretty diverse, again, the converted notes that aconvert make may contain rtf that we cannot import. But perhaps worth a try. I can pretty easily make a little add on that will turn a directory full of rtf files into notes. 

Another approach might be a lot quicker, private and sort of OK.  Did you export your notes using tomboy-ng or Tomboy ?   SupraLance used Tomboy and that produced some pretty complicated CSS code. The html  that tomboy-ng makes is reasonably clean html. I could make you a filter that strips out that simple HTML and converts your notes to plain text. tomboy-ng will happily import plain text. 

Obviously, you will loose all the markup but hopefully no content. I think ....

Thoughts ?

Davo

**Comment by gpshumway** [comment]
Thanks so much for your reply, Dave. To answer your questions:

- I was not using any form of sync (I've never had any luck making it work)
- It was a clean install of Fedora 39, so the whole drive was wiped.
- I have some older backups, but some of my notes are continuously updated, so it would be messy.
- I was using Tomboy, not Tomboy-ng. I'm afraid I just took what was in the Fedora repositories. Thusly, my HTML files are likely the CSS heavy versions produced by Tomboy.

I know what you mean about sending my notes through a public converter, but it's the best option I've seen so far. The old issue thread seemed to indicate SupraLance was successful. My tests indicate aconverter does a better job of formatting HTML files than LibreOffice, which is what I've got locally.

Honestly, the final format I'm looking for is markdown. I think I'm moving to a Nextcloud based solution for notes and that's Nextcloud Notes' format. Any ideas on converting html to markdown? A test export from Tomboy-ng seemed to work just great.

Thanks again for all your help, I really appreciate it.
-Bernie

**Comment by davidbannon** [comment]
Hmm, thats all bad news I am afraid. I vaguely remember looking at Tomboy exported html and shaking my head sadly.  It does sound like using aconvert, get one complicated one turned into  RTF and send it to me and I will try to pull it into a KMemo. That will tell us your chances of making tomboy notes from them again. If it looks interesting, then I can make you a simple tool to bring them in as that way, one at a time (?) how many notes do you have ?

Important, make sure that one you send me is publicly viewable !

Once in tomboy-ng, you can export as MarkDown. One at a time or in bulk with tomboytools.

I was at one stage looking at syncing through NextCloud but they did not quite understand the risks of bad timekeeping with sync and I quickly saw the sort of problems we used to have with Tomboy Sync, especially with Rainy. So, I backed away, Still have a lot of code I prepared for it but would not ship it my worst enemy !

Davo

**Comment by gpshumway** [comment]
Update:

I used Firefox to save the Outback Suspension HTML note as plain text, then changed the extension to ".md" and imported it into NextCloud. The result is formatted acceptably. I use colons frequently and Nextcloud seems to think they're emojis, but I can live with that.

Now if only there were a way to batch it...

I found this-
https://github.com/abiyani/automate-save-page-as

A bit old and doesn't seem to have a parameter to save as plain text..

Keeping on...

-Bernie
