### ISSUE TITLE
Special characters in headline confuse the program

### ISSUE THREAD

**Issue by tobi150403** [tomboy-notes/tomboy-ng#308]
Hello, I've come across an odd problem while using tomboy on my windows pc in german language: whenever I type a german special character like ö ä ü in an hyperlink, the program gets confused. If my hyperlink headline is "Pädagogik", it shows "Pädagogikik" the next time I open my notes, with the hyperlink still being avalible. After next restart, it says "Pädagogikikik" and I cant klick the hyperlink anymore. deleting the extra "ik" parts helps, but just until I restart the program, where it adds them again. If I just type "Paedagogik" for the headline, it doesnt get confused anymore, but it stops me from linking back to the note when I type "Pädagogik" in any other note, which is the main reason im using the program. I already tried the special characters button at the top of a note, but it didnt seem to help. Anyone with tipps and tricks to work around that? Thanks! Greetings, Tobi

**Comment by davidbannon** [comment]
Oh, looks like i have let a utf8 incompatability slip in. it did, in the past, handle utf8 char there fine but I have done a number of speed ups in the code that scans for links and apparently (?) not tested for utf8. My bad error I am afraid.

It will be fixed I assure you. Sorry!  I will let you know when and you can download a fixed version.

Davo

**Comment by tobi150403** [comment]
Hello Davo, thanks for your fast answer! Love that. One Last little thing I experienced: when I have a note named "mercedes", and in another Note I type "while driving the mercedes, the car..." it detects the word and refers back to my old mercedes note. So far so good, but if I type "while driving my car (mercedes),..." it doesnt detect the word, only If I leave a space between the word and the brackets. Same Problem when I have the word in quotation marks or next to a /slash. Dots dont cause problems as far as I know. Is that a problem on my side I can fix on my own or is that also a code thing? Greetings, Tobi

**Comment by davidbannon** [comment]
Yes tobi, that is intentional, we define a link as being surrounded by a space, comma, period or newline. Its the way it was done in the original Tomboy and if I changed that, all hell would break loose.

Have fixed your utf8 char issue, need address a few other things and give it all a good test and I will slip out a new beta release. Hopefully not long.

Davo

**Comment by tobi150403** [comment]
Alright, thank you very much!

Davo ***@***.***> schrieb am Sa., 13. Jan. 2024, 12:43:

**Comment by davidbannon** [comment]
tobi, if you like, you can grab a package from https://github.com/tomboy-notes/tomboy-ng/releases/tag/v0.38a (if your desired package its there, linux and Intel only at present).

Its identical to the code I just sent Debian as v0.39 and will be released here as 0.39 in a day or so. Because of the diversity of packages I publish, takes me a while to get them all together.

I suggest this because there is a very real possibility of a note becoming corrupted with the bug I left in there and I really don't want that to happen !

Davo

**Comment by davidbannon** [comment]
OK, this (bad) problem fixed in https://github.com/tomboy-notes/tomboy-ng/wiki/Download_Release

So closing this issue, thanks for your report.

Davo
