### ISSUE TITLE
Request:  64-bit MacOS release

### ISSUE THREAD

**Issue by sunjam** [tomboy-notes/tomboy-ng#32]
Requesting a 64-bit MacOS release as only 32-bit is available.  Thanks.

**Comment by davidbannon** [comment]
Thanks Sunjam. I'd be interested to know if tomboy-ng is causing you any issues at present because its only 32bit ?
64bit on the Mac is quite a long answer I'm afraid.
**Background**
At present tomboy-ng on the Mac is based on the Carbon widget set, Apple deliberately limit Carbon to 32bit apps. The alternative is the Cocoa widgetset but it is not as advanced as Carbon. 
MacOSX in the current release and the next release will support 32bit Carbon fine, however, Apple has sent some signals that the release beyond that may not do 32bit apps. And presumably, won't support Carbon either.
From time to time I test tomboy-ng against Cocoa ensuring it, at least compiles cleanly. However there are some issues at present. The 'development' version of lazarus is, obviously, where Cocoa is being improved and from what I have seen, good progress is being made. But I don't necessarily want to use the development version of Lazarus !
One difficulty I have is I don't want the three different platform versions of tomboy-ng drifting apart. So I want to be able to build tomboy-ng on exactly the same version of Lazarus, right now that v1.8. But to use Cocoa on the Mac means using the development version ....
**Build your own from source**
As I said, I do test tomboy-ng against Cocoa from time to time, Lazarus itself takes care of switching between widgetsets so building under Cocoa is easy. Its most certainly going to be a better product if you use the development version of LCL and possibly even RTL. So that means you need to install a set of libraries, LCL and RTL built from development version of Lazarus. Lazarus itself should be fine using just the 1.8 release.
If you want some help doing so, just ask.

**Comment by davidbannon** [comment]
Not much going to happen here in the immediate future. We certainly will have a 64bit Cocoa based app when the Lazarus-Cocoa LCL is ready. In the mean time, the 32bit version works as well on Mac as tomboy-ng works elsewhere so lets close this ticket.
