### ISSUE TITLE
Search is unexpectedly treating multiple words as "exact string" matches

### ISSUE THREAD

**Issue by mlncn** [tomboy-notes/tomboy-ng#37]
When i type:

exact string

in the search box and press enter, i expect to find the note with the text "exactly this string".

That's a silly example; where i use this all the time is typing Firstname City to find someone whose last name i don't quite remember, or a million other cases where i need to find a note that contains two or more non-contiguous words.

(Still testing version 0.12 and my frame of reference is still the Tomboy available in Debian repositories.)

Related to #34

**Comment by davidbannon** [comment]
Well, a wildcard search is certainly possible but much, much slower.In your example, we'd need to pick up a, perhaps, a 50K note that starts with "exact" and ends with "string". And every combination between. 
Might be appropriate to provide an "Advanced Search" that lets you do things like that I'd not do it to the standard search function as I suspect it would make it unusable.

David

**Comment by mlncn** [comment]
As per #34, i think search just has to use an index.  Searching for non-contiguous words has been the default when not using quotation marks since Alta Vista and continues in things like Spotlight on Mac.  And again, case-insensitive and search for all words (without requiring them to be exactly next to each other) is both how old Tomboy works (with survivable performance even with my ... now 16,791 notes) and how modern applications work.  Completely offload the work to a proper indexed search and things can fly!

I'd still recommend case-insensitive search which assumes independent words and not a phrase even if it made it completely unusable at my scale.  Usability first, and then scale.

**Comment by davidbannon** [comment]
Hmm, Tomboy does not do wildcard search, it just looks for notes that contain both the words mentioned. In either order. So, search term "exact string" will register a hit in a note that says "..and the string is exactly..". Thats relatively easy to implement but will probably require a bit of rework of the search unit.
And indexes ?  An index is useful if you have a subset of the content indexed. But if you want to index free form text then your index ends up being substantially bigger than the text. There is some saving by not indexing generic words such as "and; but...". And some benefit in a on disk index because it can be searched faster than the note but the maintenance cost has to be considered. 

The meta data structures I currently keep in memory are, sort of indexes. But only index metadata. If memory footprint did not matter we could do all sorts of things .....

**Comment by davidbannon** [comment]
OK, I have checked in code that allows user to search on the exact combination in the edit box OR find notes that contain all the words but not necessarily in that order.
This check-in also fixes a significant problem in the search tools but at the expense of performance. Further research is indicated.

**Comment by davidbannon** [comment]
Just checked in code that speeds up that search by factor of 100, now searches my test note directory of a 100 notes in about 35mS on my 'medium' speed laptop.
