### ISSUE TITLE
Offer AppImage or flatpak releases

### ISSUE THREAD

**Issue by drsh0** [tomboy-notes/tomboy-ng#42]
I understand deb and the gz files are included. However, an appimage or flatpak could be quite useful for those who want to try `tomboy-ng` and work regardless of which platform they are on. Alternatively. what are your thoughts on this being offered/packaged in the AUR?

Thanks!

**Comment by davidbannon** [comment]
Honestly, I have never worked with Flatpak or the similar ideas out there. I have on my list to make a RPM simply because I understand that idea. 

So, any help in making better distribution files would be very gratefully received !

Right now, I make raw 32bit and 64bit binaries that, generally, have dependancies most Gnome based linux users already have installed. I can, I believe make QT4 or QT5 binaries just as easily.  I am totally unsure of how far back in that process we'd need to go to make eg Flatpak.

Lets hear your ideas.

David

**Comment by davidbannon** [comment]
Now provide a RPM. I don't think the container approach is appropriate as tomboy-ng needs to be able to access systemtray and pop up quickly and easily when user wants it.

Will consider do native install packages for any specific platform that a user requests.
