### ISSUE TITLE
Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by luiandresgonzalez** [tomboy-notes/tomboy-ng#45]
I've installed tomboy-ng through the .deb file in an "almost fresh" Ubuntu 18.04. Installation didn't showed any errors but when run from the launcher it doesnt show any new window. Running it from the terminal shows the following error:
```
~$ tomboy-ng
Gtk-Message: 19:25:41.263: Failed to load module "canberra-gtk-module"
```

**Comment by davidbannon** [comment]
Wow, I have never even heard of canberra-gtk-module.
I googled for it and seems there can be an issue if you have some 32bit software running on a 64bit machine.
Any chance you downloaded the 32bit version of tomboy-ng and are using a 64bit system ?

Mr Google suggests also installing the 32bit library but I'd rather see you using the 64bit tomboy-ng if that is the issue.

Worth noting that tomboy-ng has not been tested on 18.04 yet but I'd be very surprised if there is a comparability issue.....

Davo

**Comment by luiandresgonzalez** [comment]
Hi David, I'm positive I installed and ran tomboy-ng_0.14-0_amd64.deb from this github. I already reinstalled it by `apt purge tomboy-ng` and reinstalling it and it shows the same error. 
Further testing the some install issues, I deleted the config files from my home dir and the program started with it's initial setup dialog. I set up a directory outside the home folder and the following error apears:

`luis@lambda:~$ tomboy-ng 
Gtk-Message: 13:56:09.661: Failed to load module "canberra-gtk-module"
ERROR - File not found, cant read note change date for /mnt/sda5/Dropbox/Tomboy-ng Notes/0/116/ba80cc10-dc32-4937-b17e-677e39bd3b8c.note
.
.
. <lots of other files, but same error>
`
I also tried using the default location for notes but still no window appeared other than that named KTomboy-NG Settings.

**Comment by davidbannon** [comment]
just a wild guess here ...
You say no window appears ?  Normally tomboy-ng does not show a window until you open a note, it keeps out of your way. Can you see the small system tray icon, bright green, probably top right of your screen ?
You interact with tomboy-ng all through that system tray icon.
The error you are seeing now (about missing files) somehow relates to you deleting the config files. I am wondering if you did that while tomboy-ng is still running ....
David

**Comment by davidbannon** [comment]
A little research, libcanberra seems to be there to play some sound effects, tomboy-ng does not make any sounds (afaik).  And ldd tells me that tomboy-ng does not call libcanberra itself in any way. Perhaps it calls another GTK library that, iin turns calls libcanberra ?   I have no idea why.
That being the case, if it does not cause tomboy-ng to crash (as seems to be the case?) you can safely ignore it.
The real issue is "is tomboy-ng actually running" and I suspect that may relate to you expecting to see a window pop up ?  My fault for not uploading any appropriate images of tomboy-ng running. Sorry !

Please look for that green system tray icon.....
Davo

**Comment by luiandresgonzalez** [comment]
Hi, David, 
If your refer to an app indicator on the upper right corner on GNOME, there is none while tomboy-ng running. I am familiar with that icon since I am very accustome to the tomboy "classic"(?) icon. About libcanberra, this might indicate it is just a warning and not necessarily an error that might cause it not to run? I remember in some distros there was a similar problem with Dropbox indicator icon not appearing on some dark themes (which I am using adwaita-dark), requiring to change the running environment or something like that.

**Comment by luiandresgonzalez** [comment]
Hi, David, 
If your refer to an app indicator on the upper right corner on GNOME, there is none while tomboy-ng running. I am familiar with that icon since I am very accustome to the tomboy "classic"(?) icon. About libcanberra, this might indicate it is just a warning and not necessarily an error that might cause it not to run? I remember in some distros there was a similar problem with Dropbox indicator icon not appearing on some dark themes (which I am using adwaita-dark), requiring to change the running environment or something like that.

**Comment by davidbannon** [comment]
And to further complicate, I am about to release v0.15 which has a substantially different startup model. Not because I was having trouble on Linux, because of a need to transition from 32bit t 64bit on the Mac, Cocoa required some changes. 
So, I need to do a lot of 'other' platform testing.

Davo

**Comment by davidbannon** [comment]
**OK, so forget all I have written above.** 

The underlying issue is that Ubuntu seems to have now removed all support for the System Tray. In 17.10 it did work but not as I have been describing, I only remembered when I fired up a Gnome3 VM. Sigh. In previous versions of Gnome3 you could access a System Tray by moving your mouse down into the lower left hand corner of the screen. But not in U18.04 / Gnome 3.28 !

There is a Gnome Extension designed to put the System Tray back were it belongs, top Right but apparently it too is having problems with 3.28 - not a good sign.
https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/127

I am not sure what all this means, I do have a solution to a similar solution under Mac's Cocoa but really don't like it, and am not sure I want to use it on Linux. So, until I have done a lot more research, I think I'll have to say that tomboy-ng does not work with any Gnome 3 based system.

I continue to use Ubuntu Mate and, of course, that works fine.

**Comment by davidbannon** [comment]
OK, I have a temp and very ugly workaround in mind, but first a summary of the situation.
System Tray is not the same thing as AppIndicator, might look similar but quite different underneath. Gnome3, for whatever reason, does not want to support the System Tray preferring the dumbed down AppIndicator.  Linux distros using Gnome3 have had various 'extensions' built in or added later to make apps using SystemTray work. Since Gnome3.28 thats got harder and apparently none of the fixes currently work. Some abandoned.
https://github.com/wincinderith/topicons
https://github.com/mjnaderi/TopTray
https://github.com/phocean/TopIcons-plus
https://github.com/laike9m/topIcons

My plan, as a temp measure until things become clearer is to turn on some code I have already written for Mac's Cocoa using either command line switches or, if possible, env vars.
The result will be an ugly and inconvenient interface for Gnome3 users. Instead of an always visible SystemTray icon, you will need to click on the tomboy-ng icon on the (whats its called?) dock or plank or toolbar to the left to bring a small tomboy-ng window into focus and then choose what you want to do from its menus.

Maybe, long term, Ubuntu (and others) will fix their Gnome3 extensions, maybe Lazarus will alter its SystemTray component to target the AppIndicator model, maybe Gnome3 user will decide they like the little window model (I doubt it).

Version 0.15 was nearly ready for release, I'll now need to incorporate these changes (easy) and test, should, if all goes well, be a week.

**Comment by davidbannon** [comment]
> What I don't understand about this is that the "regular" tomboy worked with its indicator

Oh, indeed ?  That surprises and somewhat confronts me ! Apparently, most SystemTray apps don't work. The original Tomboy must have some concessions to the AppIndicator model, thats good.

If you are interested, here is a link (for a few days only) to my fairly untested v0.15 for linux64. Start it from command line and add either -g or --gnome3 
 
https://drive.google.com/file/d/14D1TwGu77KCVjB6GYI-K7FbFjcLBSgUb/view?usp=drivesdk

You can operate tomboy-ng from the menus on the little window you see or by clicking anywhere in that window.

And, yep, I still see warning about libcanberra.

And, by the way, if you can still get real Tomboy running and only use Linux, well, don't expect -ng to be better !
Davo

**Comment by davidbannon** [comment]
Woops, did not intend to close this issue just yet.

**Comment by davidbannon** [comment]
Woops, did not intend to close this issue just yet.
(stop it Github you are guessing !)

**Comment by davidbannon** [comment]
sigh....

**Comment by davidbannon** [comment]
OK, here is the solution. You need to install **gnome-tweak-tool** (probably should have it anyway) and a particular gnome shell extension, '**topicons**' (which Ubuntu should have rather than their own version that mostly fails).

In the Ubuntu Software application, search for "gnome shell extensions topicon", install it. 

Then fire up Activities and search for gnome-tweak-tool, if you don't have it already, it will help you install it. Start it up. Click extensions, turn off the "Ubuntu Application Indicators", turn on "TopIcons" and exit.

Stop tomboy-ng, restart it without the command line switches and if you see the green icon top right, all is good. And in less time than it would take to install Ubuntu Mate (but I still prefer Mate).

Trouble Shooting notes -
1. I tested this with Topicon, not Topicon Plus.
2. Some people seem to indicate you need to restart - wow, just like Win95 ! (I did not need a restart but a bit of nostalgia does no harm)
3. While testing, make sure you don't dismiss the tomboy-ng startup window until you can see the green tomboy-ng icon on the Application Indicator panel, top right. Otherwise, you will loose sight of tomboy-ng and have to resort to killing the process manually. Sigh....
4. Gee, that icon does not look good there does it ? But at least its there and works.

**Comment by davidbannon** [comment]
Refs -
https://askubuntu.com/questions/1030833/app-indicator-not-working-on-ubuntu-18-04
https://extensions.gnome.org/extension/495/topicons/
https://askubuntu.com/questions/75530/how-do-i-install-and-manage-gnome-shell-extensions

**Comment by davidbannon** [comment]
Just a progress report on this issue.
I have had a patch accepted in Lazarus's LCL that fixes this issue on Ubuntu type distros and any other that include support for the "Unity System Tray" model. If you build from source, using Lazarus 1.8x, apply the patch in the kits patches directory (ensuring you have write permission to the relevant files). If you use Lazarus trunk, no need.
The non Ubuntu like distros that follow Gnomes strict model and are using Gnome 3.28 still don't work in the system tray mode and therefore must be started with the --gnome3 switch.
I don't consider this solved yet.

**Comment by davidbannon** [comment]
tomboy-ng now works seamlessly on Ubuntu and its derivatives. 
Other Linux flavours based on Gnome 3.28 are usable if the startup window is allowed to remain in place (it forced to stay with --gnome3 switch). Or it works seamlessly if the TopIcons Gnome Extension is installed.
Not the end of this issue but will have to do unless I get some feedback from users that this is unsatisfactory.
