### ISSUE TITLE
Crash while trying to sync notes using local folder on an external hard drive

### ISSUE THREAD

**Issue by erik-brangs** [tomboy-notes/tomboy-ng#46]
Hi,

I was using the plain Tomboy Notes on Debian to synchronise Notes between Windows and Linux using an external hard drive. In the last few days, synchronization on Linux broke for some reason (synchronization on Windows does not crash). I tried Tomboy Notes, gnote and tomboy-ng:
- tomboy-ng crashes
- Tomboy Notes just seems to hang up
- gnote prints some stuff about extra characters after the end of notes and then crashes

The stack trace for tomboy-ng is

    TApplication.HandleException Access violation
      Stack trace:
      $000000000065D33A
      $000000000051356A
      $0000000000513DB3
      $0000000000513456
      $00000000004211EF
      $00000000004BEC7D
      $00000000005E5812
      $00000000005F1ED1
    WARNING: TButton.Destroy with LCLRefCount>0. Hint: Maybe the component is processing an event?
    WARNING: TButton.Destroy with LCLRefCount>0. Hint: Maybe the component is processing an event?

**Comment by davidbannon** [comment]
Hi Erik, thanks for the report.

Most of that stack trace you have sent is about LCL components complaining about exiting before cleanup so have happened after the problem.

My guess is you have a corrupted note and, to my chagrin, tomboy-ng is not reporting it correctly ! If you can work out which note you can have a look at it. Otherwise, best idea would be for me to make a special binary (I'm guessing you don't have Lazarus installed) with a lot more debugging turned on.

I assume you have the latest tomboy-ng ? v0.15 ?  I have a bit more error reporting in there, however, I expect in the event of a crash, you won't see it. Sigh ...

A possible test might be to open each note, one by one and see if one of them fails, again, some error reporting will appear in the Search form. If you can find the offending note, look at the xml (if you can). If the note itself does not have any sensitive info, I'd love to see it so please keep a safe copy before trying to fix it.

Of course, if the corrupted note is in the sync repo rather than the local note directory, thats harder....

tomboy-ng is 'designed' to recover from a sync problem by starting from scratch but I strongly advise against that until we have no choice. Tomboy is a bit inclined to double up on notes doing that too I'm afraid.

David

**Comment by erik-brangs** [comment]
I don't know how to find the problematic note and I've got about 2000 notes. Therefore, I'd prefer the binary. 

I tried throwing away the local directory and sync from the folder but it also crashed. So I suppose the problematic note is in the sync folder.

I'm not sure about Lazarus. I installed the 0.15 amd64 Debian package from the releases page.

**Comment by erik-brangs** [comment]
I sent you an e-mail with the information a while back. You should have received it by now unless it was caught by some spam filter.

**Comment by davidbannon** [comment]
(an off line discussion ensured).
 Fixed in current head and will be fixed in release v0.16
Thanks for the report and subsequent testing.
