### ISSUE TITLE
Access Violation on macOS

### ISSUE THREAD

**Issue by benjbrandall** [tomboy-notes/tomboy-ng#48]
![image](https://user-images.githubusercontent.com/15836153/41035930-eee24d06-6996-11e8-9a14-b58c68915a17.png)

This occurred when I tried to make a new note, and when the required points — not ones marked optional — on the config popup were already green. I realize why the error occurred (I hadn't hit 'Save Config') but the error message wasn't very descriptive and it was difficult to figure out.

V 0.15

**Comment by davidbannon** [comment]
Hmm, think I respond to this via email and did not realise that it was a github issue. And maybe my email did not go for the same reason.
Anyway, I am pretty sure this problem here was addressed (if not solved) by commits made to deal with #46.
Some recent changes to startup model (to deal with Cocoa) had left the possibility open for a user to eg create a note before saving an initial config. While tomboy-ng can run fine without a config file, it now has a dependency on the config directory. And it makes that directory when it writes its first config file :-)

The current source now creates that directory and a default config file at first startup. So, I believe this problem should not be reproducible.

**Comment by davidbannon** [comment]
This is same issue as #46. Fixed in current head and will be fixed in release v0.16
Thanks for the report and subsequent testing.
