### ISSUE TITLE
Notes opened in Single Note Mode are uneditable (macOS)

### ISSUE THREAD

**Issue by benjbrandall** [tomboy-notes/tomboy-ng#60]
A note opened with `./tomboy-ng -o Notes.txt` on macOS doesn't respond when edited, or focus when the window is clicked:

![singlenote osx](https://user-images.githubusercontent.com/15836153/42075645-837da52e-7b7a-11e8-98ac-bae72ad3bb58.gif)

Upon killing the process, I see: `TCarbonButton.SetFocus Error: SetKeyboardFocus  failed with result -30585` which seems relevant.

EDIT: Same when running any ./tomboy-ng in macOS, doesn't matter if it's with a -o.

**Comment by benjbrandall** [comment]
Although I get the same `TCarbonButton.SetFocus Error: SetKeyboardFocus  failed with result -30585` when I just do `./tomboy-ng`, everything works anyway as long as it's not single note mode.

**Comment by davidbannon** [comment]
Ben, I think the secret is how you open the app. Don't open the tomboy-ng binary itself, you need to open the app file/dir.

something like -
open tomboy-ng.app -o text.txt <enter>

Davo

**Comment by davidbannon** [comment]
Its more of a Mac thing than a tomboy-ng/lazarus thing. Issue being of course, few Mac users launch from the command line.....

**Comment by davidbannon** [comment]
I agree its confusing but its really a platform issue rather than a tomboy-ng thing.
On a (debian based) Linux, iff you install the deb package then the binary is installed in /usr/local/bin and your default config would have a path to that. If you type "tomboy-ng -o somefile" and don't go into singlenotemode, its likely you have another, older copy of tomboy-ng in your path ahead of the one you think you are calling.
which tomboy-ng <enter>
whereis tomboy-ng <enter>

On Windows and Mac, fewer users launch from the command line and would be more interested in associating files of type *.note with the binary and would, and could, set a full path to it in their GUI file manager.
Windows specifically, we really need to make a proper installer, the tools are there, its just I have not "got around to it". It would put the binary in the right place, set a path to it and possibly (shudder) put the right things in the Registory. Wow, danger will Roberson, danger !
On the mac, if a user installs the dmg in the normal way, that is, opens the dmg, drags the app file over to the Applications directory shortcut, it should all work. However, I have tested that on exactly one 2012 Mac Powerbook running Sierra. I hope it does, in fact, work that way !  Anyway, on the Mac, thats how its done, you distribute the app file (ie tomboy-ng.app), its actually a directory that includes the binary, some config stuff and any other needed file.  

So, the answer really is, we need better installers, but they are platform by platform. On Linux, probably need to look at RPM, flatpack and ....

Davo

**Comment by benjbrandall** [comment]
Ok, here's the mac command:

`open tomboy-ng.app --args -o Note.txt`

I'll check for where you've got the documentation on this already. Or do we want single note mode to have its own .note?

**Comment by benjbrandall** [comment]
> need to look at RPM, flatpack

I've had a look at doing this, and it doesn't seem too bad. Assuming using something like Alien would be acceptable to make the RPM? https://www.thegeekstuff.com/2010/11/alien-command-examples

As for Flatpak, looks a little more involved but would be fun for me to try.

**Comment by davidbannon** [comment]
Said Ben -
_Ok, here's the mac command:
open tomboy-ng.app --args -o Note.txt_

Ah, then the help page from the app needs to tell the mac user something different then ?
I better attend to that .....

**Comment by davidbannon** [comment]
Don't worry about it Ben, we have had to come home, some unexpected health issues. Travelled some 1300Km in three days, arrived home yesterday so have access to my Mac.....

**Comment by davidbannon** [comment]
Solved by better documentation about how to launch a Mac app from command line.
