### ISSUE TITLE
v0.18 usage experience

### ISSUE THREAD

**Issue by traumschule** [tomboy-notes/tomboy-ng#73]
Thanks for this release!

On debian (buster, 32bit) i had to install
libcanberra-gtk-module libcanberra-gtk0 to satisfy the new dependency.
(Please mention dependency changes in the release note)

Yay! for the --version flag!

Short feedback longer than expected:

- Clicking "Configure" in the welcome window could activate the
  next tab with unconfigured fields in the preferences window. In the
  spirit of a wizard it could lead me to all fields I should fill out /
  configure.

- Spell: Installed hunspell and hunspell-de-de, but I don't know what to
  fill into the text fiel below "Libary not loaded"

- Please let the search box be configurable in the search window instead
  of in "Basics". The use case may change and users may forget where to
  set it.

- only show one empty note in the tray menu. the menu is too long and i
  have to scroll in it. is the window-height limited? Interesting: when
  i leftclick on it the top of the menu is shown, with rightclick it
  scrolls to the bottom. Clicking on an empty note entry does nothing,
  expected it to open a new note. Actually the empty notes could be
  hidden and the "New note" entry should be shown instead.

- Please close note windows on ESC and CTRL+w. This is a standard in
  many unix GUIs. Also quit in CTRL+q.

- Pasting into the node window does not end \n at the end, but after
  the first line. Bug?

- Good, we preserve a version history in the sync folder!

- Tested the sync between users. #72

Ok, i'll stop it here, guess it's enough already :)

**Comment by davidbannon** [comment]
Hmm, see this -
"Depends: libgtk2.0-0 (>= 2.6), libc6 (>= 2.14), libcanberra-gtk-module" - so, should have got that.
libcanberra-gtk0 ?? I have not see any req for that.  I know we don't, in fact need libcanberra-gtk-module but it grizzels if its not there. Further research ....

I just logged one myself #74 ?  about not finding the debian _hunspell_. Will need to investigate.

_Config search in searchbox_ - yeah, might be a good idea.

"only show one empty note in the tray menu" - well, maybe. But most users quickly fill up those first 10 slots. I don't understand what you mean about _i have to scroll in it._  There might be a fair effort in coding up creating those menu items dynamically, you will have to convince me its really a necessary.

_ESC and CTRL+w.  CTRL+q._ Hmm, ^w is write, and write is auto, so, not really applicible. ESC ?  Gee, as a vi user, I am always hitting ESC, I'd spend half my life reopening windows!  But ^q makes sense. And, possibly, fits in with the Mac users. Will think on it....

_Pasting into the node window does not end \n at the end, but after the first line._  Sorry, don't understand. More information please.

**Comment by traumschule** [comment]
> Gee, as a vi user, I am always hitting ESC, I'd spend half my life
> reopening windows!  But ^q makes sense. And, possibly, fits in with
> the Mac users.

:)

It's in no way urgent but of course the best way is to offer dynamic
mapping adjustable by the user.

(Catching special chars created with ctrl+<any> would be nice though)

**Comment by traumschule** [comment]
> _Pasting into the node window does not end \n at the end, but after
> the first line._  Sorry, don't understand. More information please.

I inserted text into a note. The result was that the line after the
first line was empty and the last line had no newline after it (which is
normal and expected).

**Comment by davidbannon** [comment]
_I know, those menus are time expensive :) Maybe just a if-condition to not create an entry for no note. Screnshot: https://share.riseup.net/#g8k36so9agDm9NyoMHwaww_
The menus are made in a GUI design tool before compilation. It generates all the code to draw the GUI elements at run time. I can write that code myself but am reluctant to do so, it would be a lot of duplicated code, much harder to maintain and error pone.  **But I looked at your image, what are you running it one ?**  The whole length of the menu list should be no more than half the screen on a typical laptop. Maybe a better solution would be to have an option to show only (eg) five menu entries ?

_libcanberra-gtk-module_

OK, that sounds like your install tool did not resolve dependencies. What are you using to install ? Just to be clear, you manually installed both libcanberra-gtk-module and libcanberra-gtk0  ?  Rather than adding to dependencies, I should have them removed from the list, quite sure they are not being used.

Ctrl Q - I need to see how the Mac does this before acting, I don't want to introduce an incompatability. Also, don't know how to 'publish' it, there is no menu item so how does a user find out that it works. Man page but no one reads man pages ....

Davo

**Comment by traumschule** [comment]
> But I looked at your image, what are you running it one ?

i3 (debian buster, 32bit)

> Maybe a better solution would be to have an option to show only (eg)
> five menu entries ?

I assume that would solve this (minor) issue for me. If we want more
later it could become a configuration option?

> OK, that sounds like your install tool did not resolve dependencies.
> What are you using to install ?

just apt.

> Just to be clear, you manually installed both libcanberra-gtk-module
> and libcanberra-gtk0

That's correct.

**Comment by traumschule** [comment]
On Fri, 17 Aug 2018 18:22:32 -0700
davidbannon <notifications@github.com> wrote:

> ^Q now quits (or closes) the note.

That sounds counter intuitive because usually ^W closes a window and ^Q
the whole application.

**Comment by davidbannon** [comment]
I'm not happy with it either. It seems "best practice" might be -
Ctrl F4 - close current window
Alt F4 - close current window
Ctrl -W - delete last word typed
Ctrl Q - restore screen output 
Ctrl Q (sort of) close app in a Mac
.......

About the only consistency I find is Alt-F4 is to close current window. Seems to be recommended in a number of Windows and Linux specs and is one of very few that is not contradicted.
Thoughts ????

**Comment by davidbannon** [comment]
No, ctrl-F4 does seem also popular and no really strong conflicts. Sigh .....

I guess I'd prefer ^F4 over Alt from a key mapping issue cross platform view but only just ....

**Comment by davidbannon** [comment]
Can now select search mode from search box.
expect in release v0.18a   (after I find Debian hunspell library)

**Comment by davidbannon** [comment]
OK, whats left then ?

- Spell Library - seems debian has decided to hide ldconfig from ordinary users !
- Search Box has a Mode button
- I have built in some sanity tests ahead of a sync but I sure found a lot of ways to share a file system that lie to the OS so I still recommend a real file sharing approach.
- Close an edit window with Ctrl F4 - not publicized so don't be afraid to appeal.

The above are all fixed in v0.18a, binaries now available for all except Mac (maybe tomorrow, its getting late!).  You are still to convince me about -

- Shorter / dynamic list of recent notes.
- Turning the config into a wizard.

**Comment by davidbannon** [comment]
New sync engine a lot more careful about ensuring it has appropriate access before starting and even, sort of, recovery mode if something bad happens half way through. But sure not guaranteed !
Just tidying up issues list. I don't think I can help you any more but if I can, please reopen this ticket.
Davo
