### ISSUE TITLE
OSX Icon corrupt and green?

### ISSUE THREAD

**Issue by xypd** [tomboy-notes/tomboy-ng#83]
Similar to this issue #22

There seems to be an issue with the macOS icon. I believe it to be corrupted, since I can't view it in any application that should be able to edit an .icns file.

Corrupted Icon set
<img width="862" alt="corrupted_icon_set" src="https://user-images.githubusercontent.com/23583395/48362210-24eced00-e671-11e8-881f-a0d086250456.png">

Correct Icon set
<img width="935" alt="correct_icon_set" src="https://user-images.githubusercontent.com/23583395/48362212-24eced00-e671-11e8-9ac3-a313d3dca6c8.png">

Here is a icon set I made from a wiki .svg fie. Maybe this will correct it.
[tomboy-ng.icns.zip](https://github.com/tomboy-notes/tomboy-ng/files/2572796/tomboy-ng.icns.zip)

Let me know if you need more help on this.

**Comment by davidbannon** [comment]
Thanks xypd, I will happily admit I struggled with the Mac icons although whats there now does look OK on my one mac test platform (and aging Powerbook I purchased on eBay). 

Did you make those icons yourself and have you clarified the license applicable ?  

I do need tomboy-ng's icon to look different to the Tomboy one so maybe the yellow is not a good idea ?

I am away camping right now so won't be on line very often for another week .....

Davo

**Comment by xypd** [comment]
Hey David, I didn't make them. I simply complied them into an iconset for the .icns format.

How different do you need? These were taking directly from the tomboy wiki page as an svg then convert to png, then complied.

I can help with new icons if you give me the requirements.

Have fun camping!! The internet will still be here :D.

Thanks for checking in.

**Comment by davidbannon** [comment]
OK xypd, maybe we can deal with this first ?  I have an ageing Powerbook running Sierra that I use to do the only Mac test I do.  And on it, the icons show up fine so I am somewhat puzzled why they don't for you.
But that would be due to my very low level of experience with macs !
Now, on my system, I see my (pretty ugly) green icon firstly on the dmg file. Then when you open the dmg file, same image is shown next to the Application Folder. Once you drag the icon into the application folder, again you see my green icon there (its an application bundle).  And, if you start the app, you see it on the dock and while active, you see it in the bar across the top.

Now, which one of those places don't you see it ?  Or don't you see it anywhere ?   

My guess you are using a different screen resolution to me and and my icon set does not contain the right sized icons......

Davo

**Comment by xypd** [comment]
>Did you make those icons yourself and have you clarified the license applicable ?

I used these sources for the icons, [Link to svg](https://upload.wikimedia.org/wikipedia/commons/b/be/Tomboy_logo.svg) , and [link to wiki page of icon](https://en.wikipedia.org/wiki/File:Tomboy_logo.svg). Then made the .scrn file locally.

>I do need tomboy-ng's icon to look different to the Tomboy one so maybe the yellow is not a good idea ?

So we can use the one they made at all? Would just changing the color be enough? For example I could just change the colors of the original icon so it look different. Or do we need to make one completely from scratch?


>OK xypd, maybe we can deal with this first ? I have an ageing Powerbook running Sierra that I use to do the only Mac test I do. And on it, the icons show up fine so I am somewhat puzzled why they don't for you.

They do should up as your green icon without a problem. I was just under the impression that it was just a temporary icon and you would updated it later with the original app icon. But perhaps this was mistaken thinking on my part. But it does appear that ng is missing some sizes which means they will most likely look a bit blurry on retina/High DPI Mac screens.


>Now, which one of those places don't you see it ? Or don't you see it anywhere ?

I can see the green icon in most places. But in the first post it shows that it's missing in 5 places. I think one of those is missing in file> about menu. Also in the mount installer image directory as well.

![grn_icons1](https://user-images.githubusercontent.com/23583395/49353575-785cc480-f68c-11e8-985e-6cbbd5f336cd.png)
![grn_icons3](https://user-images.githubusercontent.com/23583395/49353578-785cc480-f68c-11e8-8fe4-2e3dbf35ea1e.png)
![grn_icons2](https://user-images.githubusercontent.com/23583395/49353576-785cc480-f68c-11e8-87c0-dbfc10c18a7e.png)

**Comment by davidbannon** [comment]
OK, now that is interesting !
On my powerbook, the two you show as having default icons use my (not very attractive) green icons.  As you say, thats probably because of the issue that my icon package is missing some resolutions. And I am missing some platforms to test on !
I really like your idea of making a green version of the original Tomboy icon. I (clearly) don't know enough to do that, if you could do it for me, that would be great !

Given that the original is on wikipedia under LGLP, we are sure free to use it here. And, tomboy-ng does have the blessing of the Tomboy author (or at least those still around).

I plan to get a new release out in the next few days, be magic if you could help before then but if thats too soon, then the release after that will be fine.

Thanks for your help.

Davo

**Comment by xypd** [comment]
I can help out with this. I'll see if I can maybe make new one though :D. If I run out of time then I can just colorize the original one. Do you need me to give them to you in the .icns format?

**Comment by davidbannon** [comment]
Yes please, its the converting to icns thats an issue for me.
I also use a set of png 16x16 22x22 24x24 32x32 48x48 256x256 so if you could suppy those native that would be great. But in can generate them myself if you you give me the svg.....

**Comment by xypd** [comment]
Just a heads up, I haven't begun to work on the icons. Please don't wait for them if your planning a release soon. So other work need to be completed first. But have it on my list of todos.

**Comment by davidbannon** [comment]
No worries xypd, I'll go ahead with the release and will mention the Mac icons as a 'known issue'.
Thanks
Davo

**Comment by xypd** [comment]
Good news I finally put in time on the icons. @davidbannon please have a look and tell me what you think good or bad :).

I made a version as you requested in green. But also took the liberty to make a complete new version too.

And anyone else feel free to chime in.

![tomboy-ng_icons_concepts1](https://user-images.githubusercontent.com/23583395/61062692-aba6c500-a3cc-11e9-96d6-babd04a8e15f.png)

**Comment by davidbannon** [comment]
Wow, nice work xypd, nice work indeed.
Sorry I have not responded earlier, traveling in some remote places and internet access is just not there sometimes.
I don't have my Mac with me so cannot test but I don't expect any testing would be necessary (or, given me not seeing the problem you are addressing, useful).  So, its a case of choosing what ever looks the most appropriate ?  
Your Ver.A through to Ver.E ?  Are they all part of a set or are you suggesting we choose of of them ?  I really like the ones with the pen rather than just the blank pad, its more Tomboy style. 
I'd also need a Volume icon for the Mac, I have a crude drive drawing over the icon at present, it sucks !

Thank xypd !

**Comment by xypd** [comment]
Thanks @davidbannon, glade you like them. No worries about the time. We all have lives :D.

I think the color version with the pen is the ideal version. 

Let me break down what I was thinking and see if this is something you're interested in.

We could take the opportunity to update all the icons for all platforms

- Would need all the sizes and format for windows, Mac and Linux
- We can use one of the outlined version for black and white specific, like the menubar or similar
- We could also make some dynamic vers that can show stuff like updating, syncing, or errors. Though I’m not sure how this can work on the back end. Just a thought.
- I would probably say though that the icon vers without the pen could work better for menu and small 16x16 uses.

Lastly, are we in agreement that the green vers of the original is not ideal and should be shelfed?

Looking forward to seeing these in the wild.

**Comment by davidbannon** [comment]
Hello XYPD, long time since I followed this up !
Are you still keen to play ?  I sure would like to update the icons if possible. I am just now rushing to get a new version out, now that I am finally home and can again test on Windows and Mac. I would like to get a new release out rather quickly, a lot of mainly bug fixes have built up while I was away. Major new feature is support for non-english versions, but at least one important bug fix....

**Comment by xypd** [comment]
No worries. And yeah I'm still would love for these icons be used.

Should I fork this and try to replace them where ever I find the green icon referenced?

Could be good practice :).

I found icons in these dir or areas:
- https://github.com/tomboy-notes/tomboy-ng/blob/master/tomboy-ng/Tomboy_NG.ico
- https://github.com/tomboy-notes/tomboy-ng/tree/master/glyphs

Are there more some place else?

**Comment by davidbannon** [comment]
Hmm, not sure about doing a pull request. I might be better manually putting them into the IDE, some processing happens there, unsure what....

**Comment by davidbannon** [comment]
Yeah, makes sense. I guess I have a number of competing issues -
I want to retain that link to Tomboy, there really is nothing original in tomboy-ng, its all its presentation ideas comes from Tomboy. 
But since Tomboy was made, GUI have changed a lot, while I need the very low res SystemTray icon, we also need to use some 256x256 and what looks good in 16x16 often looks doppy at higher res. You clearly know lots more than me about such things.
A black and white one for the dark theme people is a great idea I am not sure I can change some of them dynamically, will need to do some experimenting. Windows is hard, images embedded in binary, the SystemTray icon is loaded at design time, will have to experiment there too. 

**Sizes and files needed**
On Linux, the advice I got was to have a set of icons, 16x16 to 256x256 but I suspect that all that is loaded is the 48x48. Only way to be sure is, perhaps, strace. But clearly, it will also depend a bit on the end users screen resolution. But that won't help on the Mac or Windows.....

Lets assume I need 16x16, 22x22, 24x24, 32,32, 48x48 and 256x256 for linux.
I need the icns file for Mac, and a separate volume icns one too. Looks like my Mac build script only uses the existing ICNS files, so you can change all of that just with new ICNS files.
From memory, all I need on windows is the application icon and System tray icon. 48x48 and 16x16 but I am not sure. 
If you make be a black and white set too, I'll experiment with trying to switch to them at run time for Dark Theme. Think its easy on Linux, no idea on the Mac, hard on Windows.....

**Which one to use ?**
Of the coloured ones, I think your ver 1 and 2 look far better than my poor attempt. And from your recent post, seem to scale OK too (?). Your colour changed Tomboy one has the advantage of looking like the regional and being green continuing a tomboy-ng tradition. But I still think your Ver 1 and 2 look better !

**Comment by davidbannon** [comment]
just starting to do some pre release testing ....

Davo

**Comment by xypd** [comment]
Hey Davo,

Made some time for some updates. Please let me know if you have issues and need new versions. Hopefully everything works with out any problems.

I'm providing the following, full color, black and white versions:
- Linux
  - 16, 22, 24, 32, 64, 128, 256, 512
- Mac icns
  - 16, 32, 64, 128, 256, 512, 1024
- Windows
  - 16, 32, 48, 64, 128, 256, 512

For the linux and Window batches, you can simply use what you need. for the Mac version I've included the .icns in the zip files.

[Full_color.zip](https://github.com/tomboy-notes/tomboy-ng/files/4006996/Full_color.zip)
[White.zip](https://github.com/tomboy-notes/tomboy-ng/files/4006997/White.zip)
[Black.zip](https://github.com/tomboy-notes/tomboy-ng/files/4006998/Black.zip)
[tomboyNG.svg.zip](https://github.com/tomboy-notes/tomboy-ng/files/4007001/tomboyNG.svg.zip)

**Comment by davidbannon** [comment]
Right !
I have merged your pull request, looks great. Nice to emphasis the cross platform look.
I need to put the icons in via my IDE, would like to look into selecting particular ones at run time so look better on (eg) dark themes. The black or white ones clearly targeted at Mac. Interesting ....

**Comment by davidbannon** [comment]
I have checked in code using the updated icons. Wow, it does look good. I have, so far, used only the coloured ones, the yellow pad.  I think you intend the black and while ones for the tray icon on the Mac ?  Do all Macs use a black background to the trayicon bar ?  I have code working that lets me load an alternative (to the default coloured) icon at startup but uncertain how I can be sure its appropriate.  I did not find the black or white ones very 'safe' on the various Linux desktops I tried. Even with dark themes the yellow coloured tray icon looked better. To my uneducated eye.
Thoughts ?

**Comment by aguador** [comment]
Intrusion here from a Linux user: these are reallly nice icons! I have always liked the yellow pads because I think the original Post-Its were yellow only (nothing to do with original Tomboy). However, even the redesigned green is quite sharp.

I have never been a fan of B&W icons, and would note that for the visually impaired colour can be an aid. However, if this is a particular Mac style and can be kept for it rather than Linux . . . .

**Comment by davidbannon** [comment]
You should see the coloured one in use !
Maybe I need to cut a 0.25a ?  Maybe after we get to bottom of a few other issues mentioned in other threads....
Anyway, thanks xypd, cool !
Davo

**Comment by xypd** [comment]
I'm very excited to see them in action and glade you guys like them. And you're very welcome Davo, happy to contribute.

As for the B&W vers., my use case thoughts as following.

1. Color icon is standard default on all platforms.
2. The white would be use only on darkmode or user selected
3. The black vers would be for user (maybe only Mac) that want a BW icon to match the other black and white ones provided by apple in the menubar(aka, menu tray).

I don't think the BW icon should be used for anything other than menu try. I design them mainly for sizes from maybe 16-32px

So I can see you adding a option in the settings maybe via a drop down that lets the user select the color they want to manually. Some might complain about having to change it, but I personally enjoy this option versus none.

aguador, no intrusion I appreciate your and others input into this.

Since everyone has different taste and needs I do think use of the BW vers should be an choice so people like you who don't particularly like them doesn't need to use them. But also allows this who want a limited amount of colors on the screen distracting them can use the BW vers. (ex designers, video editors, etc).

To your comment on about visually impaired, it funny I actually thought that the simple design and higher contrast would be helpful ... think mobile phone top menu area (signal, carrier, battery etc). But I can also image if you have a bunch of icons another BW one could be harder to see vs a colored one. However if we can choose the icon we want, then I think this will not be an issue.

Additionally, if possible it could give us the opportunity to add color to indicate apps state. So red could mean issue/unsaved, yellow could be syncing, green could be backed up ... etc. These are just ideas that popped in my head :D.

Of course I will need to review how it actually works in use and make adjustment if needed. So Davo if you want to compile a beta vers and make it available to me (or everyone) so I can try it out, that could be helpful.

cheers

**Comment by aguador** [comment]
@xypd Just tested an installation script with updated ng from Davo so got to see the new yellow icons. They are really slick. A great addition to ng.

The only tiny thing I noted was that on smaller icons (specifically my 30 pixel high panel on an 11,6" screen), the pencil does not stand out terribly well. Perhaps a slight change in tone or more shadow would give it better definition? I just glanced back at the icons and see that Tomboy had a brown pencil. Using the same/virtually the same colour with the changed position of the pencil might be the way to go. However, even with no change the icons are great.

(I just realised working on a Mac you have a greater screen resolution, so the contrast may be better. Those higher resolution screens are the one thing I really like about the Macs, although the laptops for the rest of us are finally starting to get a bit higher resolution.)

As far as the B&W icons, I did not mean to imply they should not be offered. They certainly have their place.

**Comment by xypd** [comment]
Cool that you tested it out! Glade your enjoying them.

Taking a quick look I can see how this could be an issue. Would you mine sharing a screenshot of what you're seeing? Also Should I assume you were talking about 32px, since I didn't make a 30px vers? If a 30px is needed it should be added since it can of course change the clarity of the icon at the wrong size.

When I get some time I can edit the icon to see if I can bring up the contrast on the pencil.

And appreciate you all views, so no worries on the BW comments. I didn't take them negatively, more I was trying to point out a use case for them.

**Comment by davidbannon** [comment]
My guess is aguador is referring to the system tray icon on Linux, I convert that to an ICO file from the 24x24 png.  I agree it does, perhaps lack definition because of its small size. Not sure if its worth having multiple master artworks to deal with the small ones. From memory, the kit includes 24x24, 22x22 and 16x16.  The larger ones do look better.

**Comment by xypd** [comment]
Once I can load it on my linux vm I can hopefully see. But only then can I assess if there are good solutions. For example creating new version with more contrast for maybe 32 and smaller.

But won't start anything of course until I see them on multiple platforms.

For example vers B row could be a go starting point. Or simply adding some darker highlights or shadows in the current version.

**Comment by aguador** [comment]
Here is a screenshot of the notification area on the panel:

![ng-panel-icon](https://user-images.githubusercontent.com/8114758/71802223-6e5e7f80-305d-11ea-98ef-f3d3bece3b39.png)

It is 30px high, so whichever icon is used is adjusted to the height of the panel. The systems I have used normally default to around 40px high, but I use between 28 and 32 as I can see enough to select whatever I need with that.

The screenshot seems a bit sharper, which led me to play around. The difference is the viewing angle. My initial reaction was to seeing the icon on this small screen with the panel at the bottom and the computer, literally, in my lap. I just moved the panel to the top of the sreen and, even with the machine in my lap, I can see it more clearly. So my original comment is based on the worst case scenario: small screen, small panel, panel at the bottom and screen about as far away as practicable. Even under those conditions the icon works well, so it is not clear that any change is worth the effort.

PS As I think I mentioned to Davo once, the original, flat green icon always looked overpowering in the notification area. Here with the angle it fits better with the other icons, particularly the Pidgin (chat) icon next to it.

**Comment by davidbannon** [comment]
Now, I suspect the icon in aguador's screenshot has not been scaled, if you zoom in in a pixel viewer its still the original 24x24, plus some black border. Attached is a screenshot of aguador's and xypd's original 24x24 side by side. No scaling.
![icon](https://user-images.githubusercontent.com/6291248/71808900-02166700-30c3-11ea-8084-7bc4b992fe92.png)

**Comment by xypd** [comment]
Yeah it looks much blurrier in aguador's vers.

I'm wondering if his settings are grabbing the 24 (or even the 16!) when it should probably use the 28 or 32 vers. Is there anyway to tell for sure?

![TBNG_pixel-check](https://user-images.githubusercontent.com/23583395/71851432-8efdf800-30a4-11ea-8614-cdeba27d878c.png)

**Comment by davidbannon** [comment]
No, I  am pretty sure he is refering to the the System Tray Icon and that is dealt with differently.  That Icon is assigned at build time, its not loaded dynamically (although I can if necessary). The general but vague advice is that it should be a 24x24 bitmap and is not scaled. But maybe his KDE is playing with it.

**Comment by xypd** [comment]
Ah, I see. Thanks for that info.

**Comment by xypd** [comment]
So awesome this is live @davidbannon. Looking good. But I do see a few place where it can be improved on the Mac. Will also try to install them on windows and ubuntu, once I get a chance.

Quick feedback is I see a few icon blurry or room for improvement on the Mac.

Will need to determine if there is something I can do.

**Comment by aguador** [comment]
>But maybe his KDE is playing with it.

I hope not, Davo, given that it was an XFCE desktop!

Before seeing the new 0.26 release I copied over 0.25a and the icons to my Enlightenment desktop. For reference, here is the new icon on a 32px mostly transparent shelf (panel, taskbar). This is the same 1366x768 12,6" screen as the shot from MX Linux's XFCE desktop.

![ng-panel-icon-E22-2020-01-15](https://user-images.githubusercontent.com/8114758/72430287-3b6d6780-3792-11ea-9b1a-d059aa59972d.png)

(Off-topic: I still have pending the issue of the triangle in the systray. The second one is for Pidgin, the common denominator between the two being gtk. Systray icon for Qt-based VLC player displays properly.)

**Comment by xypd** [comment]
@aguador that actually look pretty good. Much better than your last one for sure. I'm not sure I follow your comment on the triangle. Do you mean it not display properly or that you not sure if you like the shape of a triangle in your tray?

**Comment by aguador** [comment]
@xypd

**Comment by davidbannon** [comment]
Overall, I think the new icons look great in every spot except the (small) System tray.  Particularly good on the Mac IMHO.
Don't worry about the problems on Enlightenment, thats an issue between GTK and Enlightenment as aguador mentioned.  I think they work OK using QT5 from memory ?  I have not tested 0.26 on Enlightenment with Qt5 - sigh, too many combinations ....
On my linux boxes, the TrayIcon does look a bit fuzzier than desired but its OK, usable. But a maybe a simpler version is needed for lower resolution images. 16x16, 22x22 and 24x24. But I suspect that Linux only uses the 48x48 and scales it where necessary for the dock, menu items and filemanager stuff.  I think (?) that pretty universal across most different distros but as aguador pointed out, not 'all'. And I use the 22x22 (or is that the 24x24 ?) for System tray, I need to do some experiments there to understand it better.  Will make a tool to change its icons as a user controlled test. To load at run time, they have to be converted to (windows) icon format ....
But, honestly, looks pretty good now on most platforms !

**Comment by davidbannon** [comment]
Here is something to look at. On the left is the 24x24 icon that xypd made, the the right is the same icon but 'sharpened' in mtPaint. Thoughts ?
On Ubuntu Mate ....
![tb_icon_sharp](https://user-images.githubusercontent.com/6291248/72672436-0fadf280-3aae-11ea-9944-1f3588703c38.png)

**Comment by aguador** [comment]
Viewing this on my small screen at some distance, the detail is much clearer on the right. Nice enhancement.

**Comment by davidbannon** [comment]
OK, this is done.  Thanks again xypd, its a huge improvement and one that was needed !
Davo
