### ISSUE TITLE
[Win 10] Undo/Redo don't seem to exist

### ISSUE THREAD

**Issue by MatthewJohnHayden** [tomboy-notes/tomboy-ng#97]
I just lost a whole note by unfortunately selecting all the content and typing...

I hit Ctrl+Z to no effect, then searched the interface for an Undo button, coming up dry.

I am guessing such a  feature does not exist as of version 0.21

**Comment by davidbannon** [comment]
I am afraid not Matthew. And given that it would need to be implemented in a component (KControls) used by the project (rather than in 13K lines of my code) its not likely to happen soon.
I guess you did not make an snapshot or sync elsewhere ?
If you have a sync, leave the sadly empty note where it is, make some change on the other system, and sync, the sync clash detector will show you the difference, obviously choose the intact note.
If you don't sync, then please make a snapshot from time to time. Too late to help now ......
(so easy to be wise after the event :-)  )
David

**Comment by davidbannon** [comment]
As I don't intend, in the immediate future to correct this ommision, I will close this.  Its a very valid question but not one I have a good answer too.
